// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "EventResearch.pb.h"
// @@protoc_insertion_point(imports)

@implementation EventResearchRoot
static PBExtensionRegistry* extensionRegistry = nil;
+ (PBExtensionRegistry*) extensionRegistry {
  return extensionRegistry;
}

+ (void) initialize {
  if (self == [EventResearchRoot class]) {
    PBMutableExtensionRegistry* registry = [PBMutableExtensionRegistry registry];
    [self registerAllExtensions:registry];
    [StructureRoot registerAllExtensions:registry];
    [UserRoot registerAllExtensions:registry];
    extensionRegistry = registry;
  }
}
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry {
}
@end

@interface PerformResearchRequestProto ()
@property (strong) MinimumUserProto* sender;
@property int32_t researchId;
@property (strong) NSString* userResearchUuid;
@property int64_t clientTime;
@property int32_t gemsCost;
@property int32_t resourceCost;
@property ResourceType resourceType;
@end

@implementation PerformResearchRequestProto

- (BOOL) hasSender {
  return !!hasSender_;
}
- (void) setHasSender:(BOOL) value_ {
  hasSender_ = !!value_;
}
@synthesize sender;
- (BOOL) hasResearchId {
  return !!hasResearchId_;
}
- (void) setHasResearchId:(BOOL) value_ {
  hasResearchId_ = !!value_;
}
@synthesize researchId;
- (BOOL) hasUserResearchUuid {
  return !!hasUserResearchUuid_;
}
- (void) setHasUserResearchUuid:(BOOL) value_ {
  hasUserResearchUuid_ = !!value_;
}
@synthesize userResearchUuid;
- (BOOL) hasClientTime {
  return !!hasClientTime_;
}
- (void) setHasClientTime:(BOOL) value_ {
  hasClientTime_ = !!value_;
}
@synthesize clientTime;
- (BOOL) hasGemsCost {
  return !!hasGemsCost_;
}
- (void) setHasGemsCost:(BOOL) value_ {
  hasGemsCost_ = !!value_;
}
@synthesize gemsCost;
- (BOOL) hasResourceCost {
  return !!hasResourceCost_;
}
- (void) setHasResourceCost:(BOOL) value_ {
  hasResourceCost_ = !!value_;
}
@synthesize resourceCost;
- (BOOL) hasResourceType {
  return !!hasResourceType_;
}
- (void) setHasResourceType:(BOOL) value_ {
  hasResourceType_ = !!value_;
}
@synthesize resourceType;
- (id) init {
  if ((self = [super init])) {
    self.sender = [MinimumUserProto defaultInstance];
    self.researchId = 0;
    self.userResearchUuid = @"";
    self.clientTime = 0L;
    self.gemsCost = 0;
    self.resourceCost = 0;
    self.resourceType = ResourceTypeCash;
  }
  return self;
}
static PerformResearchRequestProto* defaultPerformResearchRequestProtoInstance = nil;
+ (void) initialize {
  if (self == [PerformResearchRequestProto class]) {
    defaultPerformResearchRequestProtoInstance = [[PerformResearchRequestProto alloc] init];
  }
}
+ (PerformResearchRequestProto*) defaultInstance {
  return defaultPerformResearchRequestProtoInstance;
}
- (PerformResearchRequestProto*) defaultInstance {
  return defaultPerformResearchRequestProtoInstance;
}
- (BOOL) isInitialized {
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasSender) {
    [output writeMessage:1 value:self.sender];
  }
  if (self.hasResearchId) {
    [output writeInt32:2 value:self.researchId];
  }
  if (self.hasUserResearchUuid) {
    [output writeString:3 value:self.userResearchUuid];
  }
  if (self.hasClientTime) {
    [output writeInt64:4 value:self.clientTime];
  }
  if (self.hasGemsCost) {
    [output writeInt32:5 value:self.gemsCost];
  }
  if (self.hasResourceCost) {
    [output writeSInt32:6 value:self.resourceCost];
  }
  if (self.hasResourceType) {
    [output writeEnum:7 value:self.resourceType];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (SInt32) serializedSize {
  __block SInt32 size_ = memoizedSerializedSize;
  if (size_ != -1) {
    return size_;
  }

  size_ = 0;
  if (self.hasSender) {
    size_ += computeMessageSize(1, self.sender);
  }
  if (self.hasResearchId) {
    size_ += computeInt32Size(2, self.researchId);
  }
  if (self.hasUserResearchUuid) {
    size_ += computeStringSize(3, self.userResearchUuid);
  }
  if (self.hasClientTime) {
    size_ += computeInt64Size(4, self.clientTime);
  }
  if (self.hasGemsCost) {
    size_ += computeInt32Size(5, self.gemsCost);
  }
  if (self.hasResourceCost) {
    size_ += computeSInt32Size(6, self.resourceCost);
  }
  if (self.hasResourceType) {
    size_ += computeEnumSize(7, self.resourceType);
  }
  size_ += self.unknownFields.serializedSize;
  memoizedSerializedSize = size_;
  return size_;
}
+ (PerformResearchRequestProto*) parseFromData:(NSData*) data {
  return (PerformResearchRequestProto*)[[[PerformResearchRequestProto builder] mergeFromData:data] build];
}
+ (PerformResearchRequestProto*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (PerformResearchRequestProto*)[[[PerformResearchRequestProto builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (PerformResearchRequestProto*) parseFromInputStream:(NSInputStream*) input {
  return (PerformResearchRequestProto*)[[[PerformResearchRequestProto builder] mergeFromInputStream:input] build];
}
+ (PerformResearchRequestProto*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (PerformResearchRequestProto*)[[[PerformResearchRequestProto builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (PerformResearchRequestProto*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (PerformResearchRequestProto*)[[[PerformResearchRequestProto builder] mergeFromCodedInputStream:input] build];
}
+ (PerformResearchRequestProto*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (PerformResearchRequestProto*)[[[PerformResearchRequestProto builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (PerformResearchRequestProto_Builder*) builder {
  return [[PerformResearchRequestProto_Builder alloc] init];
}
+ (PerformResearchRequestProto_Builder*) builderWithPrototype:(PerformResearchRequestProto*) prototype {
  return [[PerformResearchRequestProto builder] mergeFrom:prototype];
}
- (PerformResearchRequestProto_Builder*) builder {
  return [PerformResearchRequestProto builder];
}
- (PerformResearchRequestProto_Builder*) toBuilder {
  return [PerformResearchRequestProto builderWithPrototype:self];
}
- (void) writeDescriptionTo:(NSMutableString*) output withIndent:(NSString*) indent {
  if (self.hasSender) {
    [output appendFormat:@"%@%@ {\n", indent, @"sender"];
    [self.sender writeDescriptionTo:output
                         withIndent:[NSString stringWithFormat:@"%@  ", indent]];
    [output appendFormat:@"%@}\n", indent];
  }
  if (self.hasResearchId) {
    [output appendFormat:@"%@%@: %@\n", indent, @"researchId", [NSNumber numberWithInteger:self.researchId]];
  }
  if (self.hasUserResearchUuid) {
    [output appendFormat:@"%@%@: %@\n", indent, @"userResearchUuid", self.userResearchUuid];
  }
  if (self.hasClientTime) {
    [output appendFormat:@"%@%@: %@\n", indent, @"clientTime", [NSNumber numberWithLongLong:self.clientTime]];
  }
  if (self.hasGemsCost) {
    [output appendFormat:@"%@%@: %@\n", indent, @"gemsCost", [NSNumber numberWithInteger:self.gemsCost]];
  }
  if (self.hasResourceCost) {
    [output appendFormat:@"%@%@: %@\n", indent, @"resourceCost", [NSNumber numberWithInteger:self.resourceCost]];
  }
  if (self.hasResourceType) {
    [output appendFormat:@"%@%@: %@\n", indent, @"resourceType", [NSNumber numberWithInteger:self.resourceType]];
  }
  [self.unknownFields writeDescriptionTo:output withIndent:indent];
}
- (BOOL) isEqual:(id)other {
  if (other == self) {
    return YES;
  }
  if (![other isKindOfClass:[PerformResearchRequestProto class]]) {
    return NO;
  }
  PerformResearchRequestProto *otherMessage = other;
  return
      self.hasSender == otherMessage.hasSender &&
      (!self.hasSender || [self.sender isEqual:otherMessage.sender]) &&
      self.hasResearchId == otherMessage.hasResearchId &&
      (!self.hasResearchId || self.researchId == otherMessage.researchId) &&
      self.hasUserResearchUuid == otherMessage.hasUserResearchUuid &&
      (!self.hasUserResearchUuid || [self.userResearchUuid isEqual:otherMessage.userResearchUuid]) &&
      self.hasClientTime == otherMessage.hasClientTime &&
      (!self.hasClientTime || self.clientTime == otherMessage.clientTime) &&
      self.hasGemsCost == otherMessage.hasGemsCost &&
      (!self.hasGemsCost || self.gemsCost == otherMessage.gemsCost) &&
      self.hasResourceCost == otherMessage.hasResourceCost &&
      (!self.hasResourceCost || self.resourceCost == otherMessage.resourceCost) &&
      self.hasResourceType == otherMessage.hasResourceType &&
      (!self.hasResourceType || self.resourceType == otherMessage.resourceType) &&
      (self.unknownFields == otherMessage.unknownFields || (self.unknownFields != nil && [self.unknownFields isEqual:otherMessage.unknownFields]));
}
- (NSUInteger) hash {
  __block NSUInteger hashCode = 7;
  if (self.hasSender) {
    hashCode = hashCode * 31 + [self.sender hash];
  }
  if (self.hasResearchId) {
    hashCode = hashCode * 31 + [[NSNumber numberWithInteger:self.researchId] hash];
  }
  if (self.hasUserResearchUuid) {
    hashCode = hashCode * 31 + [self.userResearchUuid hash];
  }
  if (self.hasClientTime) {
    hashCode = hashCode * 31 + [[NSNumber numberWithLongLong:self.clientTime] hash];
  }
  if (self.hasGemsCost) {
    hashCode = hashCode * 31 + [[NSNumber numberWithInteger:self.gemsCost] hash];
  }
  if (self.hasResourceCost) {
    hashCode = hashCode * 31 + [[NSNumber numberWithInteger:self.resourceCost] hash];
  }
  if (self.hasResourceType) {
    hashCode = hashCode * 31 + self.resourceType;
  }
  hashCode = hashCode * 31 + [self.unknownFields hash];
  return hashCode;
}
@end

@interface PerformResearchRequestProto_Builder()
@property (strong) PerformResearchRequestProto* result;
@end

@implementation PerformResearchRequestProto_Builder
@synthesize result;
- (id) init {
  if ((self = [super init])) {
    self.result = [[PerformResearchRequestProto alloc] init];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return result;
}
- (PerformResearchRequestProto_Builder*) clear {
  self.result = [[PerformResearchRequestProto alloc] init];
  return self;
}
- (PerformResearchRequestProto_Builder*) clone {
  return [PerformResearchRequestProto builderWithPrototype:result];
}
- (PerformResearchRequestProto*) defaultInstance {
  return [PerformResearchRequestProto defaultInstance];
}
- (PerformResearchRequestProto*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (PerformResearchRequestProto*) buildPartial {
  PerformResearchRequestProto* returnMe = result;
  self.result = nil;
  return returnMe;
}
- (PerformResearchRequestProto_Builder*) mergeFrom:(PerformResearchRequestProto*) other {
  if (other == [PerformResearchRequestProto defaultInstance]) {
    return self;
  }
  if (other.hasSender) {
    [self mergeSender:other.sender];
  }
  if (other.hasResearchId) {
    [self setResearchId:other.researchId];
  }
  if (other.hasUserResearchUuid) {
    [self setUserResearchUuid:other.userResearchUuid];
  }
  if (other.hasClientTime) {
    [self setClientTime:other.clientTime];
  }
  if (other.hasGemsCost) {
    [self setGemsCost:other.gemsCost];
  }
  if (other.hasResourceCost) {
    [self setResourceCost:other.resourceCost];
  }
  if (other.hasResourceType) {
    [self setResourceType:other.resourceType];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (PerformResearchRequestProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (PerformResearchRequestProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSetBuilder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    SInt32 tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 10: {
        MinimumUserProto_Builder* subBuilder = [MinimumUserProto builder];
        if (self.hasSender) {
          [subBuilder mergeFrom:self.sender];
        }
        [input readMessage:subBuilder extensionRegistry:extensionRegistry];
        [self setSender:[subBuilder buildPartial]];
        break;
      }
      case 16: {
        [self setResearchId:[input readInt32]];
        break;
      }
      case 26: {
        [self setUserResearchUuid:[input readString]];
        break;
      }
      case 32: {
        [self setClientTime:[input readInt64]];
        break;
      }
      case 40: {
        [self setGemsCost:[input readInt32]];
        break;
      }
      case 48: {
        [self setResourceCost:[input readSInt32]];
        break;
      }
      case 56: {
        ResourceType value = (ResourceType)[input readEnum];
        if (ResourceTypeIsValidValue(value)) {
          [self setResourceType:value];
        } else {
          [unknownFields mergeVarintField:7 value:value];
        }
        break;
      }
    }
  }
}
- (BOOL) hasSender {
  return result.hasSender;
}
- (MinimumUserProto*) sender {
  return result.sender;
}
- (PerformResearchRequestProto_Builder*) setSender:(MinimumUserProto*) value {
  result.hasSender = YES;
  result.sender = value;
  return self;
}
- (PerformResearchRequestProto_Builder*) setSender_Builder:(MinimumUserProto_Builder*) builderForValue {
  return [self setSender:[builderForValue build]];
}
- (PerformResearchRequestProto_Builder*) mergeSender:(MinimumUserProto*) value {
  if (result.hasSender &&
      result.sender != [MinimumUserProto defaultInstance]) {
    result.sender =
      [[[MinimumUserProto builderWithPrototype:result.sender] mergeFrom:value] buildPartial];
  } else {
    result.sender = value;
  }
  result.hasSender = YES;
  return self;
}
- (PerformResearchRequestProto_Builder*) clearSender {
  result.hasSender = NO;
  result.sender = [MinimumUserProto defaultInstance];
  return self;
}
- (BOOL) hasResearchId {
  return result.hasResearchId;
}
- (int32_t) researchId {
  return result.researchId;
}
- (PerformResearchRequestProto_Builder*) setResearchId:(int32_t) value {
  result.hasResearchId = YES;
  result.researchId = value;
  return self;
}
- (PerformResearchRequestProto_Builder*) clearResearchId {
  result.hasResearchId = NO;
  result.researchId = 0;
  return self;
}
- (BOOL) hasUserResearchUuid {
  return result.hasUserResearchUuid;
}
- (NSString*) userResearchUuid {
  return result.userResearchUuid;
}
- (PerformResearchRequestProto_Builder*) setUserResearchUuid:(NSString*) value {
  result.hasUserResearchUuid = YES;
  result.userResearchUuid = value;
  return self;
}
- (PerformResearchRequestProto_Builder*) clearUserResearchUuid {
  result.hasUserResearchUuid = NO;
  result.userResearchUuid = @"";
  return self;
}
- (BOOL) hasClientTime {
  return result.hasClientTime;
}
- (int64_t) clientTime {
  return result.clientTime;
}
- (PerformResearchRequestProto_Builder*) setClientTime:(int64_t) value {
  result.hasClientTime = YES;
  result.clientTime = value;
  return self;
}
- (PerformResearchRequestProto_Builder*) clearClientTime {
  result.hasClientTime = NO;
  result.clientTime = 0L;
  return self;
}
- (BOOL) hasGemsCost {
  return result.hasGemsCost;
}
- (int32_t) gemsCost {
  return result.gemsCost;
}
- (PerformResearchRequestProto_Builder*) setGemsCost:(int32_t) value {
  result.hasGemsCost = YES;
  result.gemsCost = value;
  return self;
}
- (PerformResearchRequestProto_Builder*) clearGemsCost {
  result.hasGemsCost = NO;
  result.gemsCost = 0;
  return self;
}
- (BOOL) hasResourceCost {
  return result.hasResourceCost;
}
- (int32_t) resourceCost {
  return result.resourceCost;
}
- (PerformResearchRequestProto_Builder*) setResourceCost:(int32_t) value {
  result.hasResourceCost = YES;
  result.resourceCost = value;
  return self;
}
- (PerformResearchRequestProto_Builder*) clearResourceCost {
  result.hasResourceCost = NO;
  result.resourceCost = 0;
  return self;
}
- (BOOL) hasResourceType {
  return result.hasResourceType;
}
- (ResourceType) resourceType {
  return result.resourceType;
}
- (PerformResearchRequestProto_Builder*) setResourceType:(ResourceType) value {
  result.hasResourceType = YES;
  result.resourceType = value;
  return self;
}
- (PerformResearchRequestProto_Builder*) clearResourceTypeList {
  result.hasResourceType = NO;
  result.resourceType = ResourceTypeCash;
  return self;
}
@end

@interface PerformResearchResponseProto ()
@property (strong) MinimumUserProto* sender;
@property PerformResearchResponseProto_PerformResearchStatus status;
@property (strong) NSString* userResearchUuid;
@end

@implementation PerformResearchResponseProto

- (BOOL) hasSender {
  return !!hasSender_;
}
- (void) setHasSender:(BOOL) value_ {
  hasSender_ = !!value_;
}
@synthesize sender;
- (BOOL) hasStatus {
  return !!hasStatus_;
}
- (void) setHasStatus:(BOOL) value_ {
  hasStatus_ = !!value_;
}
@synthesize status;
- (BOOL) hasUserResearchUuid {
  return !!hasUserResearchUuid_;
}
- (void) setHasUserResearchUuid:(BOOL) value_ {
  hasUserResearchUuid_ = !!value_;
}
@synthesize userResearchUuid;
- (id) init {
  if ((self = [super init])) {
    self.sender = [MinimumUserProto defaultInstance];
    self.status = PerformResearchResponseProto_PerformResearchStatusSuccess;
    self.userResearchUuid = @"";
  }
  return self;
}
static PerformResearchResponseProto* defaultPerformResearchResponseProtoInstance = nil;
+ (void) initialize {
  if (self == [PerformResearchResponseProto class]) {
    defaultPerformResearchResponseProtoInstance = [[PerformResearchResponseProto alloc] init];
  }
}
+ (PerformResearchResponseProto*) defaultInstance {
  return defaultPerformResearchResponseProtoInstance;
}
- (PerformResearchResponseProto*) defaultInstance {
  return defaultPerformResearchResponseProtoInstance;
}
- (BOOL) isInitialized {
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasSender) {
    [output writeMessage:1 value:self.sender];
  }
  if (self.hasStatus) {
    [output writeEnum:2 value:self.status];
  }
  if (self.hasUserResearchUuid) {
    [output writeString:3 value:self.userResearchUuid];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (SInt32) serializedSize {
  __block SInt32 size_ = memoizedSerializedSize;
  if (size_ != -1) {
    return size_;
  }

  size_ = 0;
  if (self.hasSender) {
    size_ += computeMessageSize(1, self.sender);
  }
  if (self.hasStatus) {
    size_ += computeEnumSize(2, self.status);
  }
  if (self.hasUserResearchUuid) {
    size_ += computeStringSize(3, self.userResearchUuid);
  }
  size_ += self.unknownFields.serializedSize;
  memoizedSerializedSize = size_;
  return size_;
}
+ (PerformResearchResponseProto*) parseFromData:(NSData*) data {
  return (PerformResearchResponseProto*)[[[PerformResearchResponseProto builder] mergeFromData:data] build];
}
+ (PerformResearchResponseProto*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (PerformResearchResponseProto*)[[[PerformResearchResponseProto builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (PerformResearchResponseProto*) parseFromInputStream:(NSInputStream*) input {
  return (PerformResearchResponseProto*)[[[PerformResearchResponseProto builder] mergeFromInputStream:input] build];
}
+ (PerformResearchResponseProto*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (PerformResearchResponseProto*)[[[PerformResearchResponseProto builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (PerformResearchResponseProto*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (PerformResearchResponseProto*)[[[PerformResearchResponseProto builder] mergeFromCodedInputStream:input] build];
}
+ (PerformResearchResponseProto*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (PerformResearchResponseProto*)[[[PerformResearchResponseProto builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (PerformResearchResponseProto_Builder*) builder {
  return [[PerformResearchResponseProto_Builder alloc] init];
}
+ (PerformResearchResponseProto_Builder*) builderWithPrototype:(PerformResearchResponseProto*) prototype {
  return [[PerformResearchResponseProto builder] mergeFrom:prototype];
}
- (PerformResearchResponseProto_Builder*) builder {
  return [PerformResearchResponseProto builder];
}
- (PerformResearchResponseProto_Builder*) toBuilder {
  return [PerformResearchResponseProto builderWithPrototype:self];
}
- (void) writeDescriptionTo:(NSMutableString*) output withIndent:(NSString*) indent {
  if (self.hasSender) {
    [output appendFormat:@"%@%@ {\n", indent, @"sender"];
    [self.sender writeDescriptionTo:output
                         withIndent:[NSString stringWithFormat:@"%@  ", indent]];
    [output appendFormat:@"%@}\n", indent];
  }
  if (self.hasStatus) {
    [output appendFormat:@"%@%@: %@\n", indent, @"status", [NSNumber numberWithInteger:self.status]];
  }
  if (self.hasUserResearchUuid) {
    [output appendFormat:@"%@%@: %@\n", indent, @"userResearchUuid", self.userResearchUuid];
  }
  [self.unknownFields writeDescriptionTo:output withIndent:indent];
}
- (BOOL) isEqual:(id)other {
  if (other == self) {
    return YES;
  }
  if (![other isKindOfClass:[PerformResearchResponseProto class]]) {
    return NO;
  }
  PerformResearchResponseProto *otherMessage = other;
  return
      self.hasSender == otherMessage.hasSender &&
      (!self.hasSender || [self.sender isEqual:otherMessage.sender]) &&
      self.hasStatus == otherMessage.hasStatus &&
      (!self.hasStatus || self.status == otherMessage.status) &&
      self.hasUserResearchUuid == otherMessage.hasUserResearchUuid &&
      (!self.hasUserResearchUuid || [self.userResearchUuid isEqual:otherMessage.userResearchUuid]) &&
      (self.unknownFields == otherMessage.unknownFields || (self.unknownFields != nil && [self.unknownFields isEqual:otherMessage.unknownFields]));
}
- (NSUInteger) hash {
  __block NSUInteger hashCode = 7;
  if (self.hasSender) {
    hashCode = hashCode * 31 + [self.sender hash];
  }
  if (self.hasStatus) {
    hashCode = hashCode * 31 + self.status;
  }
  if (self.hasUserResearchUuid) {
    hashCode = hashCode * 31 + [self.userResearchUuid hash];
  }
  hashCode = hashCode * 31 + [self.unknownFields hash];
  return hashCode;
}
@end

BOOL PerformResearchResponseProto_PerformResearchStatusIsValidValue(PerformResearchResponseProto_PerformResearchStatus value) {
  switch (value) {
    case PerformResearchResponseProto_PerformResearchStatusSuccess:
    case PerformResearchResponseProto_PerformResearchStatusFailOther:
    case PerformResearchResponseProto_PerformResearchStatusFailInsufficientCash:
    case PerformResearchResponseProto_PerformResearchStatusFailInsufficientGems:
    case PerformResearchResponseProto_PerformResearchStatusFailInsufficientOil:
      return YES;
    default:
      return NO;
  }
}
@interface PerformResearchResponseProto_Builder()
@property (strong) PerformResearchResponseProto* result;
@end

@implementation PerformResearchResponseProto_Builder
@synthesize result;
- (id) init {
  if ((self = [super init])) {
    self.result = [[PerformResearchResponseProto alloc] init];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return result;
}
- (PerformResearchResponseProto_Builder*) clear {
  self.result = [[PerformResearchResponseProto alloc] init];
  return self;
}
- (PerformResearchResponseProto_Builder*) clone {
  return [PerformResearchResponseProto builderWithPrototype:result];
}
- (PerformResearchResponseProto*) defaultInstance {
  return [PerformResearchResponseProto defaultInstance];
}
- (PerformResearchResponseProto*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (PerformResearchResponseProto*) buildPartial {
  PerformResearchResponseProto* returnMe = result;
  self.result = nil;
  return returnMe;
}
- (PerformResearchResponseProto_Builder*) mergeFrom:(PerformResearchResponseProto*) other {
  if (other == [PerformResearchResponseProto defaultInstance]) {
    return self;
  }
  if (other.hasSender) {
    [self mergeSender:other.sender];
  }
  if (other.hasStatus) {
    [self setStatus:other.status];
  }
  if (other.hasUserResearchUuid) {
    [self setUserResearchUuid:other.userResearchUuid];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (PerformResearchResponseProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (PerformResearchResponseProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSetBuilder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    SInt32 tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 10: {
        MinimumUserProto_Builder* subBuilder = [MinimumUserProto builder];
        if (self.hasSender) {
          [subBuilder mergeFrom:self.sender];
        }
        [input readMessage:subBuilder extensionRegistry:extensionRegistry];
        [self setSender:[subBuilder buildPartial]];
        break;
      }
      case 16: {
        PerformResearchResponseProto_PerformResearchStatus value = (PerformResearchResponseProto_PerformResearchStatus)[input readEnum];
        if (PerformResearchResponseProto_PerformResearchStatusIsValidValue(value)) {
          [self setStatus:value];
        } else {
          [unknownFields mergeVarintField:2 value:value];
        }
        break;
      }
      case 26: {
        [self setUserResearchUuid:[input readString]];
        break;
      }
    }
  }
}
- (BOOL) hasSender {
  return result.hasSender;
}
- (MinimumUserProto*) sender {
  return result.sender;
}
- (PerformResearchResponseProto_Builder*) setSender:(MinimumUserProto*) value {
  result.hasSender = YES;
  result.sender = value;
  return self;
}
- (PerformResearchResponseProto_Builder*) setSender_Builder:(MinimumUserProto_Builder*) builderForValue {
  return [self setSender:[builderForValue build]];
}
- (PerformResearchResponseProto_Builder*) mergeSender:(MinimumUserProto*) value {
  if (result.hasSender &&
      result.sender != [MinimumUserProto defaultInstance]) {
    result.sender =
      [[[MinimumUserProto builderWithPrototype:result.sender] mergeFrom:value] buildPartial];
  } else {
    result.sender = value;
  }
  result.hasSender = YES;
  return self;
}
- (PerformResearchResponseProto_Builder*) clearSender {
  result.hasSender = NO;
  result.sender = [MinimumUserProto defaultInstance];
  return self;
}
- (BOOL) hasStatus {
  return result.hasStatus;
}
- (PerformResearchResponseProto_PerformResearchStatus) status {
  return result.status;
}
- (PerformResearchResponseProto_Builder*) setStatus:(PerformResearchResponseProto_PerformResearchStatus) value {
  result.hasStatus = YES;
  result.status = value;
  return self;
}
- (PerformResearchResponseProto_Builder*) clearStatusList {
  result.hasStatus = NO;
  result.status = PerformResearchResponseProto_PerformResearchStatusSuccess;
  return self;
}
- (BOOL) hasUserResearchUuid {
  return result.hasUserResearchUuid;
}
- (NSString*) userResearchUuid {
  return result.userResearchUuid;
}
- (PerformResearchResponseProto_Builder*) setUserResearchUuid:(NSString*) value {
  result.hasUserResearchUuid = YES;
  result.userResearchUuid = value;
  return self;
}
- (PerformResearchResponseProto_Builder*) clearUserResearchUuid {
  result.hasUserResearchUuid = NO;
  result.userResearchUuid = @"";
  return self;
}
@end

@interface FinishPerformingResearchRequestProto ()
@property (strong) MinimumUserProto* sender;
@property (strong) NSString* userResearchUuid;
@property int32_t gemsCost;
@end

@implementation FinishPerformingResearchRequestProto

- (BOOL) hasSender {
  return !!hasSender_;
}
- (void) setHasSender:(BOOL) value_ {
  hasSender_ = !!value_;
}
@synthesize sender;
- (BOOL) hasUserResearchUuid {
  return !!hasUserResearchUuid_;
}
- (void) setHasUserResearchUuid:(BOOL) value_ {
  hasUserResearchUuid_ = !!value_;
}
@synthesize userResearchUuid;
- (BOOL) hasGemsCost {
  return !!hasGemsCost_;
}
- (void) setHasGemsCost:(BOOL) value_ {
  hasGemsCost_ = !!value_;
}
@synthesize gemsCost;
- (id) init {
  if ((self = [super init])) {
    self.sender = [MinimumUserProto defaultInstance];
    self.userResearchUuid = @"";
    self.gemsCost = 0;
  }
  return self;
}
static FinishPerformingResearchRequestProto* defaultFinishPerformingResearchRequestProtoInstance = nil;
+ (void) initialize {
  if (self == [FinishPerformingResearchRequestProto class]) {
    defaultFinishPerformingResearchRequestProtoInstance = [[FinishPerformingResearchRequestProto alloc] init];
  }
}
+ (FinishPerformingResearchRequestProto*) defaultInstance {
  return defaultFinishPerformingResearchRequestProtoInstance;
}
- (FinishPerformingResearchRequestProto*) defaultInstance {
  return defaultFinishPerformingResearchRequestProtoInstance;
}
- (BOOL) isInitialized {
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasSender) {
    [output writeMessage:1 value:self.sender];
  }
  if (self.hasUserResearchUuid) {
    [output writeString:2 value:self.userResearchUuid];
  }
  if (self.hasGemsCost) {
    [output writeInt32:3 value:self.gemsCost];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (SInt32) serializedSize {
  __block SInt32 size_ = memoizedSerializedSize;
  if (size_ != -1) {
    return size_;
  }

  size_ = 0;
  if (self.hasSender) {
    size_ += computeMessageSize(1, self.sender);
  }
  if (self.hasUserResearchUuid) {
    size_ += computeStringSize(2, self.userResearchUuid);
  }
  if (self.hasGemsCost) {
    size_ += computeInt32Size(3, self.gemsCost);
  }
  size_ += self.unknownFields.serializedSize;
  memoizedSerializedSize = size_;
  return size_;
}
+ (FinishPerformingResearchRequestProto*) parseFromData:(NSData*) data {
  return (FinishPerformingResearchRequestProto*)[[[FinishPerformingResearchRequestProto builder] mergeFromData:data] build];
}
+ (FinishPerformingResearchRequestProto*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (FinishPerformingResearchRequestProto*)[[[FinishPerformingResearchRequestProto builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (FinishPerformingResearchRequestProto*) parseFromInputStream:(NSInputStream*) input {
  return (FinishPerformingResearchRequestProto*)[[[FinishPerformingResearchRequestProto builder] mergeFromInputStream:input] build];
}
+ (FinishPerformingResearchRequestProto*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (FinishPerformingResearchRequestProto*)[[[FinishPerformingResearchRequestProto builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (FinishPerformingResearchRequestProto*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (FinishPerformingResearchRequestProto*)[[[FinishPerformingResearchRequestProto builder] mergeFromCodedInputStream:input] build];
}
+ (FinishPerformingResearchRequestProto*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (FinishPerformingResearchRequestProto*)[[[FinishPerformingResearchRequestProto builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (FinishPerformingResearchRequestProto_Builder*) builder {
  return [[FinishPerformingResearchRequestProto_Builder alloc] init];
}
+ (FinishPerformingResearchRequestProto_Builder*) builderWithPrototype:(FinishPerformingResearchRequestProto*) prototype {
  return [[FinishPerformingResearchRequestProto builder] mergeFrom:prototype];
}
- (FinishPerformingResearchRequestProto_Builder*) builder {
  return [FinishPerformingResearchRequestProto builder];
}
- (FinishPerformingResearchRequestProto_Builder*) toBuilder {
  return [FinishPerformingResearchRequestProto builderWithPrototype:self];
}
- (void) writeDescriptionTo:(NSMutableString*) output withIndent:(NSString*) indent {
  if (self.hasSender) {
    [output appendFormat:@"%@%@ {\n", indent, @"sender"];
    [self.sender writeDescriptionTo:output
                         withIndent:[NSString stringWithFormat:@"%@  ", indent]];
    [output appendFormat:@"%@}\n", indent];
  }
  if (self.hasUserResearchUuid) {
    [output appendFormat:@"%@%@: %@\n", indent, @"userResearchUuid", self.userResearchUuid];
  }
  if (self.hasGemsCost) {
    [output appendFormat:@"%@%@: %@\n", indent, @"gemsCost", [NSNumber numberWithInteger:self.gemsCost]];
  }
  [self.unknownFields writeDescriptionTo:output withIndent:indent];
}
- (BOOL) isEqual:(id)other {
  if (other == self) {
    return YES;
  }
  if (![other isKindOfClass:[FinishPerformingResearchRequestProto class]]) {
    return NO;
  }
  FinishPerformingResearchRequestProto *otherMessage = other;
  return
      self.hasSender == otherMessage.hasSender &&
      (!self.hasSender || [self.sender isEqual:otherMessage.sender]) &&
      self.hasUserResearchUuid == otherMessage.hasUserResearchUuid &&
      (!self.hasUserResearchUuid || [self.userResearchUuid isEqual:otherMessage.userResearchUuid]) &&
      self.hasGemsCost == otherMessage.hasGemsCost &&
      (!self.hasGemsCost || self.gemsCost == otherMessage.gemsCost) &&
      (self.unknownFields == otherMessage.unknownFields || (self.unknownFields != nil && [self.unknownFields isEqual:otherMessage.unknownFields]));
}
- (NSUInteger) hash {
  __block NSUInteger hashCode = 7;
  if (self.hasSender) {
    hashCode = hashCode * 31 + [self.sender hash];
  }
  if (self.hasUserResearchUuid) {
    hashCode = hashCode * 31 + [self.userResearchUuid hash];
  }
  if (self.hasGemsCost) {
    hashCode = hashCode * 31 + [[NSNumber numberWithInteger:self.gemsCost] hash];
  }
  hashCode = hashCode * 31 + [self.unknownFields hash];
  return hashCode;
}
@end

@interface FinishPerformingResearchRequestProto_Builder()
@property (strong) FinishPerformingResearchRequestProto* result;
@end

@implementation FinishPerformingResearchRequestProto_Builder
@synthesize result;
- (id) init {
  if ((self = [super init])) {
    self.result = [[FinishPerformingResearchRequestProto alloc] init];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return result;
}
- (FinishPerformingResearchRequestProto_Builder*) clear {
  self.result = [[FinishPerformingResearchRequestProto alloc] init];
  return self;
}
- (FinishPerformingResearchRequestProto_Builder*) clone {
  return [FinishPerformingResearchRequestProto builderWithPrototype:result];
}
- (FinishPerformingResearchRequestProto*) defaultInstance {
  return [FinishPerformingResearchRequestProto defaultInstance];
}
- (FinishPerformingResearchRequestProto*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (FinishPerformingResearchRequestProto*) buildPartial {
  FinishPerformingResearchRequestProto* returnMe = result;
  self.result = nil;
  return returnMe;
}
- (FinishPerformingResearchRequestProto_Builder*) mergeFrom:(FinishPerformingResearchRequestProto*) other {
  if (other == [FinishPerformingResearchRequestProto defaultInstance]) {
    return self;
  }
  if (other.hasSender) {
    [self mergeSender:other.sender];
  }
  if (other.hasUserResearchUuid) {
    [self setUserResearchUuid:other.userResearchUuid];
  }
  if (other.hasGemsCost) {
    [self setGemsCost:other.gemsCost];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (FinishPerformingResearchRequestProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (FinishPerformingResearchRequestProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSetBuilder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    SInt32 tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 10: {
        MinimumUserProto_Builder* subBuilder = [MinimumUserProto builder];
        if (self.hasSender) {
          [subBuilder mergeFrom:self.sender];
        }
        [input readMessage:subBuilder extensionRegistry:extensionRegistry];
        [self setSender:[subBuilder buildPartial]];
        break;
      }
      case 18: {
        [self setUserResearchUuid:[input readString]];
        break;
      }
      case 24: {
        [self setGemsCost:[input readInt32]];
        break;
      }
    }
  }
}
- (BOOL) hasSender {
  return result.hasSender;
}
- (MinimumUserProto*) sender {
  return result.sender;
}
- (FinishPerformingResearchRequestProto_Builder*) setSender:(MinimumUserProto*) value {
  result.hasSender = YES;
  result.sender = value;
  return self;
}
- (FinishPerformingResearchRequestProto_Builder*) setSender_Builder:(MinimumUserProto_Builder*) builderForValue {
  return [self setSender:[builderForValue build]];
}
- (FinishPerformingResearchRequestProto_Builder*) mergeSender:(MinimumUserProto*) value {
  if (result.hasSender &&
      result.sender != [MinimumUserProto defaultInstance]) {
    result.sender =
      [[[MinimumUserProto builderWithPrototype:result.sender] mergeFrom:value] buildPartial];
  } else {
    result.sender = value;
  }
  result.hasSender = YES;
  return self;
}
- (FinishPerformingResearchRequestProto_Builder*) clearSender {
  result.hasSender = NO;
  result.sender = [MinimumUserProto defaultInstance];
  return self;
}
- (BOOL) hasUserResearchUuid {
  return result.hasUserResearchUuid;
}
- (NSString*) userResearchUuid {
  return result.userResearchUuid;
}
- (FinishPerformingResearchRequestProto_Builder*) setUserResearchUuid:(NSString*) value {
  result.hasUserResearchUuid = YES;
  result.userResearchUuid = value;
  return self;
}
- (FinishPerformingResearchRequestProto_Builder*) clearUserResearchUuid {
  result.hasUserResearchUuid = NO;
  result.userResearchUuid = @"";
  return self;
}
- (BOOL) hasGemsCost {
  return result.hasGemsCost;
}
- (int32_t) gemsCost {
  return result.gemsCost;
}
- (FinishPerformingResearchRequestProto_Builder*) setGemsCost:(int32_t) value {
  result.hasGemsCost = YES;
  result.gemsCost = value;
  return self;
}
- (FinishPerformingResearchRequestProto_Builder*) clearGemsCost {
  result.hasGemsCost = NO;
  result.gemsCost = 0;
  return self;
}
@end

@interface FinishPerformingResearchResponseProto ()
@property (strong) MinimumUserProto* sender;
@property FinishPerformingResearchResponseProto_FinishPerformingResearchStatus status;
@end

@implementation FinishPerformingResearchResponseProto

- (BOOL) hasSender {
  return !!hasSender_;
}
- (void) setHasSender:(BOOL) value_ {
  hasSender_ = !!value_;
}
@synthesize sender;
- (BOOL) hasStatus {
  return !!hasStatus_;
}
- (void) setHasStatus:(BOOL) value_ {
  hasStatus_ = !!value_;
}
@synthesize status;
- (id) init {
  if ((self = [super init])) {
    self.sender = [MinimumUserProto defaultInstance];
    self.status = FinishPerformingResearchResponseProto_FinishPerformingResearchStatusSuccess;
  }
  return self;
}
static FinishPerformingResearchResponseProto* defaultFinishPerformingResearchResponseProtoInstance = nil;
+ (void) initialize {
  if (self == [FinishPerformingResearchResponseProto class]) {
    defaultFinishPerformingResearchResponseProtoInstance = [[FinishPerformingResearchResponseProto alloc] init];
  }
}
+ (FinishPerformingResearchResponseProto*) defaultInstance {
  return defaultFinishPerformingResearchResponseProtoInstance;
}
- (FinishPerformingResearchResponseProto*) defaultInstance {
  return defaultFinishPerformingResearchResponseProtoInstance;
}
- (BOOL) isInitialized {
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasSender) {
    [output writeMessage:1 value:self.sender];
  }
  if (self.hasStatus) {
    [output writeEnum:2 value:self.status];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (SInt32) serializedSize {
  __block SInt32 size_ = memoizedSerializedSize;
  if (size_ != -1) {
    return size_;
  }

  size_ = 0;
  if (self.hasSender) {
    size_ += computeMessageSize(1, self.sender);
  }
  if (self.hasStatus) {
    size_ += computeEnumSize(2, self.status);
  }
  size_ += self.unknownFields.serializedSize;
  memoizedSerializedSize = size_;
  return size_;
}
+ (FinishPerformingResearchResponseProto*) parseFromData:(NSData*) data {
  return (FinishPerformingResearchResponseProto*)[[[FinishPerformingResearchResponseProto builder] mergeFromData:data] build];
}
+ (FinishPerformingResearchResponseProto*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (FinishPerformingResearchResponseProto*)[[[FinishPerformingResearchResponseProto builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (FinishPerformingResearchResponseProto*) parseFromInputStream:(NSInputStream*) input {
  return (FinishPerformingResearchResponseProto*)[[[FinishPerformingResearchResponseProto builder] mergeFromInputStream:input] build];
}
+ (FinishPerformingResearchResponseProto*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (FinishPerformingResearchResponseProto*)[[[FinishPerformingResearchResponseProto builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (FinishPerformingResearchResponseProto*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (FinishPerformingResearchResponseProto*)[[[FinishPerformingResearchResponseProto builder] mergeFromCodedInputStream:input] build];
}
+ (FinishPerformingResearchResponseProto*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (FinishPerformingResearchResponseProto*)[[[FinishPerformingResearchResponseProto builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (FinishPerformingResearchResponseProto_Builder*) builder {
  return [[FinishPerformingResearchResponseProto_Builder alloc] init];
}
+ (FinishPerformingResearchResponseProto_Builder*) builderWithPrototype:(FinishPerformingResearchResponseProto*) prototype {
  return [[FinishPerformingResearchResponseProto builder] mergeFrom:prototype];
}
- (FinishPerformingResearchResponseProto_Builder*) builder {
  return [FinishPerformingResearchResponseProto builder];
}
- (FinishPerformingResearchResponseProto_Builder*) toBuilder {
  return [FinishPerformingResearchResponseProto builderWithPrototype:self];
}
- (void) writeDescriptionTo:(NSMutableString*) output withIndent:(NSString*) indent {
  if (self.hasSender) {
    [output appendFormat:@"%@%@ {\n", indent, @"sender"];
    [self.sender writeDescriptionTo:output
                         withIndent:[NSString stringWithFormat:@"%@  ", indent]];
    [output appendFormat:@"%@}\n", indent];
  }
  if (self.hasStatus) {
    [output appendFormat:@"%@%@: %@\n", indent, @"status", [NSNumber numberWithInteger:self.status]];
  }
  [self.unknownFields writeDescriptionTo:output withIndent:indent];
}
- (BOOL) isEqual:(id)other {
  if (other == self) {
    return YES;
  }
  if (![other isKindOfClass:[FinishPerformingResearchResponseProto class]]) {
    return NO;
  }
  FinishPerformingResearchResponseProto *otherMessage = other;
  return
      self.hasSender == otherMessage.hasSender &&
      (!self.hasSender || [self.sender isEqual:otherMessage.sender]) &&
      self.hasStatus == otherMessage.hasStatus &&
      (!self.hasStatus || self.status == otherMessage.status) &&
      (self.unknownFields == otherMessage.unknownFields || (self.unknownFields != nil && [self.unknownFields isEqual:otherMessage.unknownFields]));
}
- (NSUInteger) hash {
  __block NSUInteger hashCode = 7;
  if (self.hasSender) {
    hashCode = hashCode * 31 + [self.sender hash];
  }
  if (self.hasStatus) {
    hashCode = hashCode * 31 + self.status;
  }
  hashCode = hashCode * 31 + [self.unknownFields hash];
  return hashCode;
}
@end

BOOL FinishPerformingResearchResponseProto_FinishPerformingResearchStatusIsValidValue(FinishPerformingResearchResponseProto_FinishPerformingResearchStatus value) {
  switch (value) {
    case FinishPerformingResearchResponseProto_FinishPerformingResearchStatusSuccess:
    case FinishPerformingResearchResponseProto_FinishPerformingResearchStatusFailOther:
    case FinishPerformingResearchResponseProto_FinishPerformingResearchStatusFailNotEnoughGems:
      return YES;
    default:
      return NO;
  }
}
@interface FinishPerformingResearchResponseProto_Builder()
@property (strong) FinishPerformingResearchResponseProto* result;
@end

@implementation FinishPerformingResearchResponseProto_Builder
@synthesize result;
- (id) init {
  if ((self = [super init])) {
    self.result = [[FinishPerformingResearchResponseProto alloc] init];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return result;
}
- (FinishPerformingResearchResponseProto_Builder*) clear {
  self.result = [[FinishPerformingResearchResponseProto alloc] init];
  return self;
}
- (FinishPerformingResearchResponseProto_Builder*) clone {
  return [FinishPerformingResearchResponseProto builderWithPrototype:result];
}
- (FinishPerformingResearchResponseProto*) defaultInstance {
  return [FinishPerformingResearchResponseProto defaultInstance];
}
- (FinishPerformingResearchResponseProto*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (FinishPerformingResearchResponseProto*) buildPartial {
  FinishPerformingResearchResponseProto* returnMe = result;
  self.result = nil;
  return returnMe;
}
- (FinishPerformingResearchResponseProto_Builder*) mergeFrom:(FinishPerformingResearchResponseProto*) other {
  if (other == [FinishPerformingResearchResponseProto defaultInstance]) {
    return self;
  }
  if (other.hasSender) {
    [self mergeSender:other.sender];
  }
  if (other.hasStatus) {
    [self setStatus:other.status];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (FinishPerformingResearchResponseProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (FinishPerformingResearchResponseProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSetBuilder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    SInt32 tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 10: {
        MinimumUserProto_Builder* subBuilder = [MinimumUserProto builder];
        if (self.hasSender) {
          [subBuilder mergeFrom:self.sender];
        }
        [input readMessage:subBuilder extensionRegistry:extensionRegistry];
        [self setSender:[subBuilder buildPartial]];
        break;
      }
      case 16: {
        FinishPerformingResearchResponseProto_FinishPerformingResearchStatus value = (FinishPerformingResearchResponseProto_FinishPerformingResearchStatus)[input readEnum];
        if (FinishPerformingResearchResponseProto_FinishPerformingResearchStatusIsValidValue(value)) {
          [self setStatus:value];
        } else {
          [unknownFields mergeVarintField:2 value:value];
        }
        break;
      }
    }
  }
}
- (BOOL) hasSender {
  return result.hasSender;
}
- (MinimumUserProto*) sender {
  return result.sender;
}
- (FinishPerformingResearchResponseProto_Builder*) setSender:(MinimumUserProto*) value {
  result.hasSender = YES;
  result.sender = value;
  return self;
}
- (FinishPerformingResearchResponseProto_Builder*) setSender_Builder:(MinimumUserProto_Builder*) builderForValue {
  return [self setSender:[builderForValue build]];
}
- (FinishPerformingResearchResponseProto_Builder*) mergeSender:(MinimumUserProto*) value {
  if (result.hasSender &&
      result.sender != [MinimumUserProto defaultInstance]) {
    result.sender =
      [[[MinimumUserProto builderWithPrototype:result.sender] mergeFrom:value] buildPartial];
  } else {
    result.sender = value;
  }
  result.hasSender = YES;
  return self;
}
- (FinishPerformingResearchResponseProto_Builder*) clearSender {
  result.hasSender = NO;
  result.sender = [MinimumUserProto defaultInstance];
  return self;
}
- (BOOL) hasStatus {
  return result.hasStatus;
}
- (FinishPerformingResearchResponseProto_FinishPerformingResearchStatus) status {
  return result.status;
}
- (FinishPerformingResearchResponseProto_Builder*) setStatus:(FinishPerformingResearchResponseProto_FinishPerformingResearchStatus) value {
  result.hasStatus = YES;
  result.status = value;
  return self;
}
- (FinishPerformingResearchResponseProto_Builder*) clearStatusList {
  result.hasStatus = NO;
  result.status = FinishPerformingResearchResponseProto_FinishPerformingResearchStatusSuccess;
  return self;
}
@end


// @@protoc_insertion_point(global_scope)
