// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "EventBoosterPack.pb.h"
// @@protoc_insertion_point(imports)

@implementation EventBoosterPackRoot
static PBExtensionRegistry* extensionRegistry = nil;
+ (PBExtensionRegistry*) extensionRegistry {
  return extensionRegistry;
}

+ (void) initialize {
  if (self == [EventBoosterPackRoot class]) {
    PBMutableExtensionRegistry* registry = [PBMutableExtensionRegistry registry];
    [self registerAllExtensions:registry];
    [BoosterPackStuffRoot registerAllExtensions:registry];
    [RewardRoot registerAllExtensions:registry];
    [SharedEnumConfigRoot registerAllExtensions:registry];
    [UserRoot registerAllExtensions:registry];
    extensionRegistry = registry;
  }
}
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry {
}
@end

@interface PurchaseBoosterPackRequestProto ()
@property (strong) MinimumUserProto* sender;
@property int32_t boosterPackId;
@property int64_t clientTime;
@property BOOL dailyFreeBoosterPack;
@property BOOL buyingInBulk;
@property int32_t gemsSpent;
@property int32_t gachaCreditsChange;
@end

@implementation PurchaseBoosterPackRequestProto

- (BOOL) hasSender {
  return !!hasSender_;
}
- (void) setHasSender:(BOOL) value_ {
  hasSender_ = !!value_;
}
@synthesize sender;
- (BOOL) hasBoosterPackId {
  return !!hasBoosterPackId_;
}
- (void) setHasBoosterPackId:(BOOL) value_ {
  hasBoosterPackId_ = !!value_;
}
@synthesize boosterPackId;
- (BOOL) hasClientTime {
  return !!hasClientTime_;
}
- (void) setHasClientTime:(BOOL) value_ {
  hasClientTime_ = !!value_;
}
@synthesize clientTime;
- (BOOL) hasDailyFreeBoosterPack {
  return !!hasDailyFreeBoosterPack_;
}
- (void) setHasDailyFreeBoosterPack:(BOOL) value_ {
  hasDailyFreeBoosterPack_ = !!value_;
}
- (BOOL) dailyFreeBoosterPack {
  return !!dailyFreeBoosterPack_;
}
- (void) setDailyFreeBoosterPack:(BOOL) value_ {
  dailyFreeBoosterPack_ = !!value_;
}
- (BOOL) hasBuyingInBulk {
  return !!hasBuyingInBulk_;
}
- (void) setHasBuyingInBulk:(BOOL) value_ {
  hasBuyingInBulk_ = !!value_;
}
- (BOOL) buyingInBulk {
  return !!buyingInBulk_;
}
- (void) setBuyingInBulk:(BOOL) value_ {
  buyingInBulk_ = !!value_;
}
- (BOOL) hasGemsSpent {
  return !!hasGemsSpent_;
}
- (void) setHasGemsSpent:(BOOL) value_ {
  hasGemsSpent_ = !!value_;
}
@synthesize gemsSpent;
- (BOOL) hasGachaCreditsChange {
  return !!hasGachaCreditsChange_;
}
- (void) setHasGachaCreditsChange:(BOOL) value_ {
  hasGachaCreditsChange_ = !!value_;
}
@synthesize gachaCreditsChange;
- (id) init {
  if ((self = [super init])) {
    self.sender = [MinimumUserProto defaultInstance];
    self.boosterPackId = 0;
    self.clientTime = 0L;
    self.dailyFreeBoosterPack = NO;
    self.buyingInBulk = NO;
    self.gemsSpent = 0;
    self.gachaCreditsChange = 0;
  }
  return self;
}
static PurchaseBoosterPackRequestProto* defaultPurchaseBoosterPackRequestProtoInstance = nil;
+ (void) initialize {
  if (self == [PurchaseBoosterPackRequestProto class]) {
    defaultPurchaseBoosterPackRequestProtoInstance = [[PurchaseBoosterPackRequestProto alloc] init];
  }
}
+ (PurchaseBoosterPackRequestProto*) defaultInstance {
  return defaultPurchaseBoosterPackRequestProtoInstance;
}
- (PurchaseBoosterPackRequestProto*) defaultInstance {
  return defaultPurchaseBoosterPackRequestProtoInstance;
}
- (BOOL) isInitialized {
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasSender) {
    [output writeMessage:1 value:self.sender];
  }
  if (self.hasBoosterPackId) {
    [output writeInt32:2 value:self.boosterPackId];
  }
  if (self.hasClientTime) {
    [output writeInt64:3 value:self.clientTime];
  }
  if (self.hasDailyFreeBoosterPack) {
    [output writeBool:4 value:self.dailyFreeBoosterPack];
  }
  if (self.hasBuyingInBulk) {
    [output writeBool:5 value:self.buyingInBulk];
  }
  if (self.hasGemsSpent) {
    [output writeInt32:6 value:self.gemsSpent];
  }
  if (self.hasGachaCreditsChange) {
    [output writeInt32:7 value:self.gachaCreditsChange];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (SInt32) serializedSize {
  __block SInt32 size_ = memoizedSerializedSize;
  if (size_ != -1) {
    return size_;
  }

  size_ = 0;
  if (self.hasSender) {
    size_ += computeMessageSize(1, self.sender);
  }
  if (self.hasBoosterPackId) {
    size_ += computeInt32Size(2, self.boosterPackId);
  }
  if (self.hasClientTime) {
    size_ += computeInt64Size(3, self.clientTime);
  }
  if (self.hasDailyFreeBoosterPack) {
    size_ += computeBoolSize(4, self.dailyFreeBoosterPack);
  }
  if (self.hasBuyingInBulk) {
    size_ += computeBoolSize(5, self.buyingInBulk);
  }
  if (self.hasGemsSpent) {
    size_ += computeInt32Size(6, self.gemsSpent);
  }
  if (self.hasGachaCreditsChange) {
    size_ += computeInt32Size(7, self.gachaCreditsChange);
  }
  size_ += self.unknownFields.serializedSize;
  memoizedSerializedSize = size_;
  return size_;
}
+ (PurchaseBoosterPackRequestProto*) parseFromData:(NSData*) data {
  return (PurchaseBoosterPackRequestProto*)[[[PurchaseBoosterPackRequestProto builder] mergeFromData:data] build];
}
+ (PurchaseBoosterPackRequestProto*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (PurchaseBoosterPackRequestProto*)[[[PurchaseBoosterPackRequestProto builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (PurchaseBoosterPackRequestProto*) parseFromInputStream:(NSInputStream*) input {
  return (PurchaseBoosterPackRequestProto*)[[[PurchaseBoosterPackRequestProto builder] mergeFromInputStream:input] build];
}
+ (PurchaseBoosterPackRequestProto*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (PurchaseBoosterPackRequestProto*)[[[PurchaseBoosterPackRequestProto builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (PurchaseBoosterPackRequestProto*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (PurchaseBoosterPackRequestProto*)[[[PurchaseBoosterPackRequestProto builder] mergeFromCodedInputStream:input] build];
}
+ (PurchaseBoosterPackRequestProto*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (PurchaseBoosterPackRequestProto*)[[[PurchaseBoosterPackRequestProto builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (PurchaseBoosterPackRequestProto_Builder*) builder {
  return [[PurchaseBoosterPackRequestProto_Builder alloc] init];
}
+ (PurchaseBoosterPackRequestProto_Builder*) builderWithPrototype:(PurchaseBoosterPackRequestProto*) prototype {
  return [[PurchaseBoosterPackRequestProto builder] mergeFrom:prototype];
}
- (PurchaseBoosterPackRequestProto_Builder*) builder {
  return [PurchaseBoosterPackRequestProto builder];
}
- (PurchaseBoosterPackRequestProto_Builder*) toBuilder {
  return [PurchaseBoosterPackRequestProto builderWithPrototype:self];
}
- (void) writeDescriptionTo:(NSMutableString*) output withIndent:(NSString*) indent {
  if (self.hasSender) {
    [output appendFormat:@"%@%@ {\n", indent, @"sender"];
    [self.sender writeDescriptionTo:output
                         withIndent:[NSString stringWithFormat:@"%@  ", indent]];
    [output appendFormat:@"%@}\n", indent];
  }
  if (self.hasBoosterPackId) {
    [output appendFormat:@"%@%@: %@\n", indent, @"boosterPackId", [NSNumber numberWithInteger:self.boosterPackId]];
  }
  if (self.hasClientTime) {
    [output appendFormat:@"%@%@: %@\n", indent, @"clientTime", [NSNumber numberWithLongLong:self.clientTime]];
  }
  if (self.hasDailyFreeBoosterPack) {
    [output appendFormat:@"%@%@: %@\n", indent, @"dailyFreeBoosterPack", [NSNumber numberWithBool:self.dailyFreeBoosterPack]];
  }
  if (self.hasBuyingInBulk) {
    [output appendFormat:@"%@%@: %@\n", indent, @"buyingInBulk", [NSNumber numberWithBool:self.buyingInBulk]];
  }
  if (self.hasGemsSpent) {
    [output appendFormat:@"%@%@: %@\n", indent, @"gemsSpent", [NSNumber numberWithInteger:self.gemsSpent]];
  }
  if (self.hasGachaCreditsChange) {
    [output appendFormat:@"%@%@: %@\n", indent, @"gachaCreditsChange", [NSNumber numberWithInteger:self.gachaCreditsChange]];
  }
  [self.unknownFields writeDescriptionTo:output withIndent:indent];
}
- (BOOL) isEqual:(id)other {
  if (other == self) {
    return YES;
  }
  if (![other isKindOfClass:[PurchaseBoosterPackRequestProto class]]) {
    return NO;
  }
  PurchaseBoosterPackRequestProto *otherMessage = other;
  return
      self.hasSender == otherMessage.hasSender &&
      (!self.hasSender || [self.sender isEqual:otherMessage.sender]) &&
      self.hasBoosterPackId == otherMessage.hasBoosterPackId &&
      (!self.hasBoosterPackId || self.boosterPackId == otherMessage.boosterPackId) &&
      self.hasClientTime == otherMessage.hasClientTime &&
      (!self.hasClientTime || self.clientTime == otherMessage.clientTime) &&
      self.hasDailyFreeBoosterPack == otherMessage.hasDailyFreeBoosterPack &&
      (!self.hasDailyFreeBoosterPack || self.dailyFreeBoosterPack == otherMessage.dailyFreeBoosterPack) &&
      self.hasBuyingInBulk == otherMessage.hasBuyingInBulk &&
      (!self.hasBuyingInBulk || self.buyingInBulk == otherMessage.buyingInBulk) &&
      self.hasGemsSpent == otherMessage.hasGemsSpent &&
      (!self.hasGemsSpent || self.gemsSpent == otherMessage.gemsSpent) &&
      self.hasGachaCreditsChange == otherMessage.hasGachaCreditsChange &&
      (!self.hasGachaCreditsChange || self.gachaCreditsChange == otherMessage.gachaCreditsChange) &&
      (self.unknownFields == otherMessage.unknownFields || (self.unknownFields != nil && [self.unknownFields isEqual:otherMessage.unknownFields]));
}
- (NSUInteger) hash {
  __block NSUInteger hashCode = 7;
  if (self.hasSender) {
    hashCode = hashCode * 31 + [self.sender hash];
  }
  if (self.hasBoosterPackId) {
    hashCode = hashCode * 31 + [[NSNumber numberWithInteger:self.boosterPackId] hash];
  }
  if (self.hasClientTime) {
    hashCode = hashCode * 31 + [[NSNumber numberWithLongLong:self.clientTime] hash];
  }
  if (self.hasDailyFreeBoosterPack) {
    hashCode = hashCode * 31 + [[NSNumber numberWithBool:self.dailyFreeBoosterPack] hash];
  }
  if (self.hasBuyingInBulk) {
    hashCode = hashCode * 31 + [[NSNumber numberWithBool:self.buyingInBulk] hash];
  }
  if (self.hasGemsSpent) {
    hashCode = hashCode * 31 + [[NSNumber numberWithInteger:self.gemsSpent] hash];
  }
  if (self.hasGachaCreditsChange) {
    hashCode = hashCode * 31 + [[NSNumber numberWithInteger:self.gachaCreditsChange] hash];
  }
  hashCode = hashCode * 31 + [self.unknownFields hash];
  return hashCode;
}
@end

@interface PurchaseBoosterPackRequestProto_Builder()
@property (strong) PurchaseBoosterPackRequestProto* result;
@end

@implementation PurchaseBoosterPackRequestProto_Builder
@synthesize result;
- (id) init {
  if ((self = [super init])) {
    self.result = [[PurchaseBoosterPackRequestProto alloc] init];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return result;
}
- (PurchaseBoosterPackRequestProto_Builder*) clear {
  self.result = [[PurchaseBoosterPackRequestProto alloc] init];
  return self;
}
- (PurchaseBoosterPackRequestProto_Builder*) clone {
  return [PurchaseBoosterPackRequestProto builderWithPrototype:result];
}
- (PurchaseBoosterPackRequestProto*) defaultInstance {
  return [PurchaseBoosterPackRequestProto defaultInstance];
}
- (PurchaseBoosterPackRequestProto*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (PurchaseBoosterPackRequestProto*) buildPartial {
  PurchaseBoosterPackRequestProto* returnMe = result;
  self.result = nil;
  return returnMe;
}
- (PurchaseBoosterPackRequestProto_Builder*) mergeFrom:(PurchaseBoosterPackRequestProto*) other {
  if (other == [PurchaseBoosterPackRequestProto defaultInstance]) {
    return self;
  }
  if (other.hasSender) {
    [self mergeSender:other.sender];
  }
  if (other.hasBoosterPackId) {
    [self setBoosterPackId:other.boosterPackId];
  }
  if (other.hasClientTime) {
    [self setClientTime:other.clientTime];
  }
  if (other.hasDailyFreeBoosterPack) {
    [self setDailyFreeBoosterPack:other.dailyFreeBoosterPack];
  }
  if (other.hasBuyingInBulk) {
    [self setBuyingInBulk:other.buyingInBulk];
  }
  if (other.hasGemsSpent) {
    [self setGemsSpent:other.gemsSpent];
  }
  if (other.hasGachaCreditsChange) {
    [self setGachaCreditsChange:other.gachaCreditsChange];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (PurchaseBoosterPackRequestProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (PurchaseBoosterPackRequestProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSetBuilder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    SInt32 tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 10: {
        MinimumUserProto_Builder* subBuilder = [MinimumUserProto builder];
        if (self.hasSender) {
          [subBuilder mergeFrom:self.sender];
        }
        [input readMessage:subBuilder extensionRegistry:extensionRegistry];
        [self setSender:[subBuilder buildPartial]];
        break;
      }
      case 16: {
        [self setBoosterPackId:[input readInt32]];
        break;
      }
      case 24: {
        [self setClientTime:[input readInt64]];
        break;
      }
      case 32: {
        [self setDailyFreeBoosterPack:[input readBool]];
        break;
      }
      case 40: {
        [self setBuyingInBulk:[input readBool]];
        break;
      }
      case 48: {
        [self setGemsSpent:[input readInt32]];
        break;
      }
      case 56: {
        [self setGachaCreditsChange:[input readInt32]];
        break;
      }
    }
  }
}
- (BOOL) hasSender {
  return result.hasSender;
}
- (MinimumUserProto*) sender {
  return result.sender;
}
- (PurchaseBoosterPackRequestProto_Builder*) setSender:(MinimumUserProto*) value {
  result.hasSender = YES;
  result.sender = value;
  return self;
}
- (PurchaseBoosterPackRequestProto_Builder*) setSender_Builder:(MinimumUserProto_Builder*) builderForValue {
  return [self setSender:[builderForValue build]];
}
- (PurchaseBoosterPackRequestProto_Builder*) mergeSender:(MinimumUserProto*) value {
  if (result.hasSender &&
      result.sender != [MinimumUserProto defaultInstance]) {
    result.sender =
      [[[MinimumUserProto builderWithPrototype:result.sender] mergeFrom:value] buildPartial];
  } else {
    result.sender = value;
  }
  result.hasSender = YES;
  return self;
}
- (PurchaseBoosterPackRequestProto_Builder*) clearSender {
  result.hasSender = NO;
  result.sender = [MinimumUserProto defaultInstance];
  return self;
}
- (BOOL) hasBoosterPackId {
  return result.hasBoosterPackId;
}
- (int32_t) boosterPackId {
  return result.boosterPackId;
}
- (PurchaseBoosterPackRequestProto_Builder*) setBoosterPackId:(int32_t) value {
  result.hasBoosterPackId = YES;
  result.boosterPackId = value;
  return self;
}
- (PurchaseBoosterPackRequestProto_Builder*) clearBoosterPackId {
  result.hasBoosterPackId = NO;
  result.boosterPackId = 0;
  return self;
}
- (BOOL) hasClientTime {
  return result.hasClientTime;
}
- (int64_t) clientTime {
  return result.clientTime;
}
- (PurchaseBoosterPackRequestProto_Builder*) setClientTime:(int64_t) value {
  result.hasClientTime = YES;
  result.clientTime = value;
  return self;
}
- (PurchaseBoosterPackRequestProto_Builder*) clearClientTime {
  result.hasClientTime = NO;
  result.clientTime = 0L;
  return self;
}
- (BOOL) hasDailyFreeBoosterPack {
  return result.hasDailyFreeBoosterPack;
}
- (BOOL) dailyFreeBoosterPack {
  return result.dailyFreeBoosterPack;
}
- (PurchaseBoosterPackRequestProto_Builder*) setDailyFreeBoosterPack:(BOOL) value {
  result.hasDailyFreeBoosterPack = YES;
  result.dailyFreeBoosterPack = value;
  return self;
}
- (PurchaseBoosterPackRequestProto_Builder*) clearDailyFreeBoosterPack {
  result.hasDailyFreeBoosterPack = NO;
  result.dailyFreeBoosterPack = NO;
  return self;
}
- (BOOL) hasBuyingInBulk {
  return result.hasBuyingInBulk;
}
- (BOOL) buyingInBulk {
  return result.buyingInBulk;
}
- (PurchaseBoosterPackRequestProto_Builder*) setBuyingInBulk:(BOOL) value {
  result.hasBuyingInBulk = YES;
  result.buyingInBulk = value;
  return self;
}
- (PurchaseBoosterPackRequestProto_Builder*) clearBuyingInBulk {
  result.hasBuyingInBulk = NO;
  result.buyingInBulk = NO;
  return self;
}
- (BOOL) hasGemsSpent {
  return result.hasGemsSpent;
}
- (int32_t) gemsSpent {
  return result.gemsSpent;
}
- (PurchaseBoosterPackRequestProto_Builder*) setGemsSpent:(int32_t) value {
  result.hasGemsSpent = YES;
  result.gemsSpent = value;
  return self;
}
- (PurchaseBoosterPackRequestProto_Builder*) clearGemsSpent {
  result.hasGemsSpent = NO;
  result.gemsSpent = 0;
  return self;
}
- (BOOL) hasGachaCreditsChange {
  return result.hasGachaCreditsChange;
}
- (int32_t) gachaCreditsChange {
  return result.gachaCreditsChange;
}
- (PurchaseBoosterPackRequestProto_Builder*) setGachaCreditsChange:(int32_t) value {
  result.hasGachaCreditsChange = YES;
  result.gachaCreditsChange = value;
  return self;
}
- (PurchaseBoosterPackRequestProto_Builder*) clearGachaCreditsChange {
  result.hasGachaCreditsChange = NO;
  result.gachaCreditsChange = 0;
  return self;
}
@end

@interface PurchaseBoosterPackResponseProto ()
@property (strong) MinimumUserProto* sender;
@property ResponseStatus status;
@property (strong) NSMutableArray * mutablePrizeList;
@property (strong) UserRewardProto* reward;
@end

@implementation PurchaseBoosterPackResponseProto

- (BOOL) hasSender {
  return !!hasSender_;
}
- (void) setHasSender:(BOOL) value_ {
  hasSender_ = !!value_;
}
@synthesize sender;
- (BOOL) hasStatus {
  return !!hasStatus_;
}
- (void) setHasStatus:(BOOL) value_ {
  hasStatus_ = !!value_;
}
@synthesize status;
@synthesize mutablePrizeList;
@dynamic prizeList;
- (BOOL) hasReward {
  return !!hasReward_;
}
- (void) setHasReward:(BOOL) value_ {
  hasReward_ = !!value_;
}
@synthesize reward;
- (id) init {
  if ((self = [super init])) {
    self.sender = [MinimumUserProto defaultInstance];
    self.status = ResponseStatusSuccess;
    self.reward = [UserRewardProto defaultInstance];
  }
  return self;
}
static PurchaseBoosterPackResponseProto* defaultPurchaseBoosterPackResponseProtoInstance = nil;
+ (void) initialize {
  if (self == [PurchaseBoosterPackResponseProto class]) {
    defaultPurchaseBoosterPackResponseProtoInstance = [[PurchaseBoosterPackResponseProto alloc] init];
  }
}
+ (PurchaseBoosterPackResponseProto*) defaultInstance {
  return defaultPurchaseBoosterPackResponseProtoInstance;
}
- (PurchaseBoosterPackResponseProto*) defaultInstance {
  return defaultPurchaseBoosterPackResponseProtoInstance;
}
- (NSArray *)prizeList {
  return mutablePrizeList;
}
- (BoosterItemProto*)prizeAtIndex:(NSUInteger)index {
  return [mutablePrizeList objectAtIndex:index];
}
- (BOOL) isInitialized {
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasSender) {
    [output writeMessage:1 value:self.sender];
  }
  if (self.hasStatus) {
    [output writeEnum:2 value:self.status];
  }
  [self.prizeList enumerateObjectsUsingBlock:^(BoosterItemProto *element, NSUInteger idx, BOOL *stop) {
    [output writeMessage:4 value:element];
  }];
  if (self.hasReward) {
    [output writeMessage:6 value:self.reward];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (SInt32) serializedSize {
  __block SInt32 size_ = memoizedSerializedSize;
  if (size_ != -1) {
    return size_;
  }

  size_ = 0;
  if (self.hasSender) {
    size_ += computeMessageSize(1, self.sender);
  }
  if (self.hasStatus) {
    size_ += computeEnumSize(2, self.status);
  }
  [self.prizeList enumerateObjectsUsingBlock:^(BoosterItemProto *element, NSUInteger idx, BOOL *stop) {
    size_ += computeMessageSize(4, element);
  }];
  if (self.hasReward) {
    size_ += computeMessageSize(6, self.reward);
  }
  size_ += self.unknownFields.serializedSize;
  memoizedSerializedSize = size_;
  return size_;
}
+ (PurchaseBoosterPackResponseProto*) parseFromData:(NSData*) data {
  return (PurchaseBoosterPackResponseProto*)[[[PurchaseBoosterPackResponseProto builder] mergeFromData:data] build];
}
+ (PurchaseBoosterPackResponseProto*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (PurchaseBoosterPackResponseProto*)[[[PurchaseBoosterPackResponseProto builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (PurchaseBoosterPackResponseProto*) parseFromInputStream:(NSInputStream*) input {
  return (PurchaseBoosterPackResponseProto*)[[[PurchaseBoosterPackResponseProto builder] mergeFromInputStream:input] build];
}
+ (PurchaseBoosterPackResponseProto*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (PurchaseBoosterPackResponseProto*)[[[PurchaseBoosterPackResponseProto builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (PurchaseBoosterPackResponseProto*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (PurchaseBoosterPackResponseProto*)[[[PurchaseBoosterPackResponseProto builder] mergeFromCodedInputStream:input] build];
}
+ (PurchaseBoosterPackResponseProto*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (PurchaseBoosterPackResponseProto*)[[[PurchaseBoosterPackResponseProto builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (PurchaseBoosterPackResponseProto_Builder*) builder {
  return [[PurchaseBoosterPackResponseProto_Builder alloc] init];
}
+ (PurchaseBoosterPackResponseProto_Builder*) builderWithPrototype:(PurchaseBoosterPackResponseProto*) prototype {
  return [[PurchaseBoosterPackResponseProto builder] mergeFrom:prototype];
}
- (PurchaseBoosterPackResponseProto_Builder*) builder {
  return [PurchaseBoosterPackResponseProto builder];
}
- (PurchaseBoosterPackResponseProto_Builder*) toBuilder {
  return [PurchaseBoosterPackResponseProto builderWithPrototype:self];
}
- (void) writeDescriptionTo:(NSMutableString*) output withIndent:(NSString*) indent {
  if (self.hasSender) {
    [output appendFormat:@"%@%@ {\n", indent, @"sender"];
    [self.sender writeDescriptionTo:output
                         withIndent:[NSString stringWithFormat:@"%@  ", indent]];
    [output appendFormat:@"%@}\n", indent];
  }
  if (self.hasStatus) {
    [output appendFormat:@"%@%@: %@\n", indent, @"status", [NSNumber numberWithInteger:self.status]];
  }
  [self.prizeList enumerateObjectsUsingBlock:^(BoosterItemProto *element, NSUInteger idx, BOOL *stop) {
    [output appendFormat:@"%@%@ {\n", indent, @"prize"];
    [element writeDescriptionTo:output
                     withIndent:[NSString stringWithFormat:@"%@  ", indent]];
    [output appendFormat:@"%@}\n", indent];
  }];
  if (self.hasReward) {
    [output appendFormat:@"%@%@ {\n", indent, @"reward"];
    [self.reward writeDescriptionTo:output
                         withIndent:[NSString stringWithFormat:@"%@  ", indent]];
    [output appendFormat:@"%@}\n", indent];
  }
  [self.unknownFields writeDescriptionTo:output withIndent:indent];
}
- (BOOL) isEqual:(id)other {
  if (other == self) {
    return YES;
  }
  if (![other isKindOfClass:[PurchaseBoosterPackResponseProto class]]) {
    return NO;
  }
  PurchaseBoosterPackResponseProto *otherMessage = other;
  return
      self.hasSender == otherMessage.hasSender &&
      (!self.hasSender || [self.sender isEqual:otherMessage.sender]) &&
      self.hasStatus == otherMessage.hasStatus &&
      (!self.hasStatus || self.status == otherMessage.status) &&
      [self.prizeList isEqualToArray:otherMessage.prizeList] &&
      self.hasReward == otherMessage.hasReward &&
      (!self.hasReward || [self.reward isEqual:otherMessage.reward]) &&
      (self.unknownFields == otherMessage.unknownFields || (self.unknownFields != nil && [self.unknownFields isEqual:otherMessage.unknownFields]));
}
- (NSUInteger) hash {
  __block NSUInteger hashCode = 7;
  if (self.hasSender) {
    hashCode = hashCode * 31 + [self.sender hash];
  }
  if (self.hasStatus) {
    hashCode = hashCode * 31 + self.status;
  }
  [self.prizeList enumerateObjectsUsingBlock:^(BoosterItemProto *element, NSUInteger idx, BOOL *stop) {
    hashCode = hashCode * 31 + [element hash];
  }];
  if (self.hasReward) {
    hashCode = hashCode * 31 + [self.reward hash];
  }
  hashCode = hashCode * 31 + [self.unknownFields hash];
  return hashCode;
}
@end

@interface PurchaseBoosterPackResponseProto_Builder()
@property (strong) PurchaseBoosterPackResponseProto* result;
@end

@implementation PurchaseBoosterPackResponseProto_Builder
@synthesize result;
- (id) init {
  if ((self = [super init])) {
    self.result = [[PurchaseBoosterPackResponseProto alloc] init];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return result;
}
- (PurchaseBoosterPackResponseProto_Builder*) clear {
  self.result = [[PurchaseBoosterPackResponseProto alloc] init];
  return self;
}
- (PurchaseBoosterPackResponseProto_Builder*) clone {
  return [PurchaseBoosterPackResponseProto builderWithPrototype:result];
}
- (PurchaseBoosterPackResponseProto*) defaultInstance {
  return [PurchaseBoosterPackResponseProto defaultInstance];
}
- (PurchaseBoosterPackResponseProto*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (PurchaseBoosterPackResponseProto*) buildPartial {
  PurchaseBoosterPackResponseProto* returnMe = result;
  self.result = nil;
  return returnMe;
}
- (PurchaseBoosterPackResponseProto_Builder*) mergeFrom:(PurchaseBoosterPackResponseProto*) other {
  if (other == [PurchaseBoosterPackResponseProto defaultInstance]) {
    return self;
  }
  if (other.hasSender) {
    [self mergeSender:other.sender];
  }
  if (other.hasStatus) {
    [self setStatus:other.status];
  }
  if (other.mutablePrizeList.count > 0) {
    if (result.mutablePrizeList == nil) {
      result.mutablePrizeList = [[NSMutableArray alloc] initWithArray:other.mutablePrizeList];
    } else {
      [result.mutablePrizeList addObjectsFromArray:other.mutablePrizeList];
    }
  }
  if (other.hasReward) {
    [self mergeReward:other.reward];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (PurchaseBoosterPackResponseProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (PurchaseBoosterPackResponseProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSetBuilder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    SInt32 tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 10: {
        MinimumUserProto_Builder* subBuilder = [MinimumUserProto builder];
        if (self.hasSender) {
          [subBuilder mergeFrom:self.sender];
        }
        [input readMessage:subBuilder extensionRegistry:extensionRegistry];
        [self setSender:[subBuilder buildPartial]];
        break;
      }
      case 16: {
        ResponseStatus value = (ResponseStatus)[input readEnum];
        if (ResponseStatusIsValidValue(value)) {
          [self setStatus:value];
        } else {
          [unknownFields mergeVarintField:2 value:value];
        }
        break;
      }
      case 34: {
        BoosterItemProto_Builder* subBuilder = [BoosterItemProto builder];
        [input readMessage:subBuilder extensionRegistry:extensionRegistry];
        [self addPrize:[subBuilder buildPartial]];
        break;
      }
      case 50: {
        UserRewardProto_Builder* subBuilder = [UserRewardProto builder];
        if (self.hasReward) {
          [subBuilder mergeFrom:self.reward];
        }
        [input readMessage:subBuilder extensionRegistry:extensionRegistry];
        [self setReward:[subBuilder buildPartial]];
        break;
      }
    }
  }
}
- (BOOL) hasSender {
  return result.hasSender;
}
- (MinimumUserProto*) sender {
  return result.sender;
}
- (PurchaseBoosterPackResponseProto_Builder*) setSender:(MinimumUserProto*) value {
  result.hasSender = YES;
  result.sender = value;
  return self;
}
- (PurchaseBoosterPackResponseProto_Builder*) setSender_Builder:(MinimumUserProto_Builder*) builderForValue {
  return [self setSender:[builderForValue build]];
}
- (PurchaseBoosterPackResponseProto_Builder*) mergeSender:(MinimumUserProto*) value {
  if (result.hasSender &&
      result.sender != [MinimumUserProto defaultInstance]) {
    result.sender =
      [[[MinimumUserProto builderWithPrototype:result.sender] mergeFrom:value] buildPartial];
  } else {
    result.sender = value;
  }
  result.hasSender = YES;
  return self;
}
- (PurchaseBoosterPackResponseProto_Builder*) clearSender {
  result.hasSender = NO;
  result.sender = [MinimumUserProto defaultInstance];
  return self;
}
- (BOOL) hasStatus {
  return result.hasStatus;
}
- (ResponseStatus) status {
  return result.status;
}
- (PurchaseBoosterPackResponseProto_Builder*) setStatus:(ResponseStatus) value {
  result.hasStatus = YES;
  result.status = value;
  return self;
}
- (PurchaseBoosterPackResponseProto_Builder*) clearStatusList {
  result.hasStatus = NO;
  result.status = ResponseStatusSuccess;
  return self;
}
- (NSMutableArray *)prizeList {
  return result.mutablePrizeList;
}
- (BoosterItemProto*)prizeAtIndex:(NSUInteger)index {
  return [result prizeAtIndex:index];
}
- (PurchaseBoosterPackResponseProto_Builder *)addPrize:(BoosterItemProto*)value {
  if (result.mutablePrizeList == nil) {
    result.mutablePrizeList = [[NSMutableArray alloc]init];
  }
  [result.mutablePrizeList addObject:value];
  return self;
}
- (PurchaseBoosterPackResponseProto_Builder *)addAllPrize:(NSArray *)array {
  if (result.mutablePrizeList == nil) {
    result.mutablePrizeList = [NSMutableArray array];
  }
  [result.mutablePrizeList addObjectsFromArray:array];
  return self;
}
- (PurchaseBoosterPackResponseProto_Builder *)clearPrize {
  result.mutablePrizeList = nil;
  return self;
}
- (BOOL) hasReward {
  return result.hasReward;
}
- (UserRewardProto*) reward {
  return result.reward;
}
- (PurchaseBoosterPackResponseProto_Builder*) setReward:(UserRewardProto*) value {
  result.hasReward = YES;
  result.reward = value;
  return self;
}
- (PurchaseBoosterPackResponseProto_Builder*) setReward_Builder:(UserRewardProto_Builder*) builderForValue {
  return [self setReward:[builderForValue build]];
}
- (PurchaseBoosterPackResponseProto_Builder*) mergeReward:(UserRewardProto*) value {
  if (result.hasReward &&
      result.reward != [UserRewardProto defaultInstance]) {
    result.reward =
      [[[UserRewardProto builderWithPrototype:result.reward] mergeFrom:value] buildPartial];
  } else {
    result.reward = value;
  }
  result.hasReward = YES;
  return self;
}
- (PurchaseBoosterPackResponseProto_Builder*) clearReward {
  result.hasReward = NO;
  result.reward = [UserRewardProto defaultInstance];
  return self;
}
@end

@interface ReceivedRareBoosterPurchaseResponseProto ()
@property (strong) RareBoosterPurchaseProto* rareBoosterPurchase;
@end

@implementation ReceivedRareBoosterPurchaseResponseProto

- (BOOL) hasRareBoosterPurchase {
  return !!hasRareBoosterPurchase_;
}
- (void) setHasRareBoosterPurchase:(BOOL) value_ {
  hasRareBoosterPurchase_ = !!value_;
}
@synthesize rareBoosterPurchase;
- (id) init {
  if ((self = [super init])) {
    self.rareBoosterPurchase = [RareBoosterPurchaseProto defaultInstance];
  }
  return self;
}
static ReceivedRareBoosterPurchaseResponseProto* defaultReceivedRareBoosterPurchaseResponseProtoInstance = nil;
+ (void) initialize {
  if (self == [ReceivedRareBoosterPurchaseResponseProto class]) {
    defaultReceivedRareBoosterPurchaseResponseProtoInstance = [[ReceivedRareBoosterPurchaseResponseProto alloc] init];
  }
}
+ (ReceivedRareBoosterPurchaseResponseProto*) defaultInstance {
  return defaultReceivedRareBoosterPurchaseResponseProtoInstance;
}
- (ReceivedRareBoosterPurchaseResponseProto*) defaultInstance {
  return defaultReceivedRareBoosterPurchaseResponseProtoInstance;
}
- (BOOL) isInitialized {
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasRareBoosterPurchase) {
    [output writeMessage:1 value:self.rareBoosterPurchase];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (SInt32) serializedSize {
  __block SInt32 size_ = memoizedSerializedSize;
  if (size_ != -1) {
    return size_;
  }

  size_ = 0;
  if (self.hasRareBoosterPurchase) {
    size_ += computeMessageSize(1, self.rareBoosterPurchase);
  }
  size_ += self.unknownFields.serializedSize;
  memoizedSerializedSize = size_;
  return size_;
}
+ (ReceivedRareBoosterPurchaseResponseProto*) parseFromData:(NSData*) data {
  return (ReceivedRareBoosterPurchaseResponseProto*)[[[ReceivedRareBoosterPurchaseResponseProto builder] mergeFromData:data] build];
}
+ (ReceivedRareBoosterPurchaseResponseProto*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (ReceivedRareBoosterPurchaseResponseProto*)[[[ReceivedRareBoosterPurchaseResponseProto builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (ReceivedRareBoosterPurchaseResponseProto*) parseFromInputStream:(NSInputStream*) input {
  return (ReceivedRareBoosterPurchaseResponseProto*)[[[ReceivedRareBoosterPurchaseResponseProto builder] mergeFromInputStream:input] build];
}
+ (ReceivedRareBoosterPurchaseResponseProto*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (ReceivedRareBoosterPurchaseResponseProto*)[[[ReceivedRareBoosterPurchaseResponseProto builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (ReceivedRareBoosterPurchaseResponseProto*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (ReceivedRareBoosterPurchaseResponseProto*)[[[ReceivedRareBoosterPurchaseResponseProto builder] mergeFromCodedInputStream:input] build];
}
+ (ReceivedRareBoosterPurchaseResponseProto*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (ReceivedRareBoosterPurchaseResponseProto*)[[[ReceivedRareBoosterPurchaseResponseProto builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (ReceivedRareBoosterPurchaseResponseProto_Builder*) builder {
  return [[ReceivedRareBoosterPurchaseResponseProto_Builder alloc] init];
}
+ (ReceivedRareBoosterPurchaseResponseProto_Builder*) builderWithPrototype:(ReceivedRareBoosterPurchaseResponseProto*) prototype {
  return [[ReceivedRareBoosterPurchaseResponseProto builder] mergeFrom:prototype];
}
- (ReceivedRareBoosterPurchaseResponseProto_Builder*) builder {
  return [ReceivedRareBoosterPurchaseResponseProto builder];
}
- (ReceivedRareBoosterPurchaseResponseProto_Builder*) toBuilder {
  return [ReceivedRareBoosterPurchaseResponseProto builderWithPrototype:self];
}
- (void) writeDescriptionTo:(NSMutableString*) output withIndent:(NSString*) indent {
  if (self.hasRareBoosterPurchase) {
    [output appendFormat:@"%@%@ {\n", indent, @"rareBoosterPurchase"];
    [self.rareBoosterPurchase writeDescriptionTo:output
                         withIndent:[NSString stringWithFormat:@"%@  ", indent]];
    [output appendFormat:@"%@}\n", indent];
  }
  [self.unknownFields writeDescriptionTo:output withIndent:indent];
}
- (BOOL) isEqual:(id)other {
  if (other == self) {
    return YES;
  }
  if (![other isKindOfClass:[ReceivedRareBoosterPurchaseResponseProto class]]) {
    return NO;
  }
  ReceivedRareBoosterPurchaseResponseProto *otherMessage = other;
  return
      self.hasRareBoosterPurchase == otherMessage.hasRareBoosterPurchase &&
      (!self.hasRareBoosterPurchase || [self.rareBoosterPurchase isEqual:otherMessage.rareBoosterPurchase]) &&
      (self.unknownFields == otherMessage.unknownFields || (self.unknownFields != nil && [self.unknownFields isEqual:otherMessage.unknownFields]));
}
- (NSUInteger) hash {
  __block NSUInteger hashCode = 7;
  if (self.hasRareBoosterPurchase) {
    hashCode = hashCode * 31 + [self.rareBoosterPurchase hash];
  }
  hashCode = hashCode * 31 + [self.unknownFields hash];
  return hashCode;
}
@end

@interface ReceivedRareBoosterPurchaseResponseProto_Builder()
@property (strong) ReceivedRareBoosterPurchaseResponseProto* result;
@end

@implementation ReceivedRareBoosterPurchaseResponseProto_Builder
@synthesize result;
- (id) init {
  if ((self = [super init])) {
    self.result = [[ReceivedRareBoosterPurchaseResponseProto alloc] init];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return result;
}
- (ReceivedRareBoosterPurchaseResponseProto_Builder*) clear {
  self.result = [[ReceivedRareBoosterPurchaseResponseProto alloc] init];
  return self;
}
- (ReceivedRareBoosterPurchaseResponseProto_Builder*) clone {
  return [ReceivedRareBoosterPurchaseResponseProto builderWithPrototype:result];
}
- (ReceivedRareBoosterPurchaseResponseProto*) defaultInstance {
  return [ReceivedRareBoosterPurchaseResponseProto defaultInstance];
}
- (ReceivedRareBoosterPurchaseResponseProto*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (ReceivedRareBoosterPurchaseResponseProto*) buildPartial {
  ReceivedRareBoosterPurchaseResponseProto* returnMe = result;
  self.result = nil;
  return returnMe;
}
- (ReceivedRareBoosterPurchaseResponseProto_Builder*) mergeFrom:(ReceivedRareBoosterPurchaseResponseProto*) other {
  if (other == [ReceivedRareBoosterPurchaseResponseProto defaultInstance]) {
    return self;
  }
  if (other.hasRareBoosterPurchase) {
    [self mergeRareBoosterPurchase:other.rareBoosterPurchase];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (ReceivedRareBoosterPurchaseResponseProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (ReceivedRareBoosterPurchaseResponseProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSetBuilder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    SInt32 tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 10: {
        RareBoosterPurchaseProto_Builder* subBuilder = [RareBoosterPurchaseProto builder];
        if (self.hasRareBoosterPurchase) {
          [subBuilder mergeFrom:self.rareBoosterPurchase];
        }
        [input readMessage:subBuilder extensionRegistry:extensionRegistry];
        [self setRareBoosterPurchase:[subBuilder buildPartial]];
        break;
      }
    }
  }
}
- (BOOL) hasRareBoosterPurchase {
  return result.hasRareBoosterPurchase;
}
- (RareBoosterPurchaseProto*) rareBoosterPurchase {
  return result.rareBoosterPurchase;
}
- (ReceivedRareBoosterPurchaseResponseProto_Builder*) setRareBoosterPurchase:(RareBoosterPurchaseProto*) value {
  result.hasRareBoosterPurchase = YES;
  result.rareBoosterPurchase = value;
  return self;
}
- (ReceivedRareBoosterPurchaseResponseProto_Builder*) setRareBoosterPurchase_Builder:(RareBoosterPurchaseProto_Builder*) builderForValue {
  return [self setRareBoosterPurchase:[builderForValue build]];
}
- (ReceivedRareBoosterPurchaseResponseProto_Builder*) mergeRareBoosterPurchase:(RareBoosterPurchaseProto*) value {
  if (result.hasRareBoosterPurchase &&
      result.rareBoosterPurchase != [RareBoosterPurchaseProto defaultInstance]) {
    result.rareBoosterPurchase =
      [[[RareBoosterPurchaseProto builderWithPrototype:result.rareBoosterPurchase] mergeFrom:value] buildPartial];
  } else {
    result.rareBoosterPurchase = value;
  }
  result.hasRareBoosterPurchase = YES;
  return self;
}
- (ReceivedRareBoosterPurchaseResponseProto_Builder*) clearRareBoosterPurchase {
  result.hasRareBoosterPurchase = NO;
  result.rareBoosterPurchase = [RareBoosterPurchaseProto defaultInstance];
  return self;
}
@end


// @@protoc_insertion_point(global_scope)
