// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

#import "LeaderBoard.pb.h"
#import "SharedEnumConfig.pb.h"
#import "User.pb.h"
// @@protoc_insertion_point(imports)

@class FullUserProto;
@class FullUserProto_Builder;
@class MinimumClanProto;
@class MinimumClanProto_Builder;
@class MinimumUserProto;
@class MinimumUserProtoWithFacebookId;
@class MinimumUserProtoWithFacebookId_Builder;
@class MinimumUserProtoWithMaxResources;
@class MinimumUserProtoWithMaxResources_Builder;
@class MinimumUserProto_Builder;
@class RetrieveStrengthLeaderBoardRequestProto;
@class RetrieveStrengthLeaderBoardRequestProto_Builder;
@class RetrieveStrengthLeaderBoardResponseProto;
@class RetrieveStrengthLeaderBoardResponseProto_Builder;
@class StaticUserLevelInfoProto;
@class StaticUserLevelInfoProto_Builder;
@class StrengthLeaderBoardProto;
@class StrengthLeaderBoardProto_Builder;
@class UserFacebookInviteForSlotProto;
@class UserFacebookInviteForSlotProto_Builder;
@class UserPvpLeagueProto;
@class UserPvpLeagueProto_Builder;
#ifndef __has_feature
  #define __has_feature(x) 0 // Compatibility with non-clang compilers.
#endif // __has_feature

#ifndef NS_RETURNS_NOT_RETAINED
  #if __has_feature(attribute_ns_returns_not_retained)
    #define NS_RETURNS_NOT_RETAINED __attribute__((ns_returns_not_retained))
  #else
    #define NS_RETURNS_NOT_RETAINED
  #endif
#endif


@interface EventLeaderBoardRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface RetrieveStrengthLeaderBoardRequestProto : PBGeneratedMessage {
@private
  BOOL hasMinRank_:1;
  BOOL hasMaxRank_:1;
  BOOL hasSender_:1;
  int32_t minRank;
  int32_t maxRank;
  MinimumUserProto* sender;
}
- (BOOL) hasSender;
- (BOOL) hasMinRank;
- (BOOL) hasMaxRank;
@property (readonly, strong) MinimumUserProto* sender;
@property (readonly) int32_t minRank;
@property (readonly) int32_t maxRank;

+ (RetrieveStrengthLeaderBoardRequestProto*) defaultInstance;
- (RetrieveStrengthLeaderBoardRequestProto*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (RetrieveStrengthLeaderBoardRequestProto_Builder*) builder;
+ (RetrieveStrengthLeaderBoardRequestProto_Builder*) builder;
+ (RetrieveStrengthLeaderBoardRequestProto_Builder*) builderWithPrototype:(RetrieveStrengthLeaderBoardRequestProto*) prototype;
- (RetrieveStrengthLeaderBoardRequestProto_Builder*) toBuilder;

+ (RetrieveStrengthLeaderBoardRequestProto*) parseFromData:(NSData*) data;
+ (RetrieveStrengthLeaderBoardRequestProto*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (RetrieveStrengthLeaderBoardRequestProto*) parseFromInputStream:(NSInputStream*) input;
+ (RetrieveStrengthLeaderBoardRequestProto*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (RetrieveStrengthLeaderBoardRequestProto*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (RetrieveStrengthLeaderBoardRequestProto*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface RetrieveStrengthLeaderBoardRequestProto_Builder : PBGeneratedMessageBuilder {
@private
  RetrieveStrengthLeaderBoardRequestProto* result;
}

- (RetrieveStrengthLeaderBoardRequestProto*) defaultInstance;

- (RetrieveStrengthLeaderBoardRequestProto_Builder*) clear;
- (RetrieveStrengthLeaderBoardRequestProto_Builder*) clone;

- (RetrieveStrengthLeaderBoardRequestProto*) build;
- (RetrieveStrengthLeaderBoardRequestProto*) buildPartial;

- (RetrieveStrengthLeaderBoardRequestProto_Builder*) mergeFrom:(RetrieveStrengthLeaderBoardRequestProto*) other;
- (RetrieveStrengthLeaderBoardRequestProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (RetrieveStrengthLeaderBoardRequestProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasSender;
- (MinimumUserProto*) sender;
- (RetrieveStrengthLeaderBoardRequestProto_Builder*) setSender:(MinimumUserProto*) value;
- (RetrieveStrengthLeaderBoardRequestProto_Builder*) setSender_Builder:(MinimumUserProto_Builder*) builderForValue;
- (RetrieveStrengthLeaderBoardRequestProto_Builder*) mergeSender:(MinimumUserProto*) value;
- (RetrieveStrengthLeaderBoardRequestProto_Builder*) clearSender;

- (BOOL) hasMinRank;
- (int32_t) minRank;
- (RetrieveStrengthLeaderBoardRequestProto_Builder*) setMinRank:(int32_t) value;
- (RetrieveStrengthLeaderBoardRequestProto_Builder*) clearMinRank;

- (BOOL) hasMaxRank;
- (int32_t) maxRank;
- (RetrieveStrengthLeaderBoardRequestProto_Builder*) setMaxRank:(int32_t) value;
- (RetrieveStrengthLeaderBoardRequestProto_Builder*) clearMaxRank;
@end

@interface RetrieveStrengthLeaderBoardResponseProto : PBGeneratedMessage {
@private
  BOOL hasSender_:1;
  BOOL hasSenderLeaderBoardInfo_:1;
  BOOL hasStatus_:1;
  MinimumUserProto* sender;
  StrengthLeaderBoardProto* senderLeaderBoardInfo;
  ResponseStatus status;
  NSMutableArray * mutableLeaderBoardInfoList;
}
- (BOOL) hasSender;
- (BOOL) hasSenderLeaderBoardInfo;
- (BOOL) hasStatus;
@property (readonly, strong) MinimumUserProto* sender;
@property (readonly, strong) StrengthLeaderBoardProto* senderLeaderBoardInfo;
@property (readonly, strong) NSArray * leaderBoardInfoList;
@property (readonly) ResponseStatus status;
- (StrengthLeaderBoardProto*)leaderBoardInfoAtIndex:(NSUInteger)index;

+ (RetrieveStrengthLeaderBoardResponseProto*) defaultInstance;
- (RetrieveStrengthLeaderBoardResponseProto*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (RetrieveStrengthLeaderBoardResponseProto_Builder*) builder;
+ (RetrieveStrengthLeaderBoardResponseProto_Builder*) builder;
+ (RetrieveStrengthLeaderBoardResponseProto_Builder*) builderWithPrototype:(RetrieveStrengthLeaderBoardResponseProto*) prototype;
- (RetrieveStrengthLeaderBoardResponseProto_Builder*) toBuilder;

+ (RetrieveStrengthLeaderBoardResponseProto*) parseFromData:(NSData*) data;
+ (RetrieveStrengthLeaderBoardResponseProto*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (RetrieveStrengthLeaderBoardResponseProto*) parseFromInputStream:(NSInputStream*) input;
+ (RetrieveStrengthLeaderBoardResponseProto*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (RetrieveStrengthLeaderBoardResponseProto*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (RetrieveStrengthLeaderBoardResponseProto*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface RetrieveStrengthLeaderBoardResponseProto_Builder : PBGeneratedMessageBuilder {
@private
  RetrieveStrengthLeaderBoardResponseProto* result;
}

- (RetrieveStrengthLeaderBoardResponseProto*) defaultInstance;

- (RetrieveStrengthLeaderBoardResponseProto_Builder*) clear;
- (RetrieveStrengthLeaderBoardResponseProto_Builder*) clone;

- (RetrieveStrengthLeaderBoardResponseProto*) build;
- (RetrieveStrengthLeaderBoardResponseProto*) buildPartial;

- (RetrieveStrengthLeaderBoardResponseProto_Builder*) mergeFrom:(RetrieveStrengthLeaderBoardResponseProto*) other;
- (RetrieveStrengthLeaderBoardResponseProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (RetrieveStrengthLeaderBoardResponseProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasSender;
- (MinimumUserProto*) sender;
- (RetrieveStrengthLeaderBoardResponseProto_Builder*) setSender:(MinimumUserProto*) value;
- (RetrieveStrengthLeaderBoardResponseProto_Builder*) setSender_Builder:(MinimumUserProto_Builder*) builderForValue;
- (RetrieveStrengthLeaderBoardResponseProto_Builder*) mergeSender:(MinimumUserProto*) value;
- (RetrieveStrengthLeaderBoardResponseProto_Builder*) clearSender;

- (BOOL) hasSenderLeaderBoardInfo;
- (StrengthLeaderBoardProto*) senderLeaderBoardInfo;
- (RetrieveStrengthLeaderBoardResponseProto_Builder*) setSenderLeaderBoardInfo:(StrengthLeaderBoardProto*) value;
- (RetrieveStrengthLeaderBoardResponseProto_Builder*) setSenderLeaderBoardInfo_Builder:(StrengthLeaderBoardProto_Builder*) builderForValue;
- (RetrieveStrengthLeaderBoardResponseProto_Builder*) mergeSenderLeaderBoardInfo:(StrengthLeaderBoardProto*) value;
- (RetrieveStrengthLeaderBoardResponseProto_Builder*) clearSenderLeaderBoardInfo;

- (NSMutableArray *)leaderBoardInfoList;
- (StrengthLeaderBoardProto*)leaderBoardInfoAtIndex:(NSUInteger)index;
- (RetrieveStrengthLeaderBoardResponseProto_Builder *)addLeaderBoardInfo:(StrengthLeaderBoardProto*)value;
- (RetrieveStrengthLeaderBoardResponseProto_Builder *)addAllLeaderBoardInfo:(NSArray *)array;
- (RetrieveStrengthLeaderBoardResponseProto_Builder *)clearLeaderBoardInfo;

- (BOOL) hasStatus;
- (ResponseStatus) status;
- (RetrieveStrengthLeaderBoardResponseProto_Builder*) setStatus:(ResponseStatus) value;
- (RetrieveStrengthLeaderBoardResponseProto_Builder*) clearStatusList;
@end


// @@protoc_insertion_point(global_scope)
