// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "Item.pb.h"
// @@protoc_insertion_point(imports)

@implementation ItemRoot
static PBExtensionRegistry* extensionRegistry = nil;
+ (PBExtensionRegistry*) extensionRegistry {
  return extensionRegistry;
}

+ (void) initialize {
  if (self == [ItemRoot class]) {
    PBMutableExtensionRegistry* registry = [PBMutableExtensionRegistry registry];
    [self registerAllExtensions:registry];
    [SharedEnumConfigRoot registerAllExtensions:registry];
    extensionRegistry = registry;
  }
}
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry {
}
@end

BOOL ItemTypeIsValidValue(ItemType value) {
  switch (value) {
    case ItemTypeBoosterPack:
    case ItemTypeItemOil:
    case ItemTypeItemCash:
    case ItemTypeItemGachaCredit:
    case ItemTypeSpeedUp:
    case ItemTypeBuilder:
    case ItemTypeRefreshMiniJob:
    case ItemTypeGachaMultiSpin:
      return YES;
    default:
      return NO;
  }
}
@interface UserItemProto ()
@property (strong) NSString* userUuid;
@property int32_t itemId;
@property int32_t quantity;
@end

@implementation UserItemProto

- (BOOL) hasUserUuid {
  return !!hasUserUuid_;
}
- (void) setHasUserUuid:(BOOL) value_ {
  hasUserUuid_ = !!value_;
}
@synthesize userUuid;
- (BOOL) hasItemId {
  return !!hasItemId_;
}
- (void) setHasItemId:(BOOL) value_ {
  hasItemId_ = !!value_;
}
@synthesize itemId;
- (BOOL) hasQuantity {
  return !!hasQuantity_;
}
- (void) setHasQuantity:(BOOL) value_ {
  hasQuantity_ = !!value_;
}
@synthesize quantity;
- (id) init {
  if ((self = [super init])) {
    self.userUuid = @"";
    self.itemId = 0;
    self.quantity = 0;
  }
  return self;
}
static UserItemProto* defaultUserItemProtoInstance = nil;
+ (void) initialize {
  if (self == [UserItemProto class]) {
    defaultUserItemProtoInstance = [[UserItemProto alloc] init];
  }
}
+ (UserItemProto*) defaultInstance {
  return defaultUserItemProtoInstance;
}
- (UserItemProto*) defaultInstance {
  return defaultUserItemProtoInstance;
}
- (BOOL) isInitialized {
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasUserUuid) {
    [output writeString:1 value:self.userUuid];
  }
  if (self.hasItemId) {
    [output writeInt32:2 value:self.itemId];
  }
  if (self.hasQuantity) {
    [output writeInt32:3 value:self.quantity];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (SInt32) serializedSize {
  __block SInt32 size_ = memoizedSerializedSize;
  if (size_ != -1) {
    return size_;
  }

  size_ = 0;
  if (self.hasUserUuid) {
    size_ += computeStringSize(1, self.userUuid);
  }
  if (self.hasItemId) {
    size_ += computeInt32Size(2, self.itemId);
  }
  if (self.hasQuantity) {
    size_ += computeInt32Size(3, self.quantity);
  }
  size_ += self.unknownFields.serializedSize;
  memoizedSerializedSize = size_;
  return size_;
}
+ (UserItemProto*) parseFromData:(NSData*) data {
  return (UserItemProto*)[[[UserItemProto builder] mergeFromData:data] build];
}
+ (UserItemProto*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (UserItemProto*)[[[UserItemProto builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (UserItemProto*) parseFromInputStream:(NSInputStream*) input {
  return (UserItemProto*)[[[UserItemProto builder] mergeFromInputStream:input] build];
}
+ (UserItemProto*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (UserItemProto*)[[[UserItemProto builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (UserItemProto*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (UserItemProto*)[[[UserItemProto builder] mergeFromCodedInputStream:input] build];
}
+ (UserItemProto*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (UserItemProto*)[[[UserItemProto builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (UserItemProto_Builder*) builder {
  return [[UserItemProto_Builder alloc] init];
}
+ (UserItemProto_Builder*) builderWithPrototype:(UserItemProto*) prototype {
  return [[UserItemProto builder] mergeFrom:prototype];
}
- (UserItemProto_Builder*) builder {
  return [UserItemProto builder];
}
- (UserItemProto_Builder*) toBuilder {
  return [UserItemProto builderWithPrototype:self];
}
- (void) writeDescriptionTo:(NSMutableString*) output withIndent:(NSString*) indent {
  if (self.hasUserUuid) {
    [output appendFormat:@"%@%@: %@\n", indent, @"userUuid", self.userUuid];
  }
  if (self.hasItemId) {
    [output appendFormat:@"%@%@: %@\n", indent, @"itemId", [NSNumber numberWithInteger:self.itemId]];
  }
  if (self.hasQuantity) {
    [output appendFormat:@"%@%@: %@\n", indent, @"quantity", [NSNumber numberWithInteger:self.quantity]];
  }
  [self.unknownFields writeDescriptionTo:output withIndent:indent];
}
- (BOOL) isEqual:(id)other {
  if (other == self) {
    return YES;
  }
  if (![other isKindOfClass:[UserItemProto class]]) {
    return NO;
  }
  UserItemProto *otherMessage = other;
  return
      self.hasUserUuid == otherMessage.hasUserUuid &&
      (!self.hasUserUuid || [self.userUuid isEqual:otherMessage.userUuid]) &&
      self.hasItemId == otherMessage.hasItemId &&
      (!self.hasItemId || self.itemId == otherMessage.itemId) &&
      self.hasQuantity == otherMessage.hasQuantity &&
      (!self.hasQuantity || self.quantity == otherMessage.quantity) &&
      (self.unknownFields == otherMessage.unknownFields || (self.unknownFields != nil && [self.unknownFields isEqual:otherMessage.unknownFields]));
}
- (NSUInteger) hash {
  __block NSUInteger hashCode = 7;
  if (self.hasUserUuid) {
    hashCode = hashCode * 31 + [self.userUuid hash];
  }
  if (self.hasItemId) {
    hashCode = hashCode * 31 + [[NSNumber numberWithInteger:self.itemId] hash];
  }
  if (self.hasQuantity) {
    hashCode = hashCode * 31 + [[NSNumber numberWithInteger:self.quantity] hash];
  }
  hashCode = hashCode * 31 + [self.unknownFields hash];
  return hashCode;
}
@end

@interface UserItemProto_Builder()
@property (strong) UserItemProto* result;
@end

@implementation UserItemProto_Builder
@synthesize result;
- (id) init {
  if ((self = [super init])) {
    self.result = [[UserItemProto alloc] init];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return result;
}
- (UserItemProto_Builder*) clear {
  self.result = [[UserItemProto alloc] init];
  return self;
}
- (UserItemProto_Builder*) clone {
  return [UserItemProto builderWithPrototype:result];
}
- (UserItemProto*) defaultInstance {
  return [UserItemProto defaultInstance];
}
- (UserItemProto*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (UserItemProto*) buildPartial {
  UserItemProto* returnMe = result;
  self.result = nil;
  return returnMe;
}
- (UserItemProto_Builder*) mergeFrom:(UserItemProto*) other {
  if (other == [UserItemProto defaultInstance]) {
    return self;
  }
  if (other.hasUserUuid) {
    [self setUserUuid:other.userUuid];
  }
  if (other.hasItemId) {
    [self setItemId:other.itemId];
  }
  if (other.hasQuantity) {
    [self setQuantity:other.quantity];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (UserItemProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (UserItemProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSetBuilder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    SInt32 tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 10: {
        [self setUserUuid:[input readString]];
        break;
      }
      case 16: {
        [self setItemId:[input readInt32]];
        break;
      }
      case 24: {
        [self setQuantity:[input readInt32]];
        break;
      }
    }
  }
}
- (BOOL) hasUserUuid {
  return result.hasUserUuid;
}
- (NSString*) userUuid {
  return result.userUuid;
}
- (UserItemProto_Builder*) setUserUuid:(NSString*) value {
  result.hasUserUuid = YES;
  result.userUuid = value;
  return self;
}
- (UserItemProto_Builder*) clearUserUuid {
  result.hasUserUuid = NO;
  result.userUuid = @"";
  return self;
}
- (BOOL) hasItemId {
  return result.hasItemId;
}
- (int32_t) itemId {
  return result.itemId;
}
- (UserItemProto_Builder*) setItemId:(int32_t) value {
  result.hasItemId = YES;
  result.itemId = value;
  return self;
}
- (UserItemProto_Builder*) clearItemId {
  result.hasItemId = NO;
  result.itemId = 0;
  return self;
}
- (BOOL) hasQuantity {
  return result.hasQuantity;
}
- (int32_t) quantity {
  return result.quantity;
}
- (UserItemProto_Builder*) setQuantity:(int32_t) value {
  result.hasQuantity = YES;
  result.quantity = value;
  return self;
}
- (UserItemProto_Builder*) clearQuantity {
  result.hasQuantity = NO;
  result.quantity = 0;
  return self;
}
@end

@interface ItemProto ()
@property int32_t itemId;
@property (strong) NSString* name;
@property (strong) NSString* imgName;
@property ItemType itemType;
@property int32_t staticDataId;
@property int32_t amount;
@property Float32 secretGiftChance;
@property BOOL alwaysDisplayToUser;
@property GameActionType gameActionType;
@property (strong) NSString* shortName;
@property Quality quality;
@end

@implementation ItemProto

- (BOOL) hasItemId {
  return !!hasItemId_;
}
- (void) setHasItemId:(BOOL) value_ {
  hasItemId_ = !!value_;
}
@synthesize itemId;
- (BOOL) hasName {
  return !!hasName_;
}
- (void) setHasName:(BOOL) value_ {
  hasName_ = !!value_;
}
@synthesize name;
- (BOOL) hasImgName {
  return !!hasImgName_;
}
- (void) setHasImgName:(BOOL) value_ {
  hasImgName_ = !!value_;
}
@synthesize imgName;
- (BOOL) hasItemType {
  return !!hasItemType_;
}
- (void) setHasItemType:(BOOL) value_ {
  hasItemType_ = !!value_;
}
@synthesize itemType;
- (BOOL) hasStaticDataId {
  return !!hasStaticDataId_;
}
- (void) setHasStaticDataId:(BOOL) value_ {
  hasStaticDataId_ = !!value_;
}
@synthesize staticDataId;
- (BOOL) hasAmount {
  return !!hasAmount_;
}
- (void) setHasAmount:(BOOL) value_ {
  hasAmount_ = !!value_;
}
@synthesize amount;
- (BOOL) hasSecretGiftChance {
  return !!hasSecretGiftChance_;
}
- (void) setHasSecretGiftChance:(BOOL) value_ {
  hasSecretGiftChance_ = !!value_;
}
@synthesize secretGiftChance;
- (BOOL) hasAlwaysDisplayToUser {
  return !!hasAlwaysDisplayToUser_;
}
- (void) setHasAlwaysDisplayToUser:(BOOL) value_ {
  hasAlwaysDisplayToUser_ = !!value_;
}
- (BOOL) alwaysDisplayToUser {
  return !!alwaysDisplayToUser_;
}
- (void) setAlwaysDisplayToUser:(BOOL) value_ {
  alwaysDisplayToUser_ = !!value_;
}
- (BOOL) hasGameActionType {
  return !!hasGameActionType_;
}
- (void) setHasGameActionType:(BOOL) value_ {
  hasGameActionType_ = !!value_;
}
@synthesize gameActionType;
- (BOOL) hasShortName {
  return !!hasShortName_;
}
- (void) setHasShortName:(BOOL) value_ {
  hasShortName_ = !!value_;
}
@synthesize shortName;
- (BOOL) hasQuality {
  return !!hasQuality_;
}
- (void) setHasQuality:(BOOL) value_ {
  hasQuality_ = !!value_;
}
@synthesize quality;
- (id) init {
  if ((self = [super init])) {
    self.itemId = 0;
    self.name = @"";
    self.imgName = @"";
    self.itemType = ItemTypeBoosterPack;
    self.staticDataId = 0;
    self.amount = 0;
    self.secretGiftChance = 0;
    self.alwaysDisplayToUser = NO;
    self.gameActionType = GameActionTypeNoHelp;
    self.shortName = @"";
    self.quality = QualityNoQuality;
  }
  return self;
}
static ItemProto* defaultItemProtoInstance = nil;
+ (void) initialize {
  if (self == [ItemProto class]) {
    defaultItemProtoInstance = [[ItemProto alloc] init];
  }
}
+ (ItemProto*) defaultInstance {
  return defaultItemProtoInstance;
}
- (ItemProto*) defaultInstance {
  return defaultItemProtoInstance;
}
- (BOOL) isInitialized {
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasItemId) {
    [output writeInt32:1 value:self.itemId];
  }
  if (self.hasName) {
    [output writeString:2 value:self.name];
  }
  if (self.hasImgName) {
    [output writeString:3 value:self.imgName];
  }
  if (self.hasItemType) {
    [output writeEnum:4 value:self.itemType];
  }
  if (self.hasStaticDataId) {
    [output writeInt32:5 value:self.staticDataId];
  }
  if (self.hasAmount) {
    [output writeInt32:6 value:self.amount];
  }
  if (self.hasSecretGiftChance) {
    [output writeFloat:7 value:self.secretGiftChance];
  }
  if (self.hasAlwaysDisplayToUser) {
    [output writeBool:8 value:self.alwaysDisplayToUser];
  }
  if (self.hasGameActionType) {
    [output writeEnum:9 value:self.gameActionType];
  }
  if (self.hasShortName) {
    [output writeString:10 value:self.shortName];
  }
  if (self.hasQuality) {
    [output writeEnum:11 value:self.quality];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (SInt32) serializedSize {
  __block SInt32 size_ = memoizedSerializedSize;
  if (size_ != -1) {
    return size_;
  }

  size_ = 0;
  if (self.hasItemId) {
    size_ += computeInt32Size(1, self.itemId);
  }
  if (self.hasName) {
    size_ += computeStringSize(2, self.name);
  }
  if (self.hasImgName) {
    size_ += computeStringSize(3, self.imgName);
  }
  if (self.hasItemType) {
    size_ += computeEnumSize(4, self.itemType);
  }
  if (self.hasStaticDataId) {
    size_ += computeInt32Size(5, self.staticDataId);
  }
  if (self.hasAmount) {
    size_ += computeInt32Size(6, self.amount);
  }
  if (self.hasSecretGiftChance) {
    size_ += computeFloatSize(7, self.secretGiftChance);
  }
  if (self.hasAlwaysDisplayToUser) {
    size_ += computeBoolSize(8, self.alwaysDisplayToUser);
  }
  if (self.hasGameActionType) {
    size_ += computeEnumSize(9, self.gameActionType);
  }
  if (self.hasShortName) {
    size_ += computeStringSize(10, self.shortName);
  }
  if (self.hasQuality) {
    size_ += computeEnumSize(11, self.quality);
  }
  size_ += self.unknownFields.serializedSize;
  memoizedSerializedSize = size_;
  return size_;
}
+ (ItemProto*) parseFromData:(NSData*) data {
  return (ItemProto*)[[[ItemProto builder] mergeFromData:data] build];
}
+ (ItemProto*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (ItemProto*)[[[ItemProto builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (ItemProto*) parseFromInputStream:(NSInputStream*) input {
  return (ItemProto*)[[[ItemProto builder] mergeFromInputStream:input] build];
}
+ (ItemProto*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (ItemProto*)[[[ItemProto builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (ItemProto*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (ItemProto*)[[[ItemProto builder] mergeFromCodedInputStream:input] build];
}
+ (ItemProto*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (ItemProto*)[[[ItemProto builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (ItemProto_Builder*) builder {
  return [[ItemProto_Builder alloc] init];
}
+ (ItemProto_Builder*) builderWithPrototype:(ItemProto*) prototype {
  return [[ItemProto builder] mergeFrom:prototype];
}
- (ItemProto_Builder*) builder {
  return [ItemProto builder];
}
- (ItemProto_Builder*) toBuilder {
  return [ItemProto builderWithPrototype:self];
}
- (void) writeDescriptionTo:(NSMutableString*) output withIndent:(NSString*) indent {
  if (self.hasItemId) {
    [output appendFormat:@"%@%@: %@\n", indent, @"itemId", [NSNumber numberWithInteger:self.itemId]];
  }
  if (self.hasName) {
    [output appendFormat:@"%@%@: %@\n", indent, @"name", self.name];
  }
  if (self.hasImgName) {
    [output appendFormat:@"%@%@: %@\n", indent, @"imgName", self.imgName];
  }
  if (self.hasItemType) {
    [output appendFormat:@"%@%@: %@\n", indent, @"itemType", [NSNumber numberWithInteger:self.itemType]];
  }
  if (self.hasStaticDataId) {
    [output appendFormat:@"%@%@: %@\n", indent, @"staticDataId", [NSNumber numberWithInteger:self.staticDataId]];
  }
  if (self.hasAmount) {
    [output appendFormat:@"%@%@: %@\n", indent, @"amount", [NSNumber numberWithInteger:self.amount]];
  }
  if (self.hasSecretGiftChance) {
    [output appendFormat:@"%@%@: %@\n", indent, @"secretGiftChance", [NSNumber numberWithFloat:self.secretGiftChance]];
  }
  if (self.hasAlwaysDisplayToUser) {
    [output appendFormat:@"%@%@: %@\n", indent, @"alwaysDisplayToUser", [NSNumber numberWithBool:self.alwaysDisplayToUser]];
  }
  if (self.hasGameActionType) {
    [output appendFormat:@"%@%@: %@\n", indent, @"gameActionType", [NSNumber numberWithInteger:self.gameActionType]];
  }
  if (self.hasShortName) {
    [output appendFormat:@"%@%@: %@\n", indent, @"shortName", self.shortName];
  }
  if (self.hasQuality) {
    [output appendFormat:@"%@%@: %@\n", indent, @"quality", [NSNumber numberWithInteger:self.quality]];
  }
  [self.unknownFields writeDescriptionTo:output withIndent:indent];
}
- (BOOL) isEqual:(id)other {
  if (other == self) {
    return YES;
  }
  if (![other isKindOfClass:[ItemProto class]]) {
    return NO;
  }
  ItemProto *otherMessage = other;
  return
      self.hasItemId == otherMessage.hasItemId &&
      (!self.hasItemId || self.itemId == otherMessage.itemId) &&
      self.hasName == otherMessage.hasName &&
      (!self.hasName || [self.name isEqual:otherMessage.name]) &&
      self.hasImgName == otherMessage.hasImgName &&
      (!self.hasImgName || [self.imgName isEqual:otherMessage.imgName]) &&
      self.hasItemType == otherMessage.hasItemType &&
      (!self.hasItemType || self.itemType == otherMessage.itemType) &&
      self.hasStaticDataId == otherMessage.hasStaticDataId &&
      (!self.hasStaticDataId || self.staticDataId == otherMessage.staticDataId) &&
      self.hasAmount == otherMessage.hasAmount &&
      (!self.hasAmount || self.amount == otherMessage.amount) &&
      self.hasSecretGiftChance == otherMessage.hasSecretGiftChance &&
      (!self.hasSecretGiftChance || self.secretGiftChance == otherMessage.secretGiftChance) &&
      self.hasAlwaysDisplayToUser == otherMessage.hasAlwaysDisplayToUser &&
      (!self.hasAlwaysDisplayToUser || self.alwaysDisplayToUser == otherMessage.alwaysDisplayToUser) &&
      self.hasGameActionType == otherMessage.hasGameActionType &&
      (!self.hasGameActionType || self.gameActionType == otherMessage.gameActionType) &&
      self.hasShortName == otherMessage.hasShortName &&
      (!self.hasShortName || [self.shortName isEqual:otherMessage.shortName]) &&
      self.hasQuality == otherMessage.hasQuality &&
      (!self.hasQuality || self.quality == otherMessage.quality) &&
      (self.unknownFields == otherMessage.unknownFields || (self.unknownFields != nil && [self.unknownFields isEqual:otherMessage.unknownFields]));
}
- (NSUInteger) hash {
  __block NSUInteger hashCode = 7;
  if (self.hasItemId) {
    hashCode = hashCode * 31 + [[NSNumber numberWithInteger:self.itemId] hash];
  }
  if (self.hasName) {
    hashCode = hashCode * 31 + [self.name hash];
  }
  if (self.hasImgName) {
    hashCode = hashCode * 31 + [self.imgName hash];
  }
  if (self.hasItemType) {
    hashCode = hashCode * 31 + self.itemType;
  }
  if (self.hasStaticDataId) {
    hashCode = hashCode * 31 + [[NSNumber numberWithInteger:self.staticDataId] hash];
  }
  if (self.hasAmount) {
    hashCode = hashCode * 31 + [[NSNumber numberWithInteger:self.amount] hash];
  }
  if (self.hasSecretGiftChance) {
    hashCode = hashCode * 31 + [[NSNumber numberWithFloat:self.secretGiftChance] hash];
  }
  if (self.hasAlwaysDisplayToUser) {
    hashCode = hashCode * 31 + [[NSNumber numberWithBool:self.alwaysDisplayToUser] hash];
  }
  if (self.hasGameActionType) {
    hashCode = hashCode * 31 + self.gameActionType;
  }
  if (self.hasShortName) {
    hashCode = hashCode * 31 + [self.shortName hash];
  }
  if (self.hasQuality) {
    hashCode = hashCode * 31 + self.quality;
  }
  hashCode = hashCode * 31 + [self.unknownFields hash];
  return hashCode;
}
@end

@interface ItemProto_Builder()
@property (strong) ItemProto* result;
@end

@implementation ItemProto_Builder
@synthesize result;
- (id) init {
  if ((self = [super init])) {
    self.result = [[ItemProto alloc] init];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return result;
}
- (ItemProto_Builder*) clear {
  self.result = [[ItemProto alloc] init];
  return self;
}
- (ItemProto_Builder*) clone {
  return [ItemProto builderWithPrototype:result];
}
- (ItemProto*) defaultInstance {
  return [ItemProto defaultInstance];
}
- (ItemProto*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (ItemProto*) buildPartial {
  ItemProto* returnMe = result;
  self.result = nil;
  return returnMe;
}
- (ItemProto_Builder*) mergeFrom:(ItemProto*) other {
  if (other == [ItemProto defaultInstance]) {
    return self;
  }
  if (other.hasItemId) {
    [self setItemId:other.itemId];
  }
  if (other.hasName) {
    [self setName:other.name];
  }
  if (other.hasImgName) {
    [self setImgName:other.imgName];
  }
  if (other.hasItemType) {
    [self setItemType:other.itemType];
  }
  if (other.hasStaticDataId) {
    [self setStaticDataId:other.staticDataId];
  }
  if (other.hasAmount) {
    [self setAmount:other.amount];
  }
  if (other.hasSecretGiftChance) {
    [self setSecretGiftChance:other.secretGiftChance];
  }
  if (other.hasAlwaysDisplayToUser) {
    [self setAlwaysDisplayToUser:other.alwaysDisplayToUser];
  }
  if (other.hasGameActionType) {
    [self setGameActionType:other.gameActionType];
  }
  if (other.hasShortName) {
    [self setShortName:other.shortName];
  }
  if (other.hasQuality) {
    [self setQuality:other.quality];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (ItemProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (ItemProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSetBuilder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    SInt32 tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 8: {
        [self setItemId:[input readInt32]];
        break;
      }
      case 18: {
        [self setName:[input readString]];
        break;
      }
      case 26: {
        [self setImgName:[input readString]];
        break;
      }
      case 32: {
        ItemType value = (ItemType)[input readEnum];
        if (ItemTypeIsValidValue(value)) {
          [self setItemType:value];
        } else {
          [unknownFields mergeVarintField:4 value:value];
        }
        break;
      }
      case 40: {
        [self setStaticDataId:[input readInt32]];
        break;
      }
      case 48: {
        [self setAmount:[input readInt32]];
        break;
      }
      case 61: {
        [self setSecretGiftChance:[input readFloat]];
        break;
      }
      case 64: {
        [self setAlwaysDisplayToUser:[input readBool]];
        break;
      }
      case 72: {
        GameActionType value = (GameActionType)[input readEnum];
        if (GameActionTypeIsValidValue(value)) {
          [self setGameActionType:value];
        } else {
          [unknownFields mergeVarintField:9 value:value];
        }
        break;
      }
      case 82: {
        [self setShortName:[input readString]];
        break;
      }
      case 88: {
        Quality value = (Quality)[input readEnum];
        if (QualityIsValidValue(value)) {
          [self setQuality:value];
        } else {
          [unknownFields mergeVarintField:11 value:value];
        }
        break;
      }
    }
  }
}
- (BOOL) hasItemId {
  return result.hasItemId;
}
- (int32_t) itemId {
  return result.itemId;
}
- (ItemProto_Builder*) setItemId:(int32_t) value {
  result.hasItemId = YES;
  result.itemId = value;
  return self;
}
- (ItemProto_Builder*) clearItemId {
  result.hasItemId = NO;
  result.itemId = 0;
  return self;
}
- (BOOL) hasName {
  return result.hasName;
}
- (NSString*) name {
  return result.name;
}
- (ItemProto_Builder*) setName:(NSString*) value {
  result.hasName = YES;
  result.name = value;
  return self;
}
- (ItemProto_Builder*) clearName {
  result.hasName = NO;
  result.name = @"";
  return self;
}
- (BOOL) hasImgName {
  return result.hasImgName;
}
- (NSString*) imgName {
  return result.imgName;
}
- (ItemProto_Builder*) setImgName:(NSString*) value {
  result.hasImgName = YES;
  result.imgName = value;
  return self;
}
- (ItemProto_Builder*) clearImgName {
  result.hasImgName = NO;
  result.imgName = @"";
  return self;
}
- (BOOL) hasItemType {
  return result.hasItemType;
}
- (ItemType) itemType {
  return result.itemType;
}
- (ItemProto_Builder*) setItemType:(ItemType) value {
  result.hasItemType = YES;
  result.itemType = value;
  return self;
}
- (ItemProto_Builder*) clearItemTypeList {
  result.hasItemType = NO;
  result.itemType = ItemTypeBoosterPack;
  return self;
}
- (BOOL) hasStaticDataId {
  return result.hasStaticDataId;
}
- (int32_t) staticDataId {
  return result.staticDataId;
}
- (ItemProto_Builder*) setStaticDataId:(int32_t) value {
  result.hasStaticDataId = YES;
  result.staticDataId = value;
  return self;
}
- (ItemProto_Builder*) clearStaticDataId {
  result.hasStaticDataId = NO;
  result.staticDataId = 0;
  return self;
}
- (BOOL) hasAmount {
  return result.hasAmount;
}
- (int32_t) amount {
  return result.amount;
}
- (ItemProto_Builder*) setAmount:(int32_t) value {
  result.hasAmount = YES;
  result.amount = value;
  return self;
}
- (ItemProto_Builder*) clearAmount {
  result.hasAmount = NO;
  result.amount = 0;
  return self;
}
- (BOOL) hasSecretGiftChance {
  return result.hasSecretGiftChance;
}
- (Float32) secretGiftChance {
  return result.secretGiftChance;
}
- (ItemProto_Builder*) setSecretGiftChance:(Float32) value {
  result.hasSecretGiftChance = YES;
  result.secretGiftChance = value;
  return self;
}
- (ItemProto_Builder*) clearSecretGiftChance {
  result.hasSecretGiftChance = NO;
  result.secretGiftChance = 0;
  return self;
}
- (BOOL) hasAlwaysDisplayToUser {
  return result.hasAlwaysDisplayToUser;
}
- (BOOL) alwaysDisplayToUser {
  return result.alwaysDisplayToUser;
}
- (ItemProto_Builder*) setAlwaysDisplayToUser:(BOOL) value {
  result.hasAlwaysDisplayToUser = YES;
  result.alwaysDisplayToUser = value;
  return self;
}
- (ItemProto_Builder*) clearAlwaysDisplayToUser {
  result.hasAlwaysDisplayToUser = NO;
  result.alwaysDisplayToUser = NO;
  return self;
}
- (BOOL) hasGameActionType {
  return result.hasGameActionType;
}
- (GameActionType) gameActionType {
  return result.gameActionType;
}
- (ItemProto_Builder*) setGameActionType:(GameActionType) value {
  result.hasGameActionType = YES;
  result.gameActionType = value;
  return self;
}
- (ItemProto_Builder*) clearGameActionTypeList {
  result.hasGameActionType = NO;
  result.gameActionType = GameActionTypeNoHelp;
  return self;
}
- (BOOL) hasShortName {
  return result.hasShortName;
}
- (NSString*) shortName {
  return result.shortName;
}
- (ItemProto_Builder*) setShortName:(NSString*) value {
  result.hasShortName = YES;
  result.shortName = value;
  return self;
}
- (ItemProto_Builder*) clearShortName {
  result.hasShortName = NO;
  result.shortName = @"";
  return self;
}
- (BOOL) hasQuality {
  return result.hasQuality;
}
- (Quality) quality {
  return result.quality;
}
- (ItemProto_Builder*) setQuality:(Quality) value {
  result.hasQuality = YES;
  result.quality = value;
  return self;
}
- (ItemProto_Builder*) clearQualityList {
  result.hasQuality = NO;
  result.quality = QualityNoQuality;
  return self;
}
@end

@interface UserItemUsageProto ()
@property (strong) NSString* usageUuid;
@property (strong) NSString* userUuid;
@property int32_t itemId;
@property int64_t timeOfEntry;
@property (strong) NSString* userDataUuid;
@property GameActionType actionType;
@end

@implementation UserItemUsageProto

- (BOOL) hasUsageUuid {
  return !!hasUsageUuid_;
}
- (void) setHasUsageUuid:(BOOL) value_ {
  hasUsageUuid_ = !!value_;
}
@synthesize usageUuid;
- (BOOL) hasUserUuid {
  return !!hasUserUuid_;
}
- (void) setHasUserUuid:(BOOL) value_ {
  hasUserUuid_ = !!value_;
}
@synthesize userUuid;
- (BOOL) hasItemId {
  return !!hasItemId_;
}
- (void) setHasItemId:(BOOL) value_ {
  hasItemId_ = !!value_;
}
@synthesize itemId;
- (BOOL) hasTimeOfEntry {
  return !!hasTimeOfEntry_;
}
- (void) setHasTimeOfEntry:(BOOL) value_ {
  hasTimeOfEntry_ = !!value_;
}
@synthesize timeOfEntry;
- (BOOL) hasUserDataUuid {
  return !!hasUserDataUuid_;
}
- (void) setHasUserDataUuid:(BOOL) value_ {
  hasUserDataUuid_ = !!value_;
}
@synthesize userDataUuid;
- (BOOL) hasActionType {
  return !!hasActionType_;
}
- (void) setHasActionType:(BOOL) value_ {
  hasActionType_ = !!value_;
}
@synthesize actionType;
- (id) init {
  if ((self = [super init])) {
    self.usageUuid = @"";
    self.userUuid = @"";
    self.itemId = 0;
    self.timeOfEntry = 0L;
    self.userDataUuid = @"";
    self.actionType = GameActionTypeNoHelp;
  }
  return self;
}
static UserItemUsageProto* defaultUserItemUsageProtoInstance = nil;
+ (void) initialize {
  if (self == [UserItemUsageProto class]) {
    defaultUserItemUsageProtoInstance = [[UserItemUsageProto alloc] init];
  }
}
+ (UserItemUsageProto*) defaultInstance {
  return defaultUserItemUsageProtoInstance;
}
- (UserItemUsageProto*) defaultInstance {
  return defaultUserItemUsageProtoInstance;
}
- (BOOL) isInitialized {
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasUsageUuid) {
    [output writeString:1 value:self.usageUuid];
  }
  if (self.hasUserUuid) {
    [output writeString:2 value:self.userUuid];
  }
  if (self.hasItemId) {
    [output writeInt32:3 value:self.itemId];
  }
  if (self.hasTimeOfEntry) {
    [output writeInt64:4 value:self.timeOfEntry];
  }
  if (self.hasUserDataUuid) {
    [output writeString:5 value:self.userDataUuid];
  }
  if (self.hasActionType) {
    [output writeEnum:6 value:self.actionType];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (SInt32) serializedSize {
  __block SInt32 size_ = memoizedSerializedSize;
  if (size_ != -1) {
    return size_;
  }

  size_ = 0;
  if (self.hasUsageUuid) {
    size_ += computeStringSize(1, self.usageUuid);
  }
  if (self.hasUserUuid) {
    size_ += computeStringSize(2, self.userUuid);
  }
  if (self.hasItemId) {
    size_ += computeInt32Size(3, self.itemId);
  }
  if (self.hasTimeOfEntry) {
    size_ += computeInt64Size(4, self.timeOfEntry);
  }
  if (self.hasUserDataUuid) {
    size_ += computeStringSize(5, self.userDataUuid);
  }
  if (self.hasActionType) {
    size_ += computeEnumSize(6, self.actionType);
  }
  size_ += self.unknownFields.serializedSize;
  memoizedSerializedSize = size_;
  return size_;
}
+ (UserItemUsageProto*) parseFromData:(NSData*) data {
  return (UserItemUsageProto*)[[[UserItemUsageProto builder] mergeFromData:data] build];
}
+ (UserItemUsageProto*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (UserItemUsageProto*)[[[UserItemUsageProto builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (UserItemUsageProto*) parseFromInputStream:(NSInputStream*) input {
  return (UserItemUsageProto*)[[[UserItemUsageProto builder] mergeFromInputStream:input] build];
}
+ (UserItemUsageProto*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (UserItemUsageProto*)[[[UserItemUsageProto builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (UserItemUsageProto*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (UserItemUsageProto*)[[[UserItemUsageProto builder] mergeFromCodedInputStream:input] build];
}
+ (UserItemUsageProto*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (UserItemUsageProto*)[[[UserItemUsageProto builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (UserItemUsageProto_Builder*) builder {
  return [[UserItemUsageProto_Builder alloc] init];
}
+ (UserItemUsageProto_Builder*) builderWithPrototype:(UserItemUsageProto*) prototype {
  return [[UserItemUsageProto builder] mergeFrom:prototype];
}
- (UserItemUsageProto_Builder*) builder {
  return [UserItemUsageProto builder];
}
- (UserItemUsageProto_Builder*) toBuilder {
  return [UserItemUsageProto builderWithPrototype:self];
}
- (void) writeDescriptionTo:(NSMutableString*) output withIndent:(NSString*) indent {
  if (self.hasUsageUuid) {
    [output appendFormat:@"%@%@: %@\n", indent, @"usageUuid", self.usageUuid];
  }
  if (self.hasUserUuid) {
    [output appendFormat:@"%@%@: %@\n", indent, @"userUuid", self.userUuid];
  }
  if (self.hasItemId) {
    [output appendFormat:@"%@%@: %@\n", indent, @"itemId", [NSNumber numberWithInteger:self.itemId]];
  }
  if (self.hasTimeOfEntry) {
    [output appendFormat:@"%@%@: %@\n", indent, @"timeOfEntry", [NSNumber numberWithLongLong:self.timeOfEntry]];
  }
  if (self.hasUserDataUuid) {
    [output appendFormat:@"%@%@: %@\n", indent, @"userDataUuid", self.userDataUuid];
  }
  if (self.hasActionType) {
    [output appendFormat:@"%@%@: %@\n", indent, @"actionType", [NSNumber numberWithInteger:self.actionType]];
  }
  [self.unknownFields writeDescriptionTo:output withIndent:indent];
}
- (BOOL) isEqual:(id)other {
  if (other == self) {
    return YES;
  }
  if (![other isKindOfClass:[UserItemUsageProto class]]) {
    return NO;
  }
  UserItemUsageProto *otherMessage = other;
  return
      self.hasUsageUuid == otherMessage.hasUsageUuid &&
      (!self.hasUsageUuid || [self.usageUuid isEqual:otherMessage.usageUuid]) &&
      self.hasUserUuid == otherMessage.hasUserUuid &&
      (!self.hasUserUuid || [self.userUuid isEqual:otherMessage.userUuid]) &&
      self.hasItemId == otherMessage.hasItemId &&
      (!self.hasItemId || self.itemId == otherMessage.itemId) &&
      self.hasTimeOfEntry == otherMessage.hasTimeOfEntry &&
      (!self.hasTimeOfEntry || self.timeOfEntry == otherMessage.timeOfEntry) &&
      self.hasUserDataUuid == otherMessage.hasUserDataUuid &&
      (!self.hasUserDataUuid || [self.userDataUuid isEqual:otherMessage.userDataUuid]) &&
      self.hasActionType == otherMessage.hasActionType &&
      (!self.hasActionType || self.actionType == otherMessage.actionType) &&
      (self.unknownFields == otherMessage.unknownFields || (self.unknownFields != nil && [self.unknownFields isEqual:otherMessage.unknownFields]));
}
- (NSUInteger) hash {
  __block NSUInteger hashCode = 7;
  if (self.hasUsageUuid) {
    hashCode = hashCode * 31 + [self.usageUuid hash];
  }
  if (self.hasUserUuid) {
    hashCode = hashCode * 31 + [self.userUuid hash];
  }
  if (self.hasItemId) {
    hashCode = hashCode * 31 + [[NSNumber numberWithInteger:self.itemId] hash];
  }
  if (self.hasTimeOfEntry) {
    hashCode = hashCode * 31 + [[NSNumber numberWithLongLong:self.timeOfEntry] hash];
  }
  if (self.hasUserDataUuid) {
    hashCode = hashCode * 31 + [self.userDataUuid hash];
  }
  if (self.hasActionType) {
    hashCode = hashCode * 31 + self.actionType;
  }
  hashCode = hashCode * 31 + [self.unknownFields hash];
  return hashCode;
}
@end

@interface UserItemUsageProto_Builder()
@property (strong) UserItemUsageProto* result;
@end

@implementation UserItemUsageProto_Builder
@synthesize result;
- (id) init {
  if ((self = [super init])) {
    self.result = [[UserItemUsageProto alloc] init];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return result;
}
- (UserItemUsageProto_Builder*) clear {
  self.result = [[UserItemUsageProto alloc] init];
  return self;
}
- (UserItemUsageProto_Builder*) clone {
  return [UserItemUsageProto builderWithPrototype:result];
}
- (UserItemUsageProto*) defaultInstance {
  return [UserItemUsageProto defaultInstance];
}
- (UserItemUsageProto*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (UserItemUsageProto*) buildPartial {
  UserItemUsageProto* returnMe = result;
  self.result = nil;
  return returnMe;
}
- (UserItemUsageProto_Builder*) mergeFrom:(UserItemUsageProto*) other {
  if (other == [UserItemUsageProto defaultInstance]) {
    return self;
  }
  if (other.hasUsageUuid) {
    [self setUsageUuid:other.usageUuid];
  }
  if (other.hasUserUuid) {
    [self setUserUuid:other.userUuid];
  }
  if (other.hasItemId) {
    [self setItemId:other.itemId];
  }
  if (other.hasTimeOfEntry) {
    [self setTimeOfEntry:other.timeOfEntry];
  }
  if (other.hasUserDataUuid) {
    [self setUserDataUuid:other.userDataUuid];
  }
  if (other.hasActionType) {
    [self setActionType:other.actionType];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (UserItemUsageProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (UserItemUsageProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSetBuilder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    SInt32 tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 10: {
        [self setUsageUuid:[input readString]];
        break;
      }
      case 18: {
        [self setUserUuid:[input readString]];
        break;
      }
      case 24: {
        [self setItemId:[input readInt32]];
        break;
      }
      case 32: {
        [self setTimeOfEntry:[input readInt64]];
        break;
      }
      case 42: {
        [self setUserDataUuid:[input readString]];
        break;
      }
      case 48: {
        GameActionType value = (GameActionType)[input readEnum];
        if (GameActionTypeIsValidValue(value)) {
          [self setActionType:value];
        } else {
          [unknownFields mergeVarintField:6 value:value];
        }
        break;
      }
    }
  }
}
- (BOOL) hasUsageUuid {
  return result.hasUsageUuid;
}
- (NSString*) usageUuid {
  return result.usageUuid;
}
- (UserItemUsageProto_Builder*) setUsageUuid:(NSString*) value {
  result.hasUsageUuid = YES;
  result.usageUuid = value;
  return self;
}
- (UserItemUsageProto_Builder*) clearUsageUuid {
  result.hasUsageUuid = NO;
  result.usageUuid = @"";
  return self;
}
- (BOOL) hasUserUuid {
  return result.hasUserUuid;
}
- (NSString*) userUuid {
  return result.userUuid;
}
- (UserItemUsageProto_Builder*) setUserUuid:(NSString*) value {
  result.hasUserUuid = YES;
  result.userUuid = value;
  return self;
}
- (UserItemUsageProto_Builder*) clearUserUuid {
  result.hasUserUuid = NO;
  result.userUuid = @"";
  return self;
}
- (BOOL) hasItemId {
  return result.hasItemId;
}
- (int32_t) itemId {
  return result.itemId;
}
- (UserItemUsageProto_Builder*) setItemId:(int32_t) value {
  result.hasItemId = YES;
  result.itemId = value;
  return self;
}
- (UserItemUsageProto_Builder*) clearItemId {
  result.hasItemId = NO;
  result.itemId = 0;
  return self;
}
- (BOOL) hasTimeOfEntry {
  return result.hasTimeOfEntry;
}
- (int64_t) timeOfEntry {
  return result.timeOfEntry;
}
- (UserItemUsageProto_Builder*) setTimeOfEntry:(int64_t) value {
  result.hasTimeOfEntry = YES;
  result.timeOfEntry = value;
  return self;
}
- (UserItemUsageProto_Builder*) clearTimeOfEntry {
  result.hasTimeOfEntry = NO;
  result.timeOfEntry = 0L;
  return self;
}
- (BOOL) hasUserDataUuid {
  return result.hasUserDataUuid;
}
- (NSString*) userDataUuid {
  return result.userDataUuid;
}
- (UserItemUsageProto_Builder*) setUserDataUuid:(NSString*) value {
  result.hasUserDataUuid = YES;
  result.userDataUuid = value;
  return self;
}
- (UserItemUsageProto_Builder*) clearUserDataUuid {
  result.hasUserDataUuid = NO;
  result.userDataUuid = @"";
  return self;
}
- (BOOL) hasActionType {
  return result.hasActionType;
}
- (GameActionType) actionType {
  return result.actionType;
}
- (UserItemUsageProto_Builder*) setActionType:(GameActionType) value {
  result.hasActionType = YES;
  result.actionType = value;
  return self;
}
- (UserItemUsageProto_Builder*) clearActionTypeList {
  result.hasActionType = NO;
  result.actionType = GameActionTypeNoHelp;
  return self;
}
@end

@interface UserItemSecretGiftProto ()
@property (strong) NSString* uisgUuid;
@property (strong) NSString* userUuid;
@property int32_t secsTillCollection;
@property int32_t itemId;
@property int64_t createTime;
@end

@implementation UserItemSecretGiftProto

- (BOOL) hasUisgUuid {
  return !!hasUisgUuid_;
}
- (void) setHasUisgUuid:(BOOL) value_ {
  hasUisgUuid_ = !!value_;
}
@synthesize uisgUuid;
- (BOOL) hasUserUuid {
  return !!hasUserUuid_;
}
- (void) setHasUserUuid:(BOOL) value_ {
  hasUserUuid_ = !!value_;
}
@synthesize userUuid;
- (BOOL) hasSecsTillCollection {
  return !!hasSecsTillCollection_;
}
- (void) setHasSecsTillCollection:(BOOL) value_ {
  hasSecsTillCollection_ = !!value_;
}
@synthesize secsTillCollection;
- (BOOL) hasItemId {
  return !!hasItemId_;
}
- (void) setHasItemId:(BOOL) value_ {
  hasItemId_ = !!value_;
}
@synthesize itemId;
- (BOOL) hasCreateTime {
  return !!hasCreateTime_;
}
- (void) setHasCreateTime:(BOOL) value_ {
  hasCreateTime_ = !!value_;
}
@synthesize createTime;
- (id) init {
  if ((self = [super init])) {
    self.uisgUuid = @"";
    self.userUuid = @"";
    self.secsTillCollection = 0;
    self.itemId = 0;
    self.createTime = 0L;
  }
  return self;
}
static UserItemSecretGiftProto* defaultUserItemSecretGiftProtoInstance = nil;
+ (void) initialize {
  if (self == [UserItemSecretGiftProto class]) {
    defaultUserItemSecretGiftProtoInstance = [[UserItemSecretGiftProto alloc] init];
  }
}
+ (UserItemSecretGiftProto*) defaultInstance {
  return defaultUserItemSecretGiftProtoInstance;
}
- (UserItemSecretGiftProto*) defaultInstance {
  return defaultUserItemSecretGiftProtoInstance;
}
- (BOOL) isInitialized {
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasUisgUuid) {
    [output writeString:1 value:self.uisgUuid];
  }
  if (self.hasUserUuid) {
    [output writeString:2 value:self.userUuid];
  }
  if (self.hasSecsTillCollection) {
    [output writeInt32:3 value:self.secsTillCollection];
  }
  if (self.hasItemId) {
    [output writeInt32:4 value:self.itemId];
  }
  if (self.hasCreateTime) {
    [output writeInt64:5 value:self.createTime];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (SInt32) serializedSize {
  __block SInt32 size_ = memoizedSerializedSize;
  if (size_ != -1) {
    return size_;
  }

  size_ = 0;
  if (self.hasUisgUuid) {
    size_ += computeStringSize(1, self.uisgUuid);
  }
  if (self.hasUserUuid) {
    size_ += computeStringSize(2, self.userUuid);
  }
  if (self.hasSecsTillCollection) {
    size_ += computeInt32Size(3, self.secsTillCollection);
  }
  if (self.hasItemId) {
    size_ += computeInt32Size(4, self.itemId);
  }
  if (self.hasCreateTime) {
    size_ += computeInt64Size(5, self.createTime);
  }
  size_ += self.unknownFields.serializedSize;
  memoizedSerializedSize = size_;
  return size_;
}
+ (UserItemSecretGiftProto*) parseFromData:(NSData*) data {
  return (UserItemSecretGiftProto*)[[[UserItemSecretGiftProto builder] mergeFromData:data] build];
}
+ (UserItemSecretGiftProto*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (UserItemSecretGiftProto*)[[[UserItemSecretGiftProto builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (UserItemSecretGiftProto*) parseFromInputStream:(NSInputStream*) input {
  return (UserItemSecretGiftProto*)[[[UserItemSecretGiftProto builder] mergeFromInputStream:input] build];
}
+ (UserItemSecretGiftProto*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (UserItemSecretGiftProto*)[[[UserItemSecretGiftProto builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (UserItemSecretGiftProto*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (UserItemSecretGiftProto*)[[[UserItemSecretGiftProto builder] mergeFromCodedInputStream:input] build];
}
+ (UserItemSecretGiftProto*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (UserItemSecretGiftProto*)[[[UserItemSecretGiftProto builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (UserItemSecretGiftProto_Builder*) builder {
  return [[UserItemSecretGiftProto_Builder alloc] init];
}
+ (UserItemSecretGiftProto_Builder*) builderWithPrototype:(UserItemSecretGiftProto*) prototype {
  return [[UserItemSecretGiftProto builder] mergeFrom:prototype];
}
- (UserItemSecretGiftProto_Builder*) builder {
  return [UserItemSecretGiftProto builder];
}
- (UserItemSecretGiftProto_Builder*) toBuilder {
  return [UserItemSecretGiftProto builderWithPrototype:self];
}
- (void) writeDescriptionTo:(NSMutableString*) output withIndent:(NSString*) indent {
  if (self.hasUisgUuid) {
    [output appendFormat:@"%@%@: %@\n", indent, @"uisgUuid", self.uisgUuid];
  }
  if (self.hasUserUuid) {
    [output appendFormat:@"%@%@: %@\n", indent, @"userUuid", self.userUuid];
  }
  if (self.hasSecsTillCollection) {
    [output appendFormat:@"%@%@: %@\n", indent, @"secsTillCollection", [NSNumber numberWithInteger:self.secsTillCollection]];
  }
  if (self.hasItemId) {
    [output appendFormat:@"%@%@: %@\n", indent, @"itemId", [NSNumber numberWithInteger:self.itemId]];
  }
  if (self.hasCreateTime) {
    [output appendFormat:@"%@%@: %@\n", indent, @"createTime", [NSNumber numberWithLongLong:self.createTime]];
  }
  [self.unknownFields writeDescriptionTo:output withIndent:indent];
}
- (BOOL) isEqual:(id)other {
  if (other == self) {
    return YES;
  }
  if (![other isKindOfClass:[UserItemSecretGiftProto class]]) {
    return NO;
  }
  UserItemSecretGiftProto *otherMessage = other;
  return
      self.hasUisgUuid == otherMessage.hasUisgUuid &&
      (!self.hasUisgUuid || [self.uisgUuid isEqual:otherMessage.uisgUuid]) &&
      self.hasUserUuid == otherMessage.hasUserUuid &&
      (!self.hasUserUuid || [self.userUuid isEqual:otherMessage.userUuid]) &&
      self.hasSecsTillCollection == otherMessage.hasSecsTillCollection &&
      (!self.hasSecsTillCollection || self.secsTillCollection == otherMessage.secsTillCollection) &&
      self.hasItemId == otherMessage.hasItemId &&
      (!self.hasItemId || self.itemId == otherMessage.itemId) &&
      self.hasCreateTime == otherMessage.hasCreateTime &&
      (!self.hasCreateTime || self.createTime == otherMessage.createTime) &&
      (self.unknownFields == otherMessage.unknownFields || (self.unknownFields != nil && [self.unknownFields isEqual:otherMessage.unknownFields]));
}
- (NSUInteger) hash {
  __block NSUInteger hashCode = 7;
  if (self.hasUisgUuid) {
    hashCode = hashCode * 31 + [self.uisgUuid hash];
  }
  if (self.hasUserUuid) {
    hashCode = hashCode * 31 + [self.userUuid hash];
  }
  if (self.hasSecsTillCollection) {
    hashCode = hashCode * 31 + [[NSNumber numberWithInteger:self.secsTillCollection] hash];
  }
  if (self.hasItemId) {
    hashCode = hashCode * 31 + [[NSNumber numberWithInteger:self.itemId] hash];
  }
  if (self.hasCreateTime) {
    hashCode = hashCode * 31 + [[NSNumber numberWithLongLong:self.createTime] hash];
  }
  hashCode = hashCode * 31 + [self.unknownFields hash];
  return hashCode;
}
@end

@interface UserItemSecretGiftProto_Builder()
@property (strong) UserItemSecretGiftProto* result;
@end

@implementation UserItemSecretGiftProto_Builder
@synthesize result;
- (id) init {
  if ((self = [super init])) {
    self.result = [[UserItemSecretGiftProto alloc] init];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return result;
}
- (UserItemSecretGiftProto_Builder*) clear {
  self.result = [[UserItemSecretGiftProto alloc] init];
  return self;
}
- (UserItemSecretGiftProto_Builder*) clone {
  return [UserItemSecretGiftProto builderWithPrototype:result];
}
- (UserItemSecretGiftProto*) defaultInstance {
  return [UserItemSecretGiftProto defaultInstance];
}
- (UserItemSecretGiftProto*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (UserItemSecretGiftProto*) buildPartial {
  UserItemSecretGiftProto* returnMe = result;
  self.result = nil;
  return returnMe;
}
- (UserItemSecretGiftProto_Builder*) mergeFrom:(UserItemSecretGiftProto*) other {
  if (other == [UserItemSecretGiftProto defaultInstance]) {
    return self;
  }
  if (other.hasUisgUuid) {
    [self setUisgUuid:other.uisgUuid];
  }
  if (other.hasUserUuid) {
    [self setUserUuid:other.userUuid];
  }
  if (other.hasSecsTillCollection) {
    [self setSecsTillCollection:other.secsTillCollection];
  }
  if (other.hasItemId) {
    [self setItemId:other.itemId];
  }
  if (other.hasCreateTime) {
    [self setCreateTime:other.createTime];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (UserItemSecretGiftProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (UserItemSecretGiftProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSetBuilder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    SInt32 tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 10: {
        [self setUisgUuid:[input readString]];
        break;
      }
      case 18: {
        [self setUserUuid:[input readString]];
        break;
      }
      case 24: {
        [self setSecsTillCollection:[input readInt32]];
        break;
      }
      case 32: {
        [self setItemId:[input readInt32]];
        break;
      }
      case 40: {
        [self setCreateTime:[input readInt64]];
        break;
      }
    }
  }
}
- (BOOL) hasUisgUuid {
  return result.hasUisgUuid;
}
- (NSString*) uisgUuid {
  return result.uisgUuid;
}
- (UserItemSecretGiftProto_Builder*) setUisgUuid:(NSString*) value {
  result.hasUisgUuid = YES;
  result.uisgUuid = value;
  return self;
}
- (UserItemSecretGiftProto_Builder*) clearUisgUuid {
  result.hasUisgUuid = NO;
  result.uisgUuid = @"";
  return self;
}
- (BOOL) hasUserUuid {
  return result.hasUserUuid;
}
- (NSString*) userUuid {
  return result.userUuid;
}
- (UserItemSecretGiftProto_Builder*) setUserUuid:(NSString*) value {
  result.hasUserUuid = YES;
  result.userUuid = value;
  return self;
}
- (UserItemSecretGiftProto_Builder*) clearUserUuid {
  result.hasUserUuid = NO;
  result.userUuid = @"";
  return self;
}
- (BOOL) hasSecsTillCollection {
  return result.hasSecsTillCollection;
}
- (int32_t) secsTillCollection {
  return result.secsTillCollection;
}
- (UserItemSecretGiftProto_Builder*) setSecsTillCollection:(int32_t) value {
  result.hasSecsTillCollection = YES;
  result.secsTillCollection = value;
  return self;
}
- (UserItemSecretGiftProto_Builder*) clearSecsTillCollection {
  result.hasSecsTillCollection = NO;
  result.secsTillCollection = 0;
  return self;
}
- (BOOL) hasItemId {
  return result.hasItemId;
}
- (int32_t) itemId {
  return result.itemId;
}
- (UserItemSecretGiftProto_Builder*) setItemId:(int32_t) value {
  result.hasItemId = YES;
  result.itemId = value;
  return self;
}
- (UserItemSecretGiftProto_Builder*) clearItemId {
  result.hasItemId = NO;
  result.itemId = 0;
  return self;
}
- (BOOL) hasCreateTime {
  return result.hasCreateTime;
}
- (int64_t) createTime {
  return result.createTime;
}
- (UserItemSecretGiftProto_Builder*) setCreateTime:(int64_t) value {
  result.hasCreateTime = YES;
  result.createTime = value;
  return self;
}
- (UserItemSecretGiftProto_Builder*) clearCreateTime {
  result.hasCreateTime = NO;
  result.createTime = 0L;
  return self;
}
@end

@interface ItemGemPriceProto ()
@property int32_t itemId;
@property int32_t gemPrice;
@end

@implementation ItemGemPriceProto

- (BOOL) hasItemId {
  return !!hasItemId_;
}
- (void) setHasItemId:(BOOL) value_ {
  hasItemId_ = !!value_;
}
@synthesize itemId;
- (BOOL) hasGemPrice {
  return !!hasGemPrice_;
}
- (void) setHasGemPrice:(BOOL) value_ {
  hasGemPrice_ = !!value_;
}
@synthesize gemPrice;
- (id) init {
  if ((self = [super init])) {
    self.itemId = 0;
    self.gemPrice = 0;
  }
  return self;
}
static ItemGemPriceProto* defaultItemGemPriceProtoInstance = nil;
+ (void) initialize {
  if (self == [ItemGemPriceProto class]) {
    defaultItemGemPriceProtoInstance = [[ItemGemPriceProto alloc] init];
  }
}
+ (ItemGemPriceProto*) defaultInstance {
  return defaultItemGemPriceProtoInstance;
}
- (ItemGemPriceProto*) defaultInstance {
  return defaultItemGemPriceProtoInstance;
}
- (BOOL) isInitialized {
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasItemId) {
    [output writeInt32:1 value:self.itemId];
  }
  if (self.hasGemPrice) {
    [output writeInt32:2 value:self.gemPrice];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (SInt32) serializedSize {
  __block SInt32 size_ = memoizedSerializedSize;
  if (size_ != -1) {
    return size_;
  }

  size_ = 0;
  if (self.hasItemId) {
    size_ += computeInt32Size(1, self.itemId);
  }
  if (self.hasGemPrice) {
    size_ += computeInt32Size(2, self.gemPrice);
  }
  size_ += self.unknownFields.serializedSize;
  memoizedSerializedSize = size_;
  return size_;
}
+ (ItemGemPriceProto*) parseFromData:(NSData*) data {
  return (ItemGemPriceProto*)[[[ItemGemPriceProto builder] mergeFromData:data] build];
}
+ (ItemGemPriceProto*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (ItemGemPriceProto*)[[[ItemGemPriceProto builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (ItemGemPriceProto*) parseFromInputStream:(NSInputStream*) input {
  return (ItemGemPriceProto*)[[[ItemGemPriceProto builder] mergeFromInputStream:input] build];
}
+ (ItemGemPriceProto*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (ItemGemPriceProto*)[[[ItemGemPriceProto builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (ItemGemPriceProto*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (ItemGemPriceProto*)[[[ItemGemPriceProto builder] mergeFromCodedInputStream:input] build];
}
+ (ItemGemPriceProto*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (ItemGemPriceProto*)[[[ItemGemPriceProto builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (ItemGemPriceProto_Builder*) builder {
  return [[ItemGemPriceProto_Builder alloc] init];
}
+ (ItemGemPriceProto_Builder*) builderWithPrototype:(ItemGemPriceProto*) prototype {
  return [[ItemGemPriceProto builder] mergeFrom:prototype];
}
- (ItemGemPriceProto_Builder*) builder {
  return [ItemGemPriceProto builder];
}
- (ItemGemPriceProto_Builder*) toBuilder {
  return [ItemGemPriceProto builderWithPrototype:self];
}
- (void) writeDescriptionTo:(NSMutableString*) output withIndent:(NSString*) indent {
  if (self.hasItemId) {
    [output appendFormat:@"%@%@: %@\n", indent, @"itemId", [NSNumber numberWithInteger:self.itemId]];
  }
  if (self.hasGemPrice) {
    [output appendFormat:@"%@%@: %@\n", indent, @"gemPrice", [NSNumber numberWithInteger:self.gemPrice]];
  }
  [self.unknownFields writeDescriptionTo:output withIndent:indent];
}
- (BOOL) isEqual:(id)other {
  if (other == self) {
    return YES;
  }
  if (![other isKindOfClass:[ItemGemPriceProto class]]) {
    return NO;
  }
  ItemGemPriceProto *otherMessage = other;
  return
      self.hasItemId == otherMessage.hasItemId &&
      (!self.hasItemId || self.itemId == otherMessage.itemId) &&
      self.hasGemPrice == otherMessage.hasGemPrice &&
      (!self.hasGemPrice || self.gemPrice == otherMessage.gemPrice) &&
      (self.unknownFields == otherMessage.unknownFields || (self.unknownFields != nil && [self.unknownFields isEqual:otherMessage.unknownFields]));
}
- (NSUInteger) hash {
  __block NSUInteger hashCode = 7;
  if (self.hasItemId) {
    hashCode = hashCode * 31 + [[NSNumber numberWithInteger:self.itemId] hash];
  }
  if (self.hasGemPrice) {
    hashCode = hashCode * 31 + [[NSNumber numberWithInteger:self.gemPrice] hash];
  }
  hashCode = hashCode * 31 + [self.unknownFields hash];
  return hashCode;
}
@end

@interface ItemGemPriceProto_Builder()
@property (strong) ItemGemPriceProto* result;
@end

@implementation ItemGemPriceProto_Builder
@synthesize result;
- (id) init {
  if ((self = [super init])) {
    self.result = [[ItemGemPriceProto alloc] init];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return result;
}
- (ItemGemPriceProto_Builder*) clear {
  self.result = [[ItemGemPriceProto alloc] init];
  return self;
}
- (ItemGemPriceProto_Builder*) clone {
  return [ItemGemPriceProto builderWithPrototype:result];
}
- (ItemGemPriceProto*) defaultInstance {
  return [ItemGemPriceProto defaultInstance];
}
- (ItemGemPriceProto*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (ItemGemPriceProto*) buildPartial {
  ItemGemPriceProto* returnMe = result;
  self.result = nil;
  return returnMe;
}
- (ItemGemPriceProto_Builder*) mergeFrom:(ItemGemPriceProto*) other {
  if (other == [ItemGemPriceProto defaultInstance]) {
    return self;
  }
  if (other.hasItemId) {
    [self setItemId:other.itemId];
  }
  if (other.hasGemPrice) {
    [self setGemPrice:other.gemPrice];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (ItemGemPriceProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (ItemGemPriceProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSetBuilder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    SInt32 tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 8: {
        [self setItemId:[input readInt32]];
        break;
      }
      case 16: {
        [self setGemPrice:[input readInt32]];
        break;
      }
    }
  }
}
- (BOOL) hasItemId {
  return result.hasItemId;
}
- (int32_t) itemId {
  return result.itemId;
}
- (ItemGemPriceProto_Builder*) setItemId:(int32_t) value {
  result.hasItemId = YES;
  result.itemId = value;
  return self;
}
- (ItemGemPriceProto_Builder*) clearItemId {
  result.hasItemId = NO;
  result.itemId = 0;
  return self;
}
- (BOOL) hasGemPrice {
  return result.hasGemPrice;
}
- (int32_t) gemPrice {
  return result.gemPrice;
}
- (ItemGemPriceProto_Builder*) setGemPrice:(int32_t) value {
  result.hasGemPrice = YES;
  result.gemPrice = value;
  return self;
}
- (ItemGemPriceProto_Builder*) clearGemPrice {
  result.hasGemPrice = NO;
  result.gemPrice = 0;
  return self;
}
@end


// @@protoc_insertion_point(global_scope)
