// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "BoosterPackStuff.pb.h"

@implementation BoosterPackStuffRoot
static PBExtensionRegistry* extensionRegistry = nil;
+ (PBExtensionRegistry*) extensionRegistry {
  return extensionRegistry;
}

+ (void) initialize {
  if (self == [BoosterPackStuffRoot class]) {
    PBMutableExtensionRegistry* registry = [PBMutableExtensionRegistry registry];
    [self registerAllExtensions:registry];
    [UserRoot registerAllExtensions:registry];
    extensionRegistry = [registry retain];
  }
}
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry {
}
@end

@interface RareBoosterPurchaseProto ()
@property (retain) MinimumUserProto* user;
@property (retain) BoosterPackProto* booster;
@property int64_t timeOfPurchase;
@property int32_t monsterId;
@end

@implementation RareBoosterPurchaseProto

- (BOOL) hasUser {
  return !!hasUser_;
}
- (void) setHasUser:(BOOL) value {
  hasUser_ = !!value;
}
@synthesize user;
- (BOOL) hasBooster {
  return !!hasBooster_;
}
- (void) setHasBooster:(BOOL) value {
  hasBooster_ = !!value;
}
@synthesize booster;
- (BOOL) hasTimeOfPurchase {
  return !!hasTimeOfPurchase_;
}
- (void) setHasTimeOfPurchase:(BOOL) value {
  hasTimeOfPurchase_ = !!value;
}
@synthesize timeOfPurchase;
- (BOOL) hasMonsterId {
  return !!hasMonsterId_;
}
- (void) setHasMonsterId:(BOOL) value {
  hasMonsterId_ = !!value;
}
@synthesize monsterId;
- (void) dealloc {
  self.user = nil;
  self.booster = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.user = [MinimumUserProto defaultInstance];
    self.booster = [BoosterPackProto defaultInstance];
    self.timeOfPurchase = 0L;
    self.monsterId = 0;
  }
  return self;
}
static RareBoosterPurchaseProto* defaultRareBoosterPurchaseProtoInstance = nil;
+ (void) initialize {
  if (self == [RareBoosterPurchaseProto class]) {
    defaultRareBoosterPurchaseProtoInstance = [[RareBoosterPurchaseProto alloc] init];
  }
}
+ (RareBoosterPurchaseProto*) defaultInstance {
  return defaultRareBoosterPurchaseProtoInstance;
}
- (RareBoosterPurchaseProto*) defaultInstance {
  return defaultRareBoosterPurchaseProtoInstance;
}
- (BOOL) isInitialized {
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasUser) {
    [output writeMessage:1 value:self.user];
  }
  if (self.hasBooster) {
    [output writeMessage:2 value:self.booster];
  }
  if (self.hasTimeOfPurchase) {
    [output writeUInt64:3 value:self.timeOfPurchase];
  }
  if (self.hasMonsterId) {
    [output writeInt32:4 value:self.monsterId];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (int32_t) serializedSize {
  int32_t size = memoizedSerializedSize;
  if (size != -1) {
    return size;
  }

  size = 0;
  if (self.hasUser) {
    size += computeMessageSize(1, self.user);
  }
  if (self.hasBooster) {
    size += computeMessageSize(2, self.booster);
  }
  if (self.hasTimeOfPurchase) {
    size += computeUInt64Size(3, self.timeOfPurchase);
  }
  if (self.hasMonsterId) {
    size += computeInt32Size(4, self.monsterId);
  }
  size += self.unknownFields.serializedSize;
  memoizedSerializedSize = size;
  return size;
}
+ (RareBoosterPurchaseProto*) parseFromData:(NSData*) data {
  return (RareBoosterPurchaseProto*)[[[RareBoosterPurchaseProto builder] mergeFromData:data] build];
}
+ (RareBoosterPurchaseProto*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (RareBoosterPurchaseProto*)[[[RareBoosterPurchaseProto builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (RareBoosterPurchaseProto*) parseFromInputStream:(NSInputStream*) input {
  return (RareBoosterPurchaseProto*)[[[RareBoosterPurchaseProto builder] mergeFromInputStream:input] build];
}
+ (RareBoosterPurchaseProto*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (RareBoosterPurchaseProto*)[[[RareBoosterPurchaseProto builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (RareBoosterPurchaseProto*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (RareBoosterPurchaseProto*)[[[RareBoosterPurchaseProto builder] mergeFromCodedInputStream:input] build];
}
+ (RareBoosterPurchaseProto*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (RareBoosterPurchaseProto*)[[[RareBoosterPurchaseProto builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (RareBoosterPurchaseProto_Builder*) builder {
  return [[[RareBoosterPurchaseProto_Builder alloc] init] autorelease];
}
+ (RareBoosterPurchaseProto_Builder*) builderWithPrototype:(RareBoosterPurchaseProto*) prototype {
  return [[RareBoosterPurchaseProto builder] mergeFrom:prototype];
}
- (RareBoosterPurchaseProto_Builder*) builder {
  return [RareBoosterPurchaseProto builder];
}
@end

@interface RareBoosterPurchaseProto_Builder()
@property (retain) RareBoosterPurchaseProto* result;
@end

@implementation RareBoosterPurchaseProto_Builder
@synthesize result;
- (void) dealloc {
  self.result = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.result = [[[RareBoosterPurchaseProto alloc] init] autorelease];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return result;
}
- (RareBoosterPurchaseProto_Builder*) clear {
  self.result = [[[RareBoosterPurchaseProto alloc] init] autorelease];
  return self;
}
- (RareBoosterPurchaseProto_Builder*) clone {
  return [RareBoosterPurchaseProto builderWithPrototype:result];
}
- (RareBoosterPurchaseProto*) defaultInstance {
  return [RareBoosterPurchaseProto defaultInstance];
}
- (RareBoosterPurchaseProto*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (RareBoosterPurchaseProto*) buildPartial {
  RareBoosterPurchaseProto* returnMe = [[result retain] autorelease];
  self.result = nil;
  return returnMe;
}
- (RareBoosterPurchaseProto_Builder*) mergeFrom:(RareBoosterPurchaseProto*) other {
  if (other == [RareBoosterPurchaseProto defaultInstance]) {
    return self;
  }
  if (other.hasUser) {
    [self mergeUser:other.user];
  }
  if (other.hasBooster) {
    [self mergeBooster:other.booster];
  }
  if (other.hasTimeOfPurchase) {
    [self setTimeOfPurchase:other.timeOfPurchase];
  }
  if (other.hasMonsterId) {
    [self setMonsterId:other.monsterId];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (RareBoosterPurchaseProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (RareBoosterPurchaseProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSet_Builder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    int32_t tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 10: {
        MinimumUserProto_Builder* subBuilder = [MinimumUserProto builder];
        if (self.hasUser) {
          [subBuilder mergeFrom:self.user];
        }
        [input readMessage:subBuilder extensionRegistry:extensionRegistry];
        [self setUser:[subBuilder buildPartial]];
        break;
      }
      case 18: {
        BoosterPackProto_Builder* subBuilder = [BoosterPackProto builder];
        if (self.hasBooster) {
          [subBuilder mergeFrom:self.booster];
        }
        [input readMessage:subBuilder extensionRegistry:extensionRegistry];
        [self setBooster:[subBuilder buildPartial]];
        break;
      }
      case 24: {
        [self setTimeOfPurchase:[input readUInt64]];
        break;
      }
      case 32: {
        [self setMonsterId:[input readInt32]];
        break;
      }
    }
  }
}
- (BOOL) hasUser {
  return result.hasUser;
}
- (MinimumUserProto*) user {
  return result.user;
}
- (RareBoosterPurchaseProto_Builder*) setUser:(MinimumUserProto*) value {
  result.hasUser = YES;
  result.user = value;
  return self;
}
- (RareBoosterPurchaseProto_Builder*) setUserBuilder:(MinimumUserProto_Builder*) builderForValue {
  return [self setUser:[builderForValue build]];
}
- (RareBoosterPurchaseProto_Builder*) mergeUser:(MinimumUserProto*) value {
  if (result.hasUser &&
      result.user != [MinimumUserProto defaultInstance]) {
    result.user =
      [[[MinimumUserProto builderWithPrototype:result.user] mergeFrom:value] buildPartial];
  } else {
    result.user = value;
  }
  result.hasUser = YES;
  return self;
}
- (RareBoosterPurchaseProto_Builder*) clearUser {
  result.hasUser = NO;
  result.user = [MinimumUserProto defaultInstance];
  return self;
}
- (BOOL) hasBooster {
  return result.hasBooster;
}
- (BoosterPackProto*) booster {
  return result.booster;
}
- (RareBoosterPurchaseProto_Builder*) setBooster:(BoosterPackProto*) value {
  result.hasBooster = YES;
  result.booster = value;
  return self;
}
- (RareBoosterPurchaseProto_Builder*) setBoosterBuilder:(BoosterPackProto_Builder*) builderForValue {
  return [self setBooster:[builderForValue build]];
}
- (RareBoosterPurchaseProto_Builder*) mergeBooster:(BoosterPackProto*) value {
  if (result.hasBooster &&
      result.booster != [BoosterPackProto defaultInstance]) {
    result.booster =
      [[[BoosterPackProto builderWithPrototype:result.booster] mergeFrom:value] buildPartial];
  } else {
    result.booster = value;
  }
  result.hasBooster = YES;
  return self;
}
- (RareBoosterPurchaseProto_Builder*) clearBooster {
  result.hasBooster = NO;
  result.booster = [BoosterPackProto defaultInstance];
  return self;
}
- (BOOL) hasTimeOfPurchase {
  return result.hasTimeOfPurchase;
}
- (int64_t) timeOfPurchase {
  return result.timeOfPurchase;
}
- (RareBoosterPurchaseProto_Builder*) setTimeOfPurchase:(int64_t) value {
  result.hasTimeOfPurchase = YES;
  result.timeOfPurchase = value;
  return self;
}
- (RareBoosterPurchaseProto_Builder*) clearTimeOfPurchase {
  result.hasTimeOfPurchase = NO;
  result.timeOfPurchase = 0L;
  return self;
}
- (BOOL) hasMonsterId {
  return result.hasMonsterId;
}
- (int32_t) monsterId {
  return result.monsterId;
}
- (RareBoosterPurchaseProto_Builder*) setMonsterId:(int32_t) value {
  result.hasMonsterId = YES;
  result.monsterId = value;
  return self;
}
- (RareBoosterPurchaseProto_Builder*) clearMonsterId {
  result.hasMonsterId = NO;
  result.monsterId = 0;
  return self;
}
@end

@interface BoosterPackProto ()
@property int32_t boosterPackId;
@property BOOL costsCoins;
@property (retain) NSString* name;
@property (retain) NSMutableArray* mutableBoosterItemsList;
@property int32_t price;
@end

@implementation BoosterPackProto

- (BOOL) hasBoosterPackId {
  return !!hasBoosterPackId_;
}
- (void) setHasBoosterPackId:(BOOL) value {
  hasBoosterPackId_ = !!value;
}
@synthesize boosterPackId;
- (BOOL) hasCostsCoins {
  return !!hasCostsCoins_;
}
- (void) setHasCostsCoins:(BOOL) value {
  hasCostsCoins_ = !!value;
}
- (BOOL) costsCoins {
  return !!costsCoins_;
}
- (void) setCostsCoins:(BOOL) value {
  costsCoins_ = !!value;
}
- (BOOL) hasName {
  return !!hasName_;
}
- (void) setHasName:(BOOL) value {
  hasName_ = !!value;
}
@synthesize name;
@synthesize mutableBoosterItemsList;
- (BOOL) hasPrice {
  return !!hasPrice_;
}
- (void) setHasPrice:(BOOL) value {
  hasPrice_ = !!value;
}
@synthesize price;
- (void) dealloc {
  self.name = nil;
  self.mutableBoosterItemsList = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.boosterPackId = 0;
    self.costsCoins = NO;
    self.name = @"";
    self.price = 0;
  }
  return self;
}
static BoosterPackProto* defaultBoosterPackProtoInstance = nil;
+ (void) initialize {
  if (self == [BoosterPackProto class]) {
    defaultBoosterPackProtoInstance = [[BoosterPackProto alloc] init];
  }
}
+ (BoosterPackProto*) defaultInstance {
  return defaultBoosterPackProtoInstance;
}
- (BoosterPackProto*) defaultInstance {
  return defaultBoosterPackProtoInstance;
}
- (NSArray*) boosterItemsList {
  return mutableBoosterItemsList;
}
- (BoosterItemProto*) boosterItemsAtIndex:(int32_t) index {
  id value = [mutableBoosterItemsList objectAtIndex:index];
  return value;
}
- (BOOL) isInitialized {
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasBoosterPackId) {
    [output writeInt32:1 value:self.boosterPackId];
  }
  if (self.hasCostsCoins) {
    [output writeBool:2 value:self.costsCoins];
  }
  if (self.hasName) {
    [output writeString:3 value:self.name];
  }
  for (BoosterItemProto* element in self.boosterItemsList) {
    [output writeMessage:4 value:element];
  }
  if (self.hasPrice) {
    [output writeInt32:5 value:self.price];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (int32_t) serializedSize {
  int32_t size = memoizedSerializedSize;
  if (size != -1) {
    return size;
  }

  size = 0;
  if (self.hasBoosterPackId) {
    size += computeInt32Size(1, self.boosterPackId);
  }
  if (self.hasCostsCoins) {
    size += computeBoolSize(2, self.costsCoins);
  }
  if (self.hasName) {
    size += computeStringSize(3, self.name);
  }
  for (BoosterItemProto* element in self.boosterItemsList) {
    size += computeMessageSize(4, element);
  }
  if (self.hasPrice) {
    size += computeInt32Size(5, self.price);
  }
  size += self.unknownFields.serializedSize;
  memoizedSerializedSize = size;
  return size;
}
+ (BoosterPackProto*) parseFromData:(NSData*) data {
  return (BoosterPackProto*)[[[BoosterPackProto builder] mergeFromData:data] build];
}
+ (BoosterPackProto*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (BoosterPackProto*)[[[BoosterPackProto builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (BoosterPackProto*) parseFromInputStream:(NSInputStream*) input {
  return (BoosterPackProto*)[[[BoosterPackProto builder] mergeFromInputStream:input] build];
}
+ (BoosterPackProto*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (BoosterPackProto*)[[[BoosterPackProto builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (BoosterPackProto*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (BoosterPackProto*)[[[BoosterPackProto builder] mergeFromCodedInputStream:input] build];
}
+ (BoosterPackProto*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (BoosterPackProto*)[[[BoosterPackProto builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (BoosterPackProto_Builder*) builder {
  return [[[BoosterPackProto_Builder alloc] init] autorelease];
}
+ (BoosterPackProto_Builder*) builderWithPrototype:(BoosterPackProto*) prototype {
  return [[BoosterPackProto builder] mergeFrom:prototype];
}
- (BoosterPackProto_Builder*) builder {
  return [BoosterPackProto builder];
}
@end

@interface BoosterPackProto_Builder()
@property (retain) BoosterPackProto* result;
@end

@implementation BoosterPackProto_Builder
@synthesize result;
- (void) dealloc {
  self.result = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.result = [[[BoosterPackProto alloc] init] autorelease];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return result;
}
- (BoosterPackProto_Builder*) clear {
  self.result = [[[BoosterPackProto alloc] init] autorelease];
  return self;
}
- (BoosterPackProto_Builder*) clone {
  return [BoosterPackProto builderWithPrototype:result];
}
- (BoosterPackProto*) defaultInstance {
  return [BoosterPackProto defaultInstance];
}
- (BoosterPackProto*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (BoosterPackProto*) buildPartial {
  BoosterPackProto* returnMe = [[result retain] autorelease];
  self.result = nil;
  return returnMe;
}
- (BoosterPackProto_Builder*) mergeFrom:(BoosterPackProto*) other {
  if (other == [BoosterPackProto defaultInstance]) {
    return self;
  }
  if (other.hasBoosterPackId) {
    [self setBoosterPackId:other.boosterPackId];
  }
  if (other.hasCostsCoins) {
    [self setCostsCoins:other.costsCoins];
  }
  if (other.hasName) {
    [self setName:other.name];
  }
  if (other.mutableBoosterItemsList.count > 0) {
    if (result.mutableBoosterItemsList == nil) {
      result.mutableBoosterItemsList = [NSMutableArray array];
    }
    [result.mutableBoosterItemsList addObjectsFromArray:other.mutableBoosterItemsList];
  }
  if (other.hasPrice) {
    [self setPrice:other.price];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (BoosterPackProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (BoosterPackProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSet_Builder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    int32_t tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 8: {
        [self setBoosterPackId:[input readInt32]];
        break;
      }
      case 16: {
        [self setCostsCoins:[input readBool]];
        break;
      }
      case 26: {
        [self setName:[input readString]];
        break;
      }
      case 34: {
        BoosterItemProto_Builder* subBuilder = [BoosterItemProto builder];
        [input readMessage:subBuilder extensionRegistry:extensionRegistry];
        [self addBoosterItems:[subBuilder buildPartial]];
        break;
      }
      case 40: {
        [self setPrice:[input readInt32]];
        break;
      }
    }
  }
}
- (BOOL) hasBoosterPackId {
  return result.hasBoosterPackId;
}
- (int32_t) boosterPackId {
  return result.boosterPackId;
}
- (BoosterPackProto_Builder*) setBoosterPackId:(int32_t) value {
  result.hasBoosterPackId = YES;
  result.boosterPackId = value;
  return self;
}
- (BoosterPackProto_Builder*) clearBoosterPackId {
  result.hasBoosterPackId = NO;
  result.boosterPackId = 0;
  return self;
}
- (BOOL) hasCostsCoins {
  return result.hasCostsCoins;
}
- (BOOL) costsCoins {
  return result.costsCoins;
}
- (BoosterPackProto_Builder*) setCostsCoins:(BOOL) value {
  result.hasCostsCoins = YES;
  result.costsCoins = value;
  return self;
}
- (BoosterPackProto_Builder*) clearCostsCoins {
  result.hasCostsCoins = NO;
  result.costsCoins = NO;
  return self;
}
- (BOOL) hasName {
  return result.hasName;
}
- (NSString*) name {
  return result.name;
}
- (BoosterPackProto_Builder*) setName:(NSString*) value {
  result.hasName = YES;
  result.name = value;
  return self;
}
- (BoosterPackProto_Builder*) clearName {
  result.hasName = NO;
  result.name = @"";
  return self;
}
- (NSArray*) boosterItemsList {
  if (result.mutableBoosterItemsList == nil) { return [NSArray array]; }
  return result.mutableBoosterItemsList;
}
- (BoosterItemProto*) boosterItemsAtIndex:(int32_t) index {
  return [result boosterItemsAtIndex:index];
}
- (BoosterPackProto_Builder*) replaceBoosterItemsAtIndex:(int32_t) index with:(BoosterItemProto*) value {
  [result.mutableBoosterItemsList replaceObjectAtIndex:index withObject:value];
  return self;
}
- (BoosterPackProto_Builder*) addAllBoosterItems:(NSArray*) values {
  if (result.mutableBoosterItemsList == nil) {
    result.mutableBoosterItemsList = [NSMutableArray array];
  }
  [result.mutableBoosterItemsList addObjectsFromArray:values];
  return self;
}
- (BoosterPackProto_Builder*) clearBoosterItemsList {
  result.mutableBoosterItemsList = nil;
  return self;
}
- (BoosterPackProto_Builder*) addBoosterItems:(BoosterItemProto*) value {
  if (result.mutableBoosterItemsList == nil) {
    result.mutableBoosterItemsList = [NSMutableArray array];
  }
  [result.mutableBoosterItemsList addObject:value];
  return self;
}
- (BOOL) hasPrice {
  return result.hasPrice;
}
- (int32_t) price {
  return result.price;
}
- (BoosterPackProto_Builder*) setPrice:(int32_t) value {
  result.hasPrice = YES;
  result.price = value;
  return self;
}
- (BoosterPackProto_Builder*) clearPrice {
  result.hasPrice = NO;
  result.price = 0;
  return self;
}
@end

@interface BoosterItemProto ()
@property int32_t boosterItemId;
@property int32_t equipId;
@property int32_t quantity;
@property BOOL isSpecial;
@end

@implementation BoosterItemProto

- (BOOL) hasBoosterItemId {
  return !!hasBoosterItemId_;
}
- (void) setHasBoosterItemId:(BOOL) value {
  hasBoosterItemId_ = !!value;
}
@synthesize boosterItemId;
- (BOOL) hasEquipId {
  return !!hasEquipId_;
}
- (void) setHasEquipId:(BOOL) value {
  hasEquipId_ = !!value;
}
@synthesize equipId;
- (BOOL) hasQuantity {
  return !!hasQuantity_;
}
- (void) setHasQuantity:(BOOL) value {
  hasQuantity_ = !!value;
}
@synthesize quantity;
- (BOOL) hasIsSpecial {
  return !!hasIsSpecial_;
}
- (void) setHasIsSpecial:(BOOL) value {
  hasIsSpecial_ = !!value;
}
- (BOOL) isSpecial {
  return !!isSpecial_;
}
- (void) setIsSpecial:(BOOL) value {
  isSpecial_ = !!value;
}
- (void) dealloc {
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.boosterItemId = 0;
    self.equipId = 0;
    self.quantity = 0;
    self.isSpecial = NO;
  }
  return self;
}
static BoosterItemProto* defaultBoosterItemProtoInstance = nil;
+ (void) initialize {
  if (self == [BoosterItemProto class]) {
    defaultBoosterItemProtoInstance = [[BoosterItemProto alloc] init];
  }
}
+ (BoosterItemProto*) defaultInstance {
  return defaultBoosterItemProtoInstance;
}
- (BoosterItemProto*) defaultInstance {
  return defaultBoosterItemProtoInstance;
}
- (BOOL) isInitialized {
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasBoosterItemId) {
    [output writeInt32:1 value:self.boosterItemId];
  }
  if (self.hasEquipId) {
    [output writeInt32:2 value:self.equipId];
  }
  if (self.hasQuantity) {
    [output writeInt32:3 value:self.quantity];
  }
  if (self.hasIsSpecial) {
    [output writeBool:4 value:self.isSpecial];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (int32_t) serializedSize {
  int32_t size = memoizedSerializedSize;
  if (size != -1) {
    return size;
  }

  size = 0;
  if (self.hasBoosterItemId) {
    size += computeInt32Size(1, self.boosterItemId);
  }
  if (self.hasEquipId) {
    size += computeInt32Size(2, self.equipId);
  }
  if (self.hasQuantity) {
    size += computeInt32Size(3, self.quantity);
  }
  if (self.hasIsSpecial) {
    size += computeBoolSize(4, self.isSpecial);
  }
  size += self.unknownFields.serializedSize;
  memoizedSerializedSize = size;
  return size;
}
+ (BoosterItemProto*) parseFromData:(NSData*) data {
  return (BoosterItemProto*)[[[BoosterItemProto builder] mergeFromData:data] build];
}
+ (BoosterItemProto*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (BoosterItemProto*)[[[BoosterItemProto builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (BoosterItemProto*) parseFromInputStream:(NSInputStream*) input {
  return (BoosterItemProto*)[[[BoosterItemProto builder] mergeFromInputStream:input] build];
}
+ (BoosterItemProto*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (BoosterItemProto*)[[[BoosterItemProto builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (BoosterItemProto*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (BoosterItemProto*)[[[BoosterItemProto builder] mergeFromCodedInputStream:input] build];
}
+ (BoosterItemProto*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (BoosterItemProto*)[[[BoosterItemProto builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (BoosterItemProto_Builder*) builder {
  return [[[BoosterItemProto_Builder alloc] init] autorelease];
}
+ (BoosterItemProto_Builder*) builderWithPrototype:(BoosterItemProto*) prototype {
  return [[BoosterItemProto builder] mergeFrom:prototype];
}
- (BoosterItemProto_Builder*) builder {
  return [BoosterItemProto builder];
}
@end

@interface BoosterItemProto_Builder()
@property (retain) BoosterItemProto* result;
@end

@implementation BoosterItemProto_Builder
@synthesize result;
- (void) dealloc {
  self.result = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.result = [[[BoosterItemProto alloc] init] autorelease];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return result;
}
- (BoosterItemProto_Builder*) clear {
  self.result = [[[BoosterItemProto alloc] init] autorelease];
  return self;
}
- (BoosterItemProto_Builder*) clone {
  return [BoosterItemProto builderWithPrototype:result];
}
- (BoosterItemProto*) defaultInstance {
  return [BoosterItemProto defaultInstance];
}
- (BoosterItemProto*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (BoosterItemProto*) buildPartial {
  BoosterItemProto* returnMe = [[result retain] autorelease];
  self.result = nil;
  return returnMe;
}
- (BoosterItemProto_Builder*) mergeFrom:(BoosterItemProto*) other {
  if (other == [BoosterItemProto defaultInstance]) {
    return self;
  }
  if (other.hasBoosterItemId) {
    [self setBoosterItemId:other.boosterItemId];
  }
  if (other.hasEquipId) {
    [self setEquipId:other.equipId];
  }
  if (other.hasQuantity) {
    [self setQuantity:other.quantity];
  }
  if (other.hasIsSpecial) {
    [self setIsSpecial:other.isSpecial];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (BoosterItemProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (BoosterItemProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSet_Builder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    int32_t tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 8: {
        [self setBoosterItemId:[input readInt32]];
        break;
      }
      case 16: {
        [self setEquipId:[input readInt32]];
        break;
      }
      case 24: {
        [self setQuantity:[input readInt32]];
        break;
      }
      case 32: {
        [self setIsSpecial:[input readBool]];
        break;
      }
    }
  }
}
- (BOOL) hasBoosterItemId {
  return result.hasBoosterItemId;
}
- (int32_t) boosterItemId {
  return result.boosterItemId;
}
- (BoosterItemProto_Builder*) setBoosterItemId:(int32_t) value {
  result.hasBoosterItemId = YES;
  result.boosterItemId = value;
  return self;
}
- (BoosterItemProto_Builder*) clearBoosterItemId {
  result.hasBoosterItemId = NO;
  result.boosterItemId = 0;
  return self;
}
- (BOOL) hasEquipId {
  return result.hasEquipId;
}
- (int32_t) equipId {
  return result.equipId;
}
- (BoosterItemProto_Builder*) setEquipId:(int32_t) value {
  result.hasEquipId = YES;
  result.equipId = value;
  return self;
}
- (BoosterItemProto_Builder*) clearEquipId {
  result.hasEquipId = NO;
  result.equipId = 0;
  return self;
}
- (BOOL) hasQuantity {
  return result.hasQuantity;
}
- (int32_t) quantity {
  return result.quantity;
}
- (BoosterItemProto_Builder*) setQuantity:(int32_t) value {
  result.hasQuantity = YES;
  result.quantity = value;
  return self;
}
- (BoosterItemProto_Builder*) clearQuantity {
  result.hasQuantity = NO;
  result.quantity = 0;
  return self;
}
- (BOOL) hasIsSpecial {
  return result.hasIsSpecial;
}
- (BOOL) isSpecial {
  return result.isSpecial;
}
- (BoosterItemProto_Builder*) setIsSpecial:(BOOL) value {
  result.hasIsSpecial = YES;
  result.isSpecial = value;
  return self;
}
- (BoosterItemProto_Builder*) clearIsSpecial {
  result.hasIsSpecial = NO;
  result.isSpecial = NO;
  return self;
}
@end

