// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

#import "City.pb.h"
#import "Structure.pb.h"
#import "User.pb.h"

@class CityElementProto;
@class CityElementProto_Builder;
@class CityExpansionCostProto;
@class CityExpansionCostProto_Builder;
@class CoordinateProto;
@class CoordinateProto_Builder;
@class FullCityProto;
@class FullCityProto_Builder;
@class FullStructureProto;
@class FullStructureProto_Builder;
@class FullUserProto;
@class FullUserProto_Builder;
@class FullUserStructureProto;
@class FullUserStructureProto_Builder;
@class LoadPlayerCityRequestProto;
@class LoadPlayerCityRequestProto_Builder;
@class LoadPlayerCityResponseProto;
@class LoadPlayerCityResponseProto_Builder;
@class MinimumClanProto;
@class MinimumClanProto_Builder;
@class MinimumUserProto;
@class MinimumUserProtoWithLevel;
@class MinimumUserProtoWithLevelForLeaderboard;
@class MinimumUserProtoWithLevelForLeaderboard_Builder;
@class MinimumUserProtoWithLevel_Builder;
@class MinimumUserProto_Builder;
@class PurchaseCityExpansionRequestProto;
@class PurchaseCityExpansionRequestProto_Builder;
@class PurchaseCityExpansionResponseProto;
@class PurchaseCityExpansionResponseProto_Builder;
@class UserCityExpansionDataProto;
@class UserCityExpansionDataProto_Builder;
typedef enum {
  LoadPlayerCityResponseProto_LoadPlayerCityStatusSuccess = 1,
  LoadPlayerCityResponseProto_LoadPlayerCityStatusNoSuchPlayer = 2,
  LoadPlayerCityResponseProto_LoadPlayerCityStatusOtherFail = 3,
} LoadPlayerCityResponseProto_LoadPlayerCityStatus;

BOOL LoadPlayerCityResponseProto_LoadPlayerCityStatusIsValidValue(LoadPlayerCityResponseProto_LoadPlayerCityStatus value);

typedef enum {
  PurchaseCityExpansionResponseProto_PurchaseCityExpansionStatusSuccess = 1,
  PurchaseCityExpansionResponseProto_PurchaseCityExpansionStatusNotEnoughCoins = 2,
  PurchaseCityExpansionResponseProto_PurchaseCityExpansionStatusAlreadyExpanding = 3,
  PurchaseCityExpansionResponseProto_PurchaseCityExpansionStatusOtherFail = 4,
  PurchaseCityExpansionResponseProto_PurchaseCityExpansionStatusClientTooApartFromServerTime = 5,
} PurchaseCityExpansionResponseProto_PurchaseCityExpansionStatus;

BOOL PurchaseCityExpansionResponseProto_PurchaseCityExpansionStatusIsValidValue(PurchaseCityExpansionResponseProto_PurchaseCityExpansionStatus value);


@interface EventCityRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface LoadPlayerCityRequestProto : PBGeneratedMessage {
@private
  BOOL hasCityOwnerId_:1;
  BOOL hasSender_:1;
  int32_t cityOwnerId;
  MinimumUserProto* sender;
}
- (BOOL) hasSender;
- (BOOL) hasCityOwnerId;
@property (readonly, retain) MinimumUserProto* sender;
@property (readonly) int32_t cityOwnerId;

+ (LoadPlayerCityRequestProto*) defaultInstance;
- (LoadPlayerCityRequestProto*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (LoadPlayerCityRequestProto_Builder*) builder;
+ (LoadPlayerCityRequestProto_Builder*) builder;
+ (LoadPlayerCityRequestProto_Builder*) builderWithPrototype:(LoadPlayerCityRequestProto*) prototype;

+ (LoadPlayerCityRequestProto*) parseFromData:(NSData*) data;
+ (LoadPlayerCityRequestProto*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (LoadPlayerCityRequestProto*) parseFromInputStream:(NSInputStream*) input;
+ (LoadPlayerCityRequestProto*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (LoadPlayerCityRequestProto*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (LoadPlayerCityRequestProto*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface LoadPlayerCityRequestProto_Builder : PBGeneratedMessage_Builder {
@private
  LoadPlayerCityRequestProto* result;
}

- (LoadPlayerCityRequestProto*) defaultInstance;

- (LoadPlayerCityRequestProto_Builder*) clear;
- (LoadPlayerCityRequestProto_Builder*) clone;

- (LoadPlayerCityRequestProto*) build;
- (LoadPlayerCityRequestProto*) buildPartial;

- (LoadPlayerCityRequestProto_Builder*) mergeFrom:(LoadPlayerCityRequestProto*) other;
- (LoadPlayerCityRequestProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (LoadPlayerCityRequestProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasSender;
- (MinimumUserProto*) sender;
- (LoadPlayerCityRequestProto_Builder*) setSender:(MinimumUserProto*) value;
- (LoadPlayerCityRequestProto_Builder*) setSenderBuilder:(MinimumUserProto_Builder*) builderForValue;
- (LoadPlayerCityRequestProto_Builder*) mergeSender:(MinimumUserProto*) value;
- (LoadPlayerCityRequestProto_Builder*) clearSender;

- (BOOL) hasCityOwnerId;
- (int32_t) cityOwnerId;
- (LoadPlayerCityRequestProto_Builder*) setCityOwnerId:(int32_t) value;
- (LoadPlayerCityRequestProto_Builder*) clearCityOwnerId;
@end

@interface LoadPlayerCityResponseProto : PBGeneratedMessage {
@private
  BOOL hasSender_:1;
  BOOL hasCityOwner_:1;
  BOOL hasStatus_:1;
  MinimumUserProto* sender;
  MinimumUserProto* cityOwner;
  LoadPlayerCityResponseProto_LoadPlayerCityStatus status;
  NSMutableArray* mutableOwnerNormStructsList;
  NSMutableArray* mutableUserCityExpansionDataProtoListList;
}
- (BOOL) hasSender;
- (BOOL) hasCityOwner;
- (BOOL) hasStatus;
@property (readonly, retain) MinimumUserProto* sender;
@property (readonly, retain) MinimumUserProto* cityOwner;
@property (readonly) LoadPlayerCityResponseProto_LoadPlayerCityStatus status;
- (NSArray*) ownerNormStructsList;
- (FullUserStructureProto*) ownerNormStructsAtIndex:(int32_t) index;
- (NSArray*) userCityExpansionDataProtoListList;
- (UserCityExpansionDataProto*) userCityExpansionDataProtoListAtIndex:(int32_t) index;

+ (LoadPlayerCityResponseProto*) defaultInstance;
- (LoadPlayerCityResponseProto*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (LoadPlayerCityResponseProto_Builder*) builder;
+ (LoadPlayerCityResponseProto_Builder*) builder;
+ (LoadPlayerCityResponseProto_Builder*) builderWithPrototype:(LoadPlayerCityResponseProto*) prototype;

+ (LoadPlayerCityResponseProto*) parseFromData:(NSData*) data;
+ (LoadPlayerCityResponseProto*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (LoadPlayerCityResponseProto*) parseFromInputStream:(NSInputStream*) input;
+ (LoadPlayerCityResponseProto*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (LoadPlayerCityResponseProto*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (LoadPlayerCityResponseProto*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface LoadPlayerCityResponseProto_Builder : PBGeneratedMessage_Builder {
@private
  LoadPlayerCityResponseProto* result;
}

- (LoadPlayerCityResponseProto*) defaultInstance;

- (LoadPlayerCityResponseProto_Builder*) clear;
- (LoadPlayerCityResponseProto_Builder*) clone;

- (LoadPlayerCityResponseProto*) build;
- (LoadPlayerCityResponseProto*) buildPartial;

- (LoadPlayerCityResponseProto_Builder*) mergeFrom:(LoadPlayerCityResponseProto*) other;
- (LoadPlayerCityResponseProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (LoadPlayerCityResponseProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasSender;
- (MinimumUserProto*) sender;
- (LoadPlayerCityResponseProto_Builder*) setSender:(MinimumUserProto*) value;
- (LoadPlayerCityResponseProto_Builder*) setSenderBuilder:(MinimumUserProto_Builder*) builderForValue;
- (LoadPlayerCityResponseProto_Builder*) mergeSender:(MinimumUserProto*) value;
- (LoadPlayerCityResponseProto_Builder*) clearSender;

- (BOOL) hasCityOwner;
- (MinimumUserProto*) cityOwner;
- (LoadPlayerCityResponseProto_Builder*) setCityOwner:(MinimumUserProto*) value;
- (LoadPlayerCityResponseProto_Builder*) setCityOwnerBuilder:(MinimumUserProto_Builder*) builderForValue;
- (LoadPlayerCityResponseProto_Builder*) mergeCityOwner:(MinimumUserProto*) value;
- (LoadPlayerCityResponseProto_Builder*) clearCityOwner;

- (BOOL) hasStatus;
- (LoadPlayerCityResponseProto_LoadPlayerCityStatus) status;
- (LoadPlayerCityResponseProto_Builder*) setStatus:(LoadPlayerCityResponseProto_LoadPlayerCityStatus) value;
- (LoadPlayerCityResponseProto_Builder*) clearStatus;

- (NSArray*) ownerNormStructsList;
- (FullUserStructureProto*) ownerNormStructsAtIndex:(int32_t) index;
- (LoadPlayerCityResponseProto_Builder*) replaceOwnerNormStructsAtIndex:(int32_t) index with:(FullUserStructureProto*) value;
- (LoadPlayerCityResponseProto_Builder*) addOwnerNormStructs:(FullUserStructureProto*) value;
- (LoadPlayerCityResponseProto_Builder*) addAllOwnerNormStructs:(NSArray*) values;
- (LoadPlayerCityResponseProto_Builder*) clearOwnerNormStructsList;

- (NSArray*) userCityExpansionDataProtoListList;
- (UserCityExpansionDataProto*) userCityExpansionDataProtoListAtIndex:(int32_t) index;
- (LoadPlayerCityResponseProto_Builder*) replaceUserCityExpansionDataProtoListAtIndex:(int32_t) index with:(UserCityExpansionDataProto*) value;
- (LoadPlayerCityResponseProto_Builder*) addUserCityExpansionDataProtoList:(UserCityExpansionDataProto*) value;
- (LoadPlayerCityResponseProto_Builder*) addAllUserCityExpansionDataProtoList:(NSArray*) values;
- (LoadPlayerCityResponseProto_Builder*) clearUserCityExpansionDataProtoListList;
@end

@interface PurchaseCityExpansionRequestProto : PBGeneratedMessage {
@private
  BOOL hasTimeOfPurchase_:1;
  BOOL hasSender_:1;
  BOOL hasXPosition_:1;
  BOOL hasYPosition_:1;
  int64_t timeOfPurchase;
  MinimumUserProto* sender;
  int32_t xPosition;
  int32_t yPosition;
}
- (BOOL) hasSender;
- (BOOL) hasXPosition;
- (BOOL) hasYPosition;
- (BOOL) hasTimeOfPurchase;
@property (readonly, retain) MinimumUserProto* sender;
@property (readonly) int32_t xPosition;
@property (readonly) int32_t yPosition;
@property (readonly) int64_t timeOfPurchase;

+ (PurchaseCityExpansionRequestProto*) defaultInstance;
- (PurchaseCityExpansionRequestProto*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (PurchaseCityExpansionRequestProto_Builder*) builder;
+ (PurchaseCityExpansionRequestProto_Builder*) builder;
+ (PurchaseCityExpansionRequestProto_Builder*) builderWithPrototype:(PurchaseCityExpansionRequestProto*) prototype;

+ (PurchaseCityExpansionRequestProto*) parseFromData:(NSData*) data;
+ (PurchaseCityExpansionRequestProto*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PurchaseCityExpansionRequestProto*) parseFromInputStream:(NSInputStream*) input;
+ (PurchaseCityExpansionRequestProto*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PurchaseCityExpansionRequestProto*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (PurchaseCityExpansionRequestProto*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface PurchaseCityExpansionRequestProto_Builder : PBGeneratedMessage_Builder {
@private
  PurchaseCityExpansionRequestProto* result;
}

- (PurchaseCityExpansionRequestProto*) defaultInstance;

- (PurchaseCityExpansionRequestProto_Builder*) clear;
- (PurchaseCityExpansionRequestProto_Builder*) clone;

- (PurchaseCityExpansionRequestProto*) build;
- (PurchaseCityExpansionRequestProto*) buildPartial;

- (PurchaseCityExpansionRequestProto_Builder*) mergeFrom:(PurchaseCityExpansionRequestProto*) other;
- (PurchaseCityExpansionRequestProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (PurchaseCityExpansionRequestProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasSender;
- (MinimumUserProto*) sender;
- (PurchaseCityExpansionRequestProto_Builder*) setSender:(MinimumUserProto*) value;
- (PurchaseCityExpansionRequestProto_Builder*) setSenderBuilder:(MinimumUserProto_Builder*) builderForValue;
- (PurchaseCityExpansionRequestProto_Builder*) mergeSender:(MinimumUserProto*) value;
- (PurchaseCityExpansionRequestProto_Builder*) clearSender;

- (BOOL) hasXPosition;
- (int32_t) xPosition;
- (PurchaseCityExpansionRequestProto_Builder*) setXPosition:(int32_t) value;
- (PurchaseCityExpansionRequestProto_Builder*) clearXPosition;

- (BOOL) hasYPosition;
- (int32_t) yPosition;
- (PurchaseCityExpansionRequestProto_Builder*) setYPosition:(int32_t) value;
- (PurchaseCityExpansionRequestProto_Builder*) clearYPosition;

- (BOOL) hasTimeOfPurchase;
- (int64_t) timeOfPurchase;
- (PurchaseCityExpansionRequestProto_Builder*) setTimeOfPurchase:(int64_t) value;
- (PurchaseCityExpansionRequestProto_Builder*) clearTimeOfPurchase;
@end

@interface PurchaseCityExpansionResponseProto : PBGeneratedMessage {
@private
  BOOL hasSender_:1;
  BOOL hasUcedp_:1;
  BOOL hasStatus_:1;
  MinimumUserProto* sender;
  UserCityExpansionDataProto* ucedp;
  PurchaseCityExpansionResponseProto_PurchaseCityExpansionStatus status;
}
- (BOOL) hasSender;
- (BOOL) hasStatus;
- (BOOL) hasUcedp;
@property (readonly, retain) MinimumUserProto* sender;
@property (readonly) PurchaseCityExpansionResponseProto_PurchaseCityExpansionStatus status;
@property (readonly, retain) UserCityExpansionDataProto* ucedp;

+ (PurchaseCityExpansionResponseProto*) defaultInstance;
- (PurchaseCityExpansionResponseProto*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (PurchaseCityExpansionResponseProto_Builder*) builder;
+ (PurchaseCityExpansionResponseProto_Builder*) builder;
+ (PurchaseCityExpansionResponseProto_Builder*) builderWithPrototype:(PurchaseCityExpansionResponseProto*) prototype;

+ (PurchaseCityExpansionResponseProto*) parseFromData:(NSData*) data;
+ (PurchaseCityExpansionResponseProto*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PurchaseCityExpansionResponseProto*) parseFromInputStream:(NSInputStream*) input;
+ (PurchaseCityExpansionResponseProto*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PurchaseCityExpansionResponseProto*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (PurchaseCityExpansionResponseProto*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface PurchaseCityExpansionResponseProto_Builder : PBGeneratedMessage_Builder {
@private
  PurchaseCityExpansionResponseProto* result;
}

- (PurchaseCityExpansionResponseProto*) defaultInstance;

- (PurchaseCityExpansionResponseProto_Builder*) clear;
- (PurchaseCityExpansionResponseProto_Builder*) clone;

- (PurchaseCityExpansionResponseProto*) build;
- (PurchaseCityExpansionResponseProto*) buildPartial;

- (PurchaseCityExpansionResponseProto_Builder*) mergeFrom:(PurchaseCityExpansionResponseProto*) other;
- (PurchaseCityExpansionResponseProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (PurchaseCityExpansionResponseProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasSender;
- (MinimumUserProto*) sender;
- (PurchaseCityExpansionResponseProto_Builder*) setSender:(MinimumUserProto*) value;
- (PurchaseCityExpansionResponseProto_Builder*) setSenderBuilder:(MinimumUserProto_Builder*) builderForValue;
- (PurchaseCityExpansionResponseProto_Builder*) mergeSender:(MinimumUserProto*) value;
- (PurchaseCityExpansionResponseProto_Builder*) clearSender;

- (BOOL) hasStatus;
- (PurchaseCityExpansionResponseProto_PurchaseCityExpansionStatus) status;
- (PurchaseCityExpansionResponseProto_Builder*) setStatus:(PurchaseCityExpansionResponseProto_PurchaseCityExpansionStatus) value;
- (PurchaseCityExpansionResponseProto_Builder*) clearStatus;

- (BOOL) hasUcedp;
- (UserCityExpansionDataProto*) ucedp;
- (PurchaseCityExpansionResponseProto_Builder*) setUcedp:(UserCityExpansionDataProto*) value;
- (PurchaseCityExpansionResponseProto_Builder*) setUcedpBuilder:(UserCityExpansionDataProto_Builder*) builderForValue;
- (PurchaseCityExpansionResponseProto_Builder*) mergeUcedp:(UserCityExpansionDataProto*) value;
- (PurchaseCityExpansionResponseProto_Builder*) clearUcedp;
@end

