// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "EventStaticData.pb.h"
// @@protoc_insertion_point(imports)

@implementation EventStaticDataRoot
static PBExtensionRegistry* extensionRegistry = nil;
+ (PBExtensionRegistry*) extensionRegistry {
  return extensionRegistry;
}

+ (void) initialize {
  if (self == [EventStaticDataRoot class]) {
    PBMutableExtensionRegistry* registry = [PBMutableExtensionRegistry registry];
    [self registerAllExtensions:registry];
    [StaticDataRoot registerAllExtensions:registry];
    extensionRegistry = registry;
  }
}
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry {
}
@end

@interface PurgeClientStaticDataResponseProto ()
@property int32_t senderId;
@property (strong) StaticDataProto* staticDataStuff;
@end

@implementation PurgeClientStaticDataResponseProto

- (BOOL) hasSenderId {
  return !!hasSenderId_;
}
- (void) setHasSenderId:(BOOL) value_ {
  hasSenderId_ = !!value_;
}
@synthesize senderId;
- (BOOL) hasStaticDataStuff {
  return !!hasStaticDataStuff_;
}
- (void) setHasStaticDataStuff:(BOOL) value_ {
  hasStaticDataStuff_ = !!value_;
}
@synthesize staticDataStuff;
- (id) init {
  if ((self = [super init])) {
    self.senderId = 0;
    self.staticDataStuff = [StaticDataProto defaultInstance];
  }
  return self;
}
static PurgeClientStaticDataResponseProto* defaultPurgeClientStaticDataResponseProtoInstance = nil;
+ (void) initialize {
  if (self == [PurgeClientStaticDataResponseProto class]) {
    defaultPurgeClientStaticDataResponseProtoInstance = [[PurgeClientStaticDataResponseProto alloc] init];
  }
}
+ (PurgeClientStaticDataResponseProto*) defaultInstance {
  return defaultPurgeClientStaticDataResponseProtoInstance;
}
- (PurgeClientStaticDataResponseProto*) defaultInstance {
  return defaultPurgeClientStaticDataResponseProtoInstance;
}
- (BOOL) isInitialized {
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasSenderId) {
    [output writeInt32:1 value:self.senderId];
  }
  if (self.hasStaticDataStuff) {
    [output writeMessage:2 value:self.staticDataStuff];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (SInt32) serializedSize {
  __block SInt32 size_ = memoizedSerializedSize;
  if (size_ != -1) {
    return size_;
  }

  size_ = 0;
  if (self.hasSenderId) {
    size_ += computeInt32Size(1, self.senderId);
  }
  if (self.hasStaticDataStuff) {
    size_ += computeMessageSize(2, self.staticDataStuff);
  }
  size_ += self.unknownFields.serializedSize;
  memoizedSerializedSize = size_;
  return size_;
}
+ (PurgeClientStaticDataResponseProto*) parseFromData:(NSData*) data {
  return (PurgeClientStaticDataResponseProto*)[[[PurgeClientStaticDataResponseProto builder] mergeFromData:data] build];
}
+ (PurgeClientStaticDataResponseProto*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (PurgeClientStaticDataResponseProto*)[[[PurgeClientStaticDataResponseProto builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (PurgeClientStaticDataResponseProto*) parseFromInputStream:(NSInputStream*) input {
  return (PurgeClientStaticDataResponseProto*)[[[PurgeClientStaticDataResponseProto builder] mergeFromInputStream:input] build];
}
+ (PurgeClientStaticDataResponseProto*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (PurgeClientStaticDataResponseProto*)[[[PurgeClientStaticDataResponseProto builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (PurgeClientStaticDataResponseProto*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (PurgeClientStaticDataResponseProto*)[[[PurgeClientStaticDataResponseProto builder] mergeFromCodedInputStream:input] build];
}
+ (PurgeClientStaticDataResponseProto*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (PurgeClientStaticDataResponseProto*)[[[PurgeClientStaticDataResponseProto builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (PurgeClientStaticDataResponseProto_Builder*) builder {
  return [[PurgeClientStaticDataResponseProto_Builder alloc] init];
}
+ (PurgeClientStaticDataResponseProto_Builder*) builderWithPrototype:(PurgeClientStaticDataResponseProto*) prototype {
  return [[PurgeClientStaticDataResponseProto builder] mergeFrom:prototype];
}
- (PurgeClientStaticDataResponseProto_Builder*) builder {
  return [PurgeClientStaticDataResponseProto builder];
}
- (PurgeClientStaticDataResponseProto_Builder*) toBuilder {
  return [PurgeClientStaticDataResponseProto builderWithPrototype:self];
}
- (void) writeDescriptionTo:(NSMutableString*) output withIndent:(NSString*) indent {
  if (self.hasSenderId) {
    [output appendFormat:@"%@%@: %@\n", indent, @"senderId", [NSNumber numberWithInteger:self.senderId]];
  }
  if (self.hasStaticDataStuff) {
    [output appendFormat:@"%@%@ {\n", indent, @"staticDataStuff"];
    [self.staticDataStuff writeDescriptionTo:output
                         withIndent:[NSString stringWithFormat:@"%@  ", indent]];
    [output appendFormat:@"%@}\n", indent];
  }
  [self.unknownFields writeDescriptionTo:output withIndent:indent];
}
- (BOOL) isEqual:(id)other {
  if (other == self) {
    return YES;
  }
  if (![other isKindOfClass:[PurgeClientStaticDataResponseProto class]]) {
    return NO;
  }
  PurgeClientStaticDataResponseProto *otherMessage = other;
  return
      self.hasSenderId == otherMessage.hasSenderId &&
      (!self.hasSenderId || self.senderId == otherMessage.senderId) &&
      self.hasStaticDataStuff == otherMessage.hasStaticDataStuff &&
      (!self.hasStaticDataStuff || [self.staticDataStuff isEqual:otherMessage.staticDataStuff]) &&
      (self.unknownFields == otherMessage.unknownFields || (self.unknownFields != nil && [self.unknownFields isEqual:otherMessage.unknownFields]));
}
- (NSUInteger) hash {
  __block NSUInteger hashCode = 7;
  if (self.hasSenderId) {
    hashCode = hashCode * 31 + [[NSNumber numberWithInteger:self.senderId] hash];
  }
  if (self.hasStaticDataStuff) {
    hashCode = hashCode * 31 + [self.staticDataStuff hash];
  }
  hashCode = hashCode * 31 + [self.unknownFields hash];
  return hashCode;
}
@end

@interface PurgeClientStaticDataResponseProto_Builder()
@property (strong) PurgeClientStaticDataResponseProto* result;
@end

@implementation PurgeClientStaticDataResponseProto_Builder
@synthesize result;
- (id) init {
  if ((self = [super init])) {
    self.result = [[PurgeClientStaticDataResponseProto alloc] init];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return result;
}
- (PurgeClientStaticDataResponseProto_Builder*) clear {
  self.result = [[PurgeClientStaticDataResponseProto alloc] init];
  return self;
}
- (PurgeClientStaticDataResponseProto_Builder*) clone {
  return [PurgeClientStaticDataResponseProto builderWithPrototype:result];
}
- (PurgeClientStaticDataResponseProto*) defaultInstance {
  return [PurgeClientStaticDataResponseProto defaultInstance];
}
- (PurgeClientStaticDataResponseProto*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (PurgeClientStaticDataResponseProto*) buildPartial {
  PurgeClientStaticDataResponseProto* returnMe = result;
  self.result = nil;
  return returnMe;
}
- (PurgeClientStaticDataResponseProto_Builder*) mergeFrom:(PurgeClientStaticDataResponseProto*) other {
  if (other == [PurgeClientStaticDataResponseProto defaultInstance]) {
    return self;
  }
  if (other.hasSenderId) {
    [self setSenderId:other.senderId];
  }
  if (other.hasStaticDataStuff) {
    [self mergeStaticDataStuff:other.staticDataStuff];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (PurgeClientStaticDataResponseProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (PurgeClientStaticDataResponseProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSetBuilder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    SInt32 tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 8: {
        [self setSenderId:[input readInt32]];
        break;
      }
      case 18: {
        StaticDataProto_Builder* subBuilder = [StaticDataProto builder];
        if (self.hasStaticDataStuff) {
          [subBuilder mergeFrom:self.staticDataStuff];
        }
        [input readMessage:subBuilder extensionRegistry:extensionRegistry];
        [self setStaticDataStuff:[subBuilder buildPartial]];
        break;
      }
    }
  }
}
- (BOOL) hasSenderId {
  return result.hasSenderId;
}
- (int32_t) senderId {
  return result.senderId;
}
- (PurgeClientStaticDataResponseProto_Builder*) setSenderId:(int32_t) value {
  result.hasSenderId = YES;
  result.senderId = value;
  return self;
}
- (PurgeClientStaticDataResponseProto_Builder*) clearSenderId {
  result.hasSenderId = NO;
  result.senderId = 0;
  return self;
}
- (BOOL) hasStaticDataStuff {
  return result.hasStaticDataStuff;
}
- (StaticDataProto*) staticDataStuff {
  return result.staticDataStuff;
}
- (PurgeClientStaticDataResponseProto_Builder*) setStaticDataStuff:(StaticDataProto*) value {
  result.hasStaticDataStuff = YES;
  result.staticDataStuff = value;
  return self;
}
- (PurgeClientStaticDataResponseProto_Builder*) setStaticDataStuff_Builder:(StaticDataProto_Builder*) builderForValue {
  return [self setStaticDataStuff:[builderForValue build]];
}
- (PurgeClientStaticDataResponseProto_Builder*) mergeStaticDataStuff:(StaticDataProto*) value {
  if (result.hasStaticDataStuff &&
      result.staticDataStuff != [StaticDataProto defaultInstance]) {
    result.staticDataStuff =
      [[[StaticDataProto builderWithPrototype:result.staticDataStuff] mergeFrom:value] buildPartial];
  } else {
    result.staticDataStuff = value;
  }
  result.hasStaticDataStuff = YES;
  return self;
}
- (PurgeClientStaticDataResponseProto_Builder*) clearStaticDataStuff {
  result.hasStaticDataStuff = NO;
  result.staticDataStuff = [StaticDataProto defaultInstance];
  return self;
}
@end


// @@protoc_insertion_point(global_scope)
