// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "Item.pb.h"
// @@protoc_insertion_point(imports)

@implementation ItemRoot
static PBExtensionRegistry* extensionRegistry = nil;
+ (PBExtensionRegistry*) extensionRegistry {
  return extensionRegistry;
}

+ (void) initialize {
  if (self == [ItemRoot class]) {
    PBMutableExtensionRegistry* registry = [PBMutableExtensionRegistry registry];
    [self registerAllExtensions:registry];
    extensionRegistry = registry;
  }
}
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry {
}
@end

BOOL ItemTypeIsValidValue(ItemType value) {
  switch (value) {
    case ItemTypeBoosterPack:
      return YES;
    default:
      return NO;
  }
}
@interface UserItemProto ()
@property int32_t userId;
@property int32_t itemId;
@property int32_t quantity;
@end

@implementation UserItemProto

- (BOOL) hasUserId {
  return !!hasUserId_;
}
- (void) setHasUserId:(BOOL) value_ {
  hasUserId_ = !!value_;
}
@synthesize userId;
- (BOOL) hasItemId {
  return !!hasItemId_;
}
- (void) setHasItemId:(BOOL) value_ {
  hasItemId_ = !!value_;
}
@synthesize itemId;
- (BOOL) hasQuantity {
  return !!hasQuantity_;
}
- (void) setHasQuantity:(BOOL) value_ {
  hasQuantity_ = !!value_;
}
@synthesize quantity;
- (id) init {
  if ((self = [super init])) {
    self.userId = 0;
    self.itemId = 0;
    self.quantity = 0;
  }
  return self;
}
static UserItemProto* defaultUserItemProtoInstance = nil;
+ (void) initialize {
  if (self == [UserItemProto class]) {
    defaultUserItemProtoInstance = [[UserItemProto alloc] init];
  }
}
+ (UserItemProto*) defaultInstance {
  return defaultUserItemProtoInstance;
}
- (UserItemProto*) defaultInstance {
  return defaultUserItemProtoInstance;
}
- (BOOL) isInitialized {
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasUserId) {
    [output writeInt32:1 value:self.userId];
  }
  if (self.hasItemId) {
    [output writeInt32:2 value:self.itemId];
  }
  if (self.hasQuantity) {
    [output writeInt32:3 value:self.quantity];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (SInt32) serializedSize {
  __block SInt32 size_ = memoizedSerializedSize;
  if (size_ != -1) {
    return size_;
  }

  size_ = 0;
  if (self.hasUserId) {
    size_ += computeInt32Size(1, self.userId);
  }
  if (self.hasItemId) {
    size_ += computeInt32Size(2, self.itemId);
  }
  if (self.hasQuantity) {
    size_ += computeInt32Size(3, self.quantity);
  }
  size_ += self.unknownFields.serializedSize;
  memoizedSerializedSize = size_;
  return size_;
}
+ (UserItemProto*) parseFromData:(NSData*) data {
  return (UserItemProto*)[[[UserItemProto builder] mergeFromData:data] build];
}
+ (UserItemProto*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (UserItemProto*)[[[UserItemProto builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (UserItemProto*) parseFromInputStream:(NSInputStream*) input {
  return (UserItemProto*)[[[UserItemProto builder] mergeFromInputStream:input] build];
}
+ (UserItemProto*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (UserItemProto*)[[[UserItemProto builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (UserItemProto*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (UserItemProto*)[[[UserItemProto builder] mergeFromCodedInputStream:input] build];
}
+ (UserItemProto*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (UserItemProto*)[[[UserItemProto builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (UserItemProto_Builder*) builder {
  return [[UserItemProto_Builder alloc] init];
}
+ (UserItemProto_Builder*) builderWithPrototype:(UserItemProto*) prototype {
  return [[UserItemProto builder] mergeFrom:prototype];
}
- (UserItemProto_Builder*) builder {
  return [UserItemProto builder];
}
- (UserItemProto_Builder*) toBuilder {
  return [UserItemProto builderWithPrototype:self];
}
- (void) writeDescriptionTo:(NSMutableString*) output withIndent:(NSString*) indent {
  if (self.hasUserId) {
    [output appendFormat:@"%@%@: %@\n", indent, @"userId", [NSNumber numberWithInteger:self.userId]];
  }
  if (self.hasItemId) {
    [output appendFormat:@"%@%@: %@\n", indent, @"itemId", [NSNumber numberWithInteger:self.itemId]];
  }
  if (self.hasQuantity) {
    [output appendFormat:@"%@%@: %@\n", indent, @"quantity", [NSNumber numberWithInteger:self.quantity]];
  }
  [self.unknownFields writeDescriptionTo:output withIndent:indent];
}
- (BOOL) isEqual:(id)other {
  if (other == self) {
    return YES;
  }
  if (![other isKindOfClass:[UserItemProto class]]) {
    return NO;
  }
  UserItemProto *otherMessage = other;
  return
      self.hasUserId == otherMessage.hasUserId &&
      (!self.hasUserId || self.userId == otherMessage.userId) &&
      self.hasItemId == otherMessage.hasItemId &&
      (!self.hasItemId || self.itemId == otherMessage.itemId) &&
      self.hasQuantity == otherMessage.hasQuantity &&
      (!self.hasQuantity || self.quantity == otherMessage.quantity) &&
      (self.unknownFields == otherMessage.unknownFields || (self.unknownFields != nil && [self.unknownFields isEqual:otherMessage.unknownFields]));
}
- (NSUInteger) hash {
  __block NSUInteger hashCode = 7;
  if (self.hasUserId) {
    hashCode = hashCode * 31 + [[NSNumber numberWithInteger:self.userId] hash];
  }
  if (self.hasItemId) {
    hashCode = hashCode * 31 + [[NSNumber numberWithInteger:self.itemId] hash];
  }
  if (self.hasQuantity) {
    hashCode = hashCode * 31 + [[NSNumber numberWithInteger:self.quantity] hash];
  }
  hashCode = hashCode * 31 + [self.unknownFields hash];
  return hashCode;
}
@end

@interface UserItemProto_Builder()
@property (strong) UserItemProto* result;
@end

@implementation UserItemProto_Builder
@synthesize result;
- (id) init {
  if ((self = [super init])) {
    self.result = [[UserItemProto alloc] init];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return result;
}
- (UserItemProto_Builder*) clear {
  self.result = [[UserItemProto alloc] init];
  return self;
}
- (UserItemProto_Builder*) clone {
  return [UserItemProto builderWithPrototype:result];
}
- (UserItemProto*) defaultInstance {
  return [UserItemProto defaultInstance];
}
- (UserItemProto*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (UserItemProto*) buildPartial {
  UserItemProto* returnMe = result;
  self.result = nil;
  return returnMe;
}
- (UserItemProto_Builder*) mergeFrom:(UserItemProto*) other {
  if (other == [UserItemProto defaultInstance]) {
    return self;
  }
  if (other.hasUserId) {
    [self setUserId:other.userId];
  }
  if (other.hasItemId) {
    [self setItemId:other.itemId];
  }
  if (other.hasQuantity) {
    [self setQuantity:other.quantity];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (UserItemProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (UserItemProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSetBuilder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    SInt32 tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 8: {
        [self setUserId:[input readInt32]];
        break;
      }
      case 16: {
        [self setItemId:[input readInt32]];
        break;
      }
      case 24: {
        [self setQuantity:[input readInt32]];
        break;
      }
    }
  }
}
- (BOOL) hasUserId {
  return result.hasUserId;
}
- (int32_t) userId {
  return result.userId;
}
- (UserItemProto_Builder*) setUserId:(int32_t) value {
  result.hasUserId = YES;
  result.userId = value;
  return self;
}
- (UserItemProto_Builder*) clearUserId {
  result.hasUserId = NO;
  result.userId = 0;
  return self;
}
- (BOOL) hasItemId {
  return result.hasItemId;
}
- (int32_t) itemId {
  return result.itemId;
}
- (UserItemProto_Builder*) setItemId:(int32_t) value {
  result.hasItemId = YES;
  result.itemId = value;
  return self;
}
- (UserItemProto_Builder*) clearItemId {
  result.hasItemId = NO;
  result.itemId = 0;
  return self;
}
- (BOOL) hasQuantity {
  return result.hasQuantity;
}
- (int32_t) quantity {
  return result.quantity;
}
- (UserItemProto_Builder*) setQuantity:(int32_t) value {
  result.hasQuantity = YES;
  result.quantity = value;
  return self;
}
- (UserItemProto_Builder*) clearQuantity {
  result.hasQuantity = NO;
  result.quantity = 0;
  return self;
}
@end

@interface ItemProto ()
@property int32_t itemId;
@property (strong) NSString* name;
@property (strong) NSString* imgName;
@property ItemType itemType;
@property int32_t staticDataId;
@end

@implementation ItemProto

- (BOOL) hasItemId {
  return !!hasItemId_;
}
- (void) setHasItemId:(BOOL) value_ {
  hasItemId_ = !!value_;
}
@synthesize itemId;
- (BOOL) hasName {
  return !!hasName_;
}
- (void) setHasName:(BOOL) value_ {
  hasName_ = !!value_;
}
@synthesize name;
- (BOOL) hasImgName {
  return !!hasImgName_;
}
- (void) setHasImgName:(BOOL) value_ {
  hasImgName_ = !!value_;
}
@synthesize imgName;
- (BOOL) hasItemType {
  return !!hasItemType_;
}
- (void) setHasItemType:(BOOL) value_ {
  hasItemType_ = !!value_;
}
@synthesize itemType;
- (BOOL) hasStaticDataId {
  return !!hasStaticDataId_;
}
- (void) setHasStaticDataId:(BOOL) value_ {
  hasStaticDataId_ = !!value_;
}
@synthesize staticDataId;
- (id) init {
  if ((self = [super init])) {
    self.itemId = 0;
    self.name = @"";
    self.imgName = @"";
    self.itemType = ItemTypeBoosterPack;
    self.staticDataId = 0;
  }
  return self;
}
static ItemProto* defaultItemProtoInstance = nil;
+ (void) initialize {
  if (self == [ItemProto class]) {
    defaultItemProtoInstance = [[ItemProto alloc] init];
  }
}
+ (ItemProto*) defaultInstance {
  return defaultItemProtoInstance;
}
- (ItemProto*) defaultInstance {
  return defaultItemProtoInstance;
}
- (BOOL) isInitialized {
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasItemId) {
    [output writeInt32:1 value:self.itemId];
  }
  if (self.hasName) {
    [output writeString:2 value:self.name];
  }
  if (self.hasImgName) {
    [output writeString:3 value:self.imgName];
  }
  if (self.hasItemType) {
    [output writeEnum:4 value:self.itemType];
  }
  if (self.hasStaticDataId) {
    [output writeInt32:5 value:self.staticDataId];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (SInt32) serializedSize {
  __block SInt32 size_ = memoizedSerializedSize;
  if (size_ != -1) {
    return size_;
  }

  size_ = 0;
  if (self.hasItemId) {
    size_ += computeInt32Size(1, self.itemId);
  }
  if (self.hasName) {
    size_ += computeStringSize(2, self.name);
  }
  if (self.hasImgName) {
    size_ += computeStringSize(3, self.imgName);
  }
  if (self.hasItemType) {
    size_ += computeEnumSize(4, self.itemType);
  }
  if (self.hasStaticDataId) {
    size_ += computeInt32Size(5, self.staticDataId);
  }
  size_ += self.unknownFields.serializedSize;
  memoizedSerializedSize = size_;
  return size_;
}
+ (ItemProto*) parseFromData:(NSData*) data {
  return (ItemProto*)[[[ItemProto builder] mergeFromData:data] build];
}
+ (ItemProto*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (ItemProto*)[[[ItemProto builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (ItemProto*) parseFromInputStream:(NSInputStream*) input {
  return (ItemProto*)[[[ItemProto builder] mergeFromInputStream:input] build];
}
+ (ItemProto*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (ItemProto*)[[[ItemProto builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (ItemProto*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (ItemProto*)[[[ItemProto builder] mergeFromCodedInputStream:input] build];
}
+ (ItemProto*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (ItemProto*)[[[ItemProto builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (ItemProto_Builder*) builder {
  return [[ItemProto_Builder alloc] init];
}
+ (ItemProto_Builder*) builderWithPrototype:(ItemProto*) prototype {
  return [[ItemProto builder] mergeFrom:prototype];
}
- (ItemProto_Builder*) builder {
  return [ItemProto builder];
}
- (ItemProto_Builder*) toBuilder {
  return [ItemProto builderWithPrototype:self];
}
- (void) writeDescriptionTo:(NSMutableString*) output withIndent:(NSString*) indent {
  if (self.hasItemId) {
    [output appendFormat:@"%@%@: %@\n", indent, @"itemId", [NSNumber numberWithInteger:self.itemId]];
  }
  if (self.hasName) {
    [output appendFormat:@"%@%@: %@\n", indent, @"name", self.name];
  }
  if (self.hasImgName) {
    [output appendFormat:@"%@%@: %@\n", indent, @"imgName", self.imgName];
  }
  if (self.hasItemType) {
    [output appendFormat:@"%@%@: %d\n", indent, @"itemType", self.itemType];
  }
  if (self.hasStaticDataId) {
    [output appendFormat:@"%@%@: %@\n", indent, @"staticDataId", [NSNumber numberWithInteger:self.staticDataId]];
  }
  [self.unknownFields writeDescriptionTo:output withIndent:indent];
}
- (BOOL) isEqual:(id)other {
  if (other == self) {
    return YES;
  }
  if (![other isKindOfClass:[ItemProto class]]) {
    return NO;
  }
  ItemProto *otherMessage = other;
  return
      self.hasItemId == otherMessage.hasItemId &&
      (!self.hasItemId || self.itemId == otherMessage.itemId) &&
      self.hasName == otherMessage.hasName &&
      (!self.hasName || [self.name isEqual:otherMessage.name]) &&
      self.hasImgName == otherMessage.hasImgName &&
      (!self.hasImgName || [self.imgName isEqual:otherMessage.imgName]) &&
      self.hasItemType == otherMessage.hasItemType &&
      (!self.hasItemType || self.itemType == otherMessage.itemType) &&
      self.hasStaticDataId == otherMessage.hasStaticDataId &&
      (!self.hasStaticDataId || self.staticDataId == otherMessage.staticDataId) &&
      (self.unknownFields == otherMessage.unknownFields || (self.unknownFields != nil && [self.unknownFields isEqual:otherMessage.unknownFields]));
}
- (NSUInteger) hash {
  __block NSUInteger hashCode = 7;
  if (self.hasItemId) {
    hashCode = hashCode * 31 + [[NSNumber numberWithInteger:self.itemId] hash];
  }
  if (self.hasName) {
    hashCode = hashCode * 31 + [self.name hash];
  }
  if (self.hasImgName) {
    hashCode = hashCode * 31 + [self.imgName hash];
  }
  if (self.hasItemType) {
    hashCode = hashCode * 31 + self.itemType;
  }
  if (self.hasStaticDataId) {
    hashCode = hashCode * 31 + [[NSNumber numberWithInteger:self.staticDataId] hash];
  }
  hashCode = hashCode * 31 + [self.unknownFields hash];
  return hashCode;
}
@end

@interface ItemProto_Builder()
@property (strong) ItemProto* result;
@end

@implementation ItemProto_Builder
@synthesize result;
- (id) init {
  if ((self = [super init])) {
    self.result = [[ItemProto alloc] init];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return result;
}
- (ItemProto_Builder*) clear {
  self.result = [[ItemProto alloc] init];
  return self;
}
- (ItemProto_Builder*) clone {
  return [ItemProto builderWithPrototype:result];
}
- (ItemProto*) defaultInstance {
  return [ItemProto defaultInstance];
}
- (ItemProto*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (ItemProto*) buildPartial {
  ItemProto* returnMe = result;
  self.result = nil;
  return returnMe;
}
- (ItemProto_Builder*) mergeFrom:(ItemProto*) other {
  if (other == [ItemProto defaultInstance]) {
    return self;
  }
  if (other.hasItemId) {
    [self setItemId:other.itemId];
  }
  if (other.hasName) {
    [self setName:other.name];
  }
  if (other.hasImgName) {
    [self setImgName:other.imgName];
  }
  if (other.hasItemType) {
    [self setItemType:other.itemType];
  }
  if (other.hasStaticDataId) {
    [self setStaticDataId:other.staticDataId];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (ItemProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (ItemProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSetBuilder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    SInt32 tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 8: {
        [self setItemId:[input readInt32]];
        break;
      }
      case 18: {
        [self setName:[input readString]];
        break;
      }
      case 26: {
        [self setImgName:[input readString]];
        break;
      }
      case 32: {
        ItemType value = (ItemType)[input readEnum];
        if (ItemTypeIsValidValue(value)) {
          [self setItemType:value];
        } else {
          [unknownFields mergeVarintField:4 value:value];
        }
        break;
      }
      case 40: {
        [self setStaticDataId:[input readInt32]];
        break;
      }
    }
  }
}
- (BOOL) hasItemId {
  return result.hasItemId;
}
- (int32_t) itemId {
  return result.itemId;
}
- (ItemProto_Builder*) setItemId:(int32_t) value {
  result.hasItemId = YES;
  result.itemId = value;
  return self;
}
- (ItemProto_Builder*) clearItemId {
  result.hasItemId = NO;
  result.itemId = 0;
  return self;
}
- (BOOL) hasName {
  return result.hasName;
}
- (NSString*) name {
  return result.name;
}
- (ItemProto_Builder*) setName:(NSString*) value {
  result.hasName = YES;
  result.name = value;
  return self;
}
- (ItemProto_Builder*) clearName {
  result.hasName = NO;
  result.name = @"";
  return self;
}
- (BOOL) hasImgName {
  return result.hasImgName;
}
- (NSString*) imgName {
  return result.imgName;
}
- (ItemProto_Builder*) setImgName:(NSString*) value {
  result.hasImgName = YES;
  result.imgName = value;
  return self;
}
- (ItemProto_Builder*) clearImgName {
  result.hasImgName = NO;
  result.imgName = @"";
  return self;
}
- (BOOL) hasItemType {
  return result.hasItemType;
}
- (ItemType) itemType {
  return result.itemType;
}
- (ItemProto_Builder*) setItemType:(ItemType) value {
  result.hasItemType = YES;
  result.itemType = value;
  return self;
}
- (ItemProto_Builder*) clearItemType {
  result.hasItemType = NO;
  result.itemType = ItemTypeBoosterPack;
  return self;
}
- (BOOL) hasStaticDataId {
  return result.hasStaticDataId;
}
- (int32_t) staticDataId {
  return result.staticDataId;
}
- (ItemProto_Builder*) setStaticDataId:(int32_t) value {
  result.hasStaticDataId = YES;
  result.staticDataId = value;
  return self;
}
- (ItemProto_Builder*) clearStaticDataId {
  result.hasStaticDataId = NO;
  result.staticDataId = 0;
  return self;
}
@end


// @@protoc_insertion_point(global_scope)
