// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

#import "BoosterPackStuff.pb.h"
#import "City.pb.h"
#import "MonsterStuff.pb.h"
#import "Quest.pb.h"
#import "Structure.pb.h"
#import "Task.pb.h"
#import "User.pb.h"

@class BoosterDisplayItemProto;
@class BoosterDisplayItemProto_Builder;
@class BoosterItemProto;
@class BoosterItemProto_Builder;
@class BoosterPackProto;
@class BoosterPackProto_Builder;
@class CityElementProto;
@class CityElementProto_Builder;
@class CityExpansionCostProto;
@class CityExpansionCostProto_Builder;
@class CoordinateProto;
@class CoordinateProto_Builder;
@class DialogueProto;
@class DialogueProto_Builder;
@class DialogueProto_SpeechSegmentProto;
@class DialogueProto_SpeechSegmentProto_Builder;
@class FullCityProto;
@class FullCityProto_Builder;
@class FullQuestProto;
@class FullQuestProto_Builder;
@class FullTaskProto;
@class FullTaskProto_Builder;
@class FullUserMonsterProto;
@class FullUserMonsterProto_Builder;
@class FullUserProto;
@class FullUserProto_Builder;
@class FullUserQuestProto;
@class FullUserQuestProto_Builder;
@class FullUserStructureProto;
@class FullUserStructureProto_Builder;
@class HospitalProto;
@class HospitalProto_Builder;
@class LabProto;
@class LabProto_Builder;
@class MinimumClanProto;
@class MinimumClanProto_Builder;
@class MinimumUserMonsterSellProto;
@class MinimumUserMonsterSellProto_Builder;
@class MinimumUserProto;
@class MinimumUserProtoWithFacebookId;
@class MinimumUserProtoWithFacebookId_Builder;
@class MinimumUserProtoWithLevel;
@class MinimumUserProtoWithLevel_Builder;
@class MinimumUserProtoWithMaxResources;
@class MinimumUserProtoWithMaxResources_Builder;
@class MinimumUserProto_Builder;
@class MinimumUserTaskProto;
@class MinimumUserTaskProto_Builder;
@class MonsterLevelInfoProto;
@class MonsterLevelInfoProto_Builder;
@class MonsterProto;
@class MonsterProto_Builder;
@class PersistentEventProto;
@class PersistentEventProto_Builder;
@class RareBoosterPurchaseProto;
@class RareBoosterPurchaseProto_Builder;
@class ResidenceProto;
@class ResidenceProto_Builder;
@class ResourceGeneratorProto;
@class ResourceGeneratorProto_Builder;
@class ResourceStorageProto;
@class ResourceStorageProto_Builder;
@class StaticDataProto;
@class StaticDataProto_Builder;
@class StaticUserLevelInfoProto;
@class StaticUserLevelInfoProto_Builder;
@class StructureInfoProto;
@class StructureInfoProto_Builder;
@class TaskStageMonsterProto;
@class TaskStageMonsterProto_Builder;
@class TaskStageProto;
@class TaskStageProto_Builder;
@class TownHallProto;
@class TownHallProto_Builder;
@class UserCityExpansionDataProto;
@class UserCityExpansionDataProto_Builder;
@class UserCurrentMonsterTeamProto;
@class UserCurrentMonsterTeamProto_Builder;
@class UserEnhancementItemProto;
@class UserEnhancementItemProto_Builder;
@class UserEnhancementProto;
@class UserEnhancementProto_Builder;
@class UserFacebookInviteForSlotProto;
@class UserFacebookInviteForSlotProto_Builder;
@class UserMonsterCurrentExpProto;
@class UserMonsterCurrentExpProto_Builder;
@class UserMonsterCurrentHealthProto;
@class UserMonsterCurrentHealthProto_Builder;
@class UserMonsterEvolutionProto;
@class UserMonsterEvolutionProto_Builder;
@class UserMonsterHealingProto;
@class UserMonsterHealingProto_Builder;
@class UserPersistentEventProto;
@class UserPersistentEventProto_Builder;

@interface StaticDataRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface StaticDataProto : PBGeneratedMessage {
@private
  BOOL hasSender_:1;
  MinimumUserProto* sender;
  NSMutableArray* mutableEventsList;
  NSMutableArray* mutableAllTownHallsList;
  NSMutableArray* mutableAllLabsList;
  NSMutableArray* mutableAllResidencesList;
  NSMutableArray* mutableAllHospitalsList;
  NSMutableArray* mutableAllStoragesList;
  NSMutableArray* mutableAllGeneratorsList;
  NSMutableArray* mutableBoosterPacksList;
  NSMutableArray* mutableAvailableQuestsList;
  NSMutableArray* mutableUnredeemedQuestsList;
  NSMutableArray* mutableInProgressQuestsList;
  NSMutableArray* mutableSlipList;
  NSMutableArray* mutableAllMonstersList;
  NSMutableArray* mutableAllTasksList;
  NSMutableArray* mutableAllCitiesList;
  NSMutableArray* mutableExpansionCostsList;
}
- (BOOL) hasSender;
@property (readonly, retain) MinimumUserProto* sender;
- (NSArray*) expansionCostsList;
- (CityExpansionCostProto*) expansionCostsAtIndex:(int32_t) index;
- (NSArray*) allCitiesList;
- (FullCityProto*) allCitiesAtIndex:(int32_t) index;
- (NSArray*) allTasksList;
- (FullTaskProto*) allTasksAtIndex:(int32_t) index;
- (NSArray*) allMonstersList;
- (MonsterProto*) allMonstersAtIndex:(int32_t) index;
- (NSArray*) slipList;
- (StaticUserLevelInfoProto*) slipAtIndex:(int32_t) index;
- (NSArray*) inProgressQuestsList;
- (FullQuestProto*) inProgressQuestsAtIndex:(int32_t) index;
- (NSArray*) unredeemedQuestsList;
- (FullQuestProto*) unredeemedQuestsAtIndex:(int32_t) index;
- (NSArray*) availableQuestsList;
- (FullQuestProto*) availableQuestsAtIndex:(int32_t) index;
- (NSArray*) boosterPacksList;
- (BoosterPackProto*) boosterPacksAtIndex:(int32_t) index;
- (NSArray*) allGeneratorsList;
- (ResourceGeneratorProto*) allGeneratorsAtIndex:(int32_t) index;
- (NSArray*) allStoragesList;
- (ResourceStorageProto*) allStoragesAtIndex:(int32_t) index;
- (NSArray*) allHospitalsList;
- (HospitalProto*) allHospitalsAtIndex:(int32_t) index;
- (NSArray*) allResidencesList;
- (ResidenceProto*) allResidencesAtIndex:(int32_t) index;
- (NSArray*) allLabsList;
- (LabProto*) allLabsAtIndex:(int32_t) index;
- (NSArray*) allTownHallsList;
- (TownHallProto*) allTownHallsAtIndex:(int32_t) index;
- (NSArray*) eventsList;
- (PersistentEventProto*) eventsAtIndex:(int32_t) index;

+ (StaticDataProto*) defaultInstance;
- (StaticDataProto*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (StaticDataProto_Builder*) builder;
+ (StaticDataProto_Builder*) builder;
+ (StaticDataProto_Builder*) builderWithPrototype:(StaticDataProto*) prototype;

+ (StaticDataProto*) parseFromData:(NSData*) data;
+ (StaticDataProto*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (StaticDataProto*) parseFromInputStream:(NSInputStream*) input;
+ (StaticDataProto*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (StaticDataProto*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (StaticDataProto*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface StaticDataProto_Builder : PBGeneratedMessage_Builder {
@private
  StaticDataProto* result;
}

- (StaticDataProto*) defaultInstance;

- (StaticDataProto_Builder*) clear;
- (StaticDataProto_Builder*) clone;

- (StaticDataProto*) build;
- (StaticDataProto*) buildPartial;

- (StaticDataProto_Builder*) mergeFrom:(StaticDataProto*) other;
- (StaticDataProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (StaticDataProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasSender;
- (MinimumUserProto*) sender;
- (StaticDataProto_Builder*) setSender:(MinimumUserProto*) value;
- (StaticDataProto_Builder*) setSenderBuilder:(MinimumUserProto_Builder*) builderForValue;
- (StaticDataProto_Builder*) mergeSender:(MinimumUserProto*) value;
- (StaticDataProto_Builder*) clearSender;

- (NSArray*) expansionCostsList;
- (CityExpansionCostProto*) expansionCostsAtIndex:(int32_t) index;
- (StaticDataProto_Builder*) replaceExpansionCostsAtIndex:(int32_t) index with:(CityExpansionCostProto*) value;
- (StaticDataProto_Builder*) addExpansionCosts:(CityExpansionCostProto*) value;
- (StaticDataProto_Builder*) addAllExpansionCosts:(NSArray*) values;
- (StaticDataProto_Builder*) clearExpansionCostsList;

- (NSArray*) allCitiesList;
- (FullCityProto*) allCitiesAtIndex:(int32_t) index;
- (StaticDataProto_Builder*) replaceAllCitiesAtIndex:(int32_t) index with:(FullCityProto*) value;
- (StaticDataProto_Builder*) addAllCities:(FullCityProto*) value;
- (StaticDataProto_Builder*) addAllAllCities:(NSArray*) values;
- (StaticDataProto_Builder*) clearAllCitiesList;

- (NSArray*) allTasksList;
- (FullTaskProto*) allTasksAtIndex:(int32_t) index;
- (StaticDataProto_Builder*) replaceAllTasksAtIndex:(int32_t) index with:(FullTaskProto*) value;
- (StaticDataProto_Builder*) addAllTasks:(FullTaskProto*) value;
- (StaticDataProto_Builder*) addAllAllTasks:(NSArray*) values;
- (StaticDataProto_Builder*) clearAllTasksList;

- (NSArray*) allMonstersList;
- (MonsterProto*) allMonstersAtIndex:(int32_t) index;
- (StaticDataProto_Builder*) replaceAllMonstersAtIndex:(int32_t) index with:(MonsterProto*) value;
- (StaticDataProto_Builder*) addAllMonsters:(MonsterProto*) value;
- (StaticDataProto_Builder*) addAllAllMonsters:(NSArray*) values;
- (StaticDataProto_Builder*) clearAllMonstersList;

- (NSArray*) slipList;
- (StaticUserLevelInfoProto*) slipAtIndex:(int32_t) index;
- (StaticDataProto_Builder*) replaceSlipAtIndex:(int32_t) index with:(StaticUserLevelInfoProto*) value;
- (StaticDataProto_Builder*) addSlip:(StaticUserLevelInfoProto*) value;
- (StaticDataProto_Builder*) addAllSlip:(NSArray*) values;
- (StaticDataProto_Builder*) clearSlipList;

- (NSArray*) inProgressQuestsList;
- (FullQuestProto*) inProgressQuestsAtIndex:(int32_t) index;
- (StaticDataProto_Builder*) replaceInProgressQuestsAtIndex:(int32_t) index with:(FullQuestProto*) value;
- (StaticDataProto_Builder*) addInProgressQuests:(FullQuestProto*) value;
- (StaticDataProto_Builder*) addAllInProgressQuests:(NSArray*) values;
- (StaticDataProto_Builder*) clearInProgressQuestsList;

- (NSArray*) unredeemedQuestsList;
- (FullQuestProto*) unredeemedQuestsAtIndex:(int32_t) index;
- (StaticDataProto_Builder*) replaceUnredeemedQuestsAtIndex:(int32_t) index with:(FullQuestProto*) value;
- (StaticDataProto_Builder*) addUnredeemedQuests:(FullQuestProto*) value;
- (StaticDataProto_Builder*) addAllUnredeemedQuests:(NSArray*) values;
- (StaticDataProto_Builder*) clearUnredeemedQuestsList;

- (NSArray*) availableQuestsList;
- (FullQuestProto*) availableQuestsAtIndex:(int32_t) index;
- (StaticDataProto_Builder*) replaceAvailableQuestsAtIndex:(int32_t) index with:(FullQuestProto*) value;
- (StaticDataProto_Builder*) addAvailableQuests:(FullQuestProto*) value;
- (StaticDataProto_Builder*) addAllAvailableQuests:(NSArray*) values;
- (StaticDataProto_Builder*) clearAvailableQuestsList;

- (NSArray*) boosterPacksList;
- (BoosterPackProto*) boosterPacksAtIndex:(int32_t) index;
- (StaticDataProto_Builder*) replaceBoosterPacksAtIndex:(int32_t) index with:(BoosterPackProto*) value;
- (StaticDataProto_Builder*) addBoosterPacks:(BoosterPackProto*) value;
- (StaticDataProto_Builder*) addAllBoosterPacks:(NSArray*) values;
- (StaticDataProto_Builder*) clearBoosterPacksList;

- (NSArray*) allGeneratorsList;
- (ResourceGeneratorProto*) allGeneratorsAtIndex:(int32_t) index;
- (StaticDataProto_Builder*) replaceAllGeneratorsAtIndex:(int32_t) index with:(ResourceGeneratorProto*) value;
- (StaticDataProto_Builder*) addAllGenerators:(ResourceGeneratorProto*) value;
- (StaticDataProto_Builder*) addAllAllGenerators:(NSArray*) values;
- (StaticDataProto_Builder*) clearAllGeneratorsList;

- (NSArray*) allStoragesList;
- (ResourceStorageProto*) allStoragesAtIndex:(int32_t) index;
- (StaticDataProto_Builder*) replaceAllStoragesAtIndex:(int32_t) index with:(ResourceStorageProto*) value;
- (StaticDataProto_Builder*) addAllStorages:(ResourceStorageProto*) value;
- (StaticDataProto_Builder*) addAllAllStorages:(NSArray*) values;
- (StaticDataProto_Builder*) clearAllStoragesList;

- (NSArray*) allHospitalsList;
- (HospitalProto*) allHospitalsAtIndex:(int32_t) index;
- (StaticDataProto_Builder*) replaceAllHospitalsAtIndex:(int32_t) index with:(HospitalProto*) value;
- (StaticDataProto_Builder*) addAllHospitals:(HospitalProto*) value;
- (StaticDataProto_Builder*) addAllAllHospitals:(NSArray*) values;
- (StaticDataProto_Builder*) clearAllHospitalsList;

- (NSArray*) allResidencesList;
- (ResidenceProto*) allResidencesAtIndex:(int32_t) index;
- (StaticDataProto_Builder*) replaceAllResidencesAtIndex:(int32_t) index with:(ResidenceProto*) value;
- (StaticDataProto_Builder*) addAllResidences:(ResidenceProto*) value;
- (StaticDataProto_Builder*) addAllAllResidences:(NSArray*) values;
- (StaticDataProto_Builder*) clearAllResidencesList;

- (NSArray*) allLabsList;
- (LabProto*) allLabsAtIndex:(int32_t) index;
- (StaticDataProto_Builder*) replaceAllLabsAtIndex:(int32_t) index with:(LabProto*) value;
- (StaticDataProto_Builder*) addAllLabs:(LabProto*) value;
- (StaticDataProto_Builder*) addAllAllLabs:(NSArray*) values;
- (StaticDataProto_Builder*) clearAllLabsList;

- (NSArray*) allTownHallsList;
- (TownHallProto*) allTownHallsAtIndex:(int32_t) index;
- (StaticDataProto_Builder*) replaceAllTownHallsAtIndex:(int32_t) index with:(TownHallProto*) value;
- (StaticDataProto_Builder*) addAllTownHalls:(TownHallProto*) value;
- (StaticDataProto_Builder*) addAllAllTownHalls:(NSArray*) values;
- (StaticDataProto_Builder*) clearAllTownHallsList;

- (NSArray*) eventsList;
- (PersistentEventProto*) eventsAtIndex:(int32_t) index;
- (StaticDataProto_Builder*) replaceEventsAtIndex:(int32_t) index with:(PersistentEventProto*) value;
- (StaticDataProto_Builder*) addEvents:(PersistentEventProto*) value;
- (StaticDataProto_Builder*) addAllEvents:(NSArray*) values;
- (StaticDataProto_Builder*) clearEventsList;
@end

